// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// Common constants, all parameters must be provided unless they are marked as optional
///
/// {DCD35AD7-4E4A-4BAD-A90C-E0C49EB23AFE}
/// </summary>
/// <remarks>
/// Source: include/sl_consts.h:182.
/// </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 456)]
public unsafe partial struct Constants : ISLStructure
{
    /// <summary>
    /// sl::BaseStructure::next
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:112.
    /// </remarks>
    public BaseStructure* Next;

    /// <summary>
    /// sl::BaseStructure::structType
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:113.
    /// </remarks>
    public StructType StructType;

    /// <summary>
    /// sl::BaseStructure::structVersion
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:114.
    /// </remarks>
    public nuint StructVersion;

    /// <summary>
    /// Native structure type identifier.
    /// </summary>
    public static StructType TypeId => new(0xdcd35ad7, 0x4e4a, 0x4bad, [0xa9, 0xc, 0xe0, 0xc4, 0x9e, 0xb2, 0x3a, 0xfe]);

    /// <summary>
    /// Specifies matrix transformation from the camera view to the clip space.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:188.
    /// </remarks>
    public Float4x4 CameraViewToClip;

    /// <summary>
    /// Specifies matrix transformation from the clip space to the camera view space.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:190.
    /// </remarks>
    public Float4x4 ClipToCameraView;

    /// <summary>
    /// Optional - Specifies matrix transformation describing lens distortion in clip space.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:192.
    /// </remarks>
    public Float4x4 ClipToLensClip;

    /// <summary>
    /// Specifies matrix transformation from the current clip to the previous clip space.
    /// clipToPrevClip = clipToView * viewToViewPrev * viewToClipPrev
    /// Sample code can be found in sl_matrix_helpers.h
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:196.
    /// </remarks>
    public Float4x4 ClipToPrevClip;

    /// <summary>
    /// Specifies matrix transformation from the previous clip to the current clip space.
    /// prevClipToClip = clipToPrevClip.inverse()
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:199.
    /// </remarks>
    public Float4x4 PrevClipToClip;

    /// <summary>
    /// Specifies pixel space jitter offset
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:202.
    /// </remarks>
    public Float2 JitterOffset;

    /// <summary>
    /// Specifies scale factors used to normalize motion vectors (so the values are in [-1,1] range)
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:204.
    /// </remarks>
    public Float2 MvecScale;

    /// <summary>
    /// Optional - Specifies camera pinhole offset if used.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:206.
    /// </remarks>
    public Float2 CameraPinholeOffset;

    /// <summary>
    /// Specifies camera position in world space.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:208.
    /// </remarks>
    public Float3 CameraPos;

    /// <summary>
    /// Specifies camera up vector in world space.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:210.
    /// </remarks>
    public Float3 CameraUp;

    /// <summary>
    /// Specifies camera right vector in world space.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:212.
    /// </remarks>
    public Float3 CameraRight;

    /// <summary>
    /// Specifies camera forward vector in world space.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:214.
    /// </remarks>
    public Float3 CameraFwd;

    /// <summary>
    /// Specifies camera near view plane distance.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:217.
    /// </remarks>
    public float CameraNear;

    /// <summary>
    /// Specifies camera far view plane distance.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:219.
    /// </remarks>
    public float CameraFar;

    /// <summary>
    /// Specifies camera field of view in radians.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:221.
    /// </remarks>
    public float CameraFOV;

    /// <summary>
    /// Specifies camera aspect ratio defined as view space width divided by height.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:223.
    /// </remarks>
    public float CameraAspectRatio;

    /// <summary>
    /// Specifies which value represents an invalid (un-initialized) value in the motion vectors buffer
    /// NOTE: This is only required if `cameraMotionIncluded` is set to false and SL needs to compute it.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:226.
    /// </remarks>
    public float MotionVectorsInvalidValue;

    /// <summary>
    /// Specifies if depth values are inverted (value closer to the camera is higher) or not.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:229.
    /// </remarks>
    public SLBoolean DepthInverted;

    /// <summary>
    /// Specifies if camera motion is included in the MVec buffer.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:231.
    /// </remarks>
    public SLBoolean CameraMotionIncluded;

    /// <summary>
    /// Specifies if motion vectors are 3D or not.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:233.
    /// </remarks>
    public SLBoolean MotionVectors3D;

    /// <summary>
    /// Specifies if previous frame has no connection to the current one (i.e. motion vectors are invalid)
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:235.
    /// </remarks>
    public SLBoolean Reset;

    /// <summary>
    /// Specifies if orthographic projection is used or not.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:237.
    /// </remarks>
    public SLBoolean OrthographicProjection;

    /// <summary>
    /// Specifies if motion vectors are already dilated or not.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:239.
    /// </remarks>
    public SLBoolean MotionVectorsDilated;

    /// <summary>
    /// Specifies if motion vectors are jittered or not.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:241.
    /// </remarks>
    public SLBoolean MotionVectorsJittered;

    /// <summary>
    /// Version 2 members:
    ///
    /// Optional heuristic that specifies the minimum depth difference between two objects in screen-space.
    /// The units of the value are in linear depth units.
    /// Linear depth is computed as:
    /// if depthInverted is false:  `lin_depth = 1 / (1 - depth)`
    /// if depthInverted is true:   `lin_depth = 1 / depth`
    ///
    /// Although unlikely to need to be modified, smaller thresholds are useful when depth units are
    /// unusually compressed into a small dynamic range near 1.
    ///
    /// If not specified, the default value is 40.0f.
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:255.
    /// </remarks>
    public float MinRelativeLinearDepthObjectSeparation;

    /// <summary>
    /// Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.
    /// </summary>
    public Constants()
    {
        this = default;

        StructType = TypeId;
        StructVersion = SL.StructVersion2;
        CameraViewToClip = new();
        ClipToCameraView = new();
        ClipToLensClip = new();
        ClipToPrevClip = new();
        PrevClipToClip = new();
        JitterOffset = new();
        MvecScale = new();
        CameraPinholeOffset = new();
        CameraPos = new();
        CameraUp = new();
        CameraRight = new();
        CameraFwd = new();
        CameraNear = float.MaxValue;
        CameraFar = float.MaxValue;
        CameraFOV = float.MaxValue;
        CameraAspectRatio = float.MaxValue;
        MotionVectorsInvalidValue = float.MaxValue;
        DepthInverted = (SLBoolean)2;
        CameraMotionIncluded = (SLBoolean)2;
        MotionVectors3D = (SLBoolean)2;
        Reset = (SLBoolean)2;
        MinRelativeLinearDepthObjectSeparation = 40f;
    }
}
