// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// sl::float4x4
/// </summary>
/// <remarks>
/// Source: include/sl_consts.h:131.
/// </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 4, Size = 64)]
public unsafe partial struct Float4x4
{
    /// <summary>
    /// Row major matrix
    /// </summary>
    /// <remarks>
    /// Source: include/sl_consts.h:140.
    /// </remarks>
    public RowBuffer Row;

    /// <summary>
    /// Inline storage for 4 native Float4 elements.
    /// </summary>
    [InlineArray(4)]
    public struct RowBuffer
    {
        private Float4 element;
    }

    /// <summary>
    /// Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.
    /// </summary>
    public Float4x4()
    {
        this = default;

        for (int index = 0; index < 4; index++)
        {
            Row[index] = new();
        }
    }
}
