// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

namespace Streamline.NET;

/// <summary>
/// Log type
/// </summary>
/// <remarks>
/// Source: include/sl_core_types.h:490.
/// </remarks>
public enum LogType : uint
{
    /// <summary>
    /// Controlled by LogLevel, SL can show more information in eLogLevelVerbose mode
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:493.
    /// </remarks>
    Info = 0,

    /// <summary>
    /// Always shown regardless of LogLevel
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:495.
    /// </remarks>
    Warn = 1,

    /// <summary>
    /// Always shown regardless of LogLevel
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:496.
    /// </remarks>
    Error = 2,

    /// <summary>
    /// Total count
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:498.
    /// </remarks>
    Count = 3,
}
