// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// tagRECT
/// </summary>
/// <remarks>
/// Source: system/windef.h:154.
/// </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 4, Size = 16)]
public unsafe partial struct Rect
{
    /// <summary>
    /// tagRECT::left
    /// </summary>
    /// <remarks>
    /// Source: system/windef.h:156.
    /// </remarks>
    public int Left;

    /// <summary>
    /// tagRECT::top
    /// </summary>
    /// <remarks>
    /// Source: system/windef.h:157.
    /// </remarks>
    public int Top;

    /// <summary>
    /// tagRECT::right
    /// </summary>
    /// <remarks>
    /// Source: system/windef.h:158.
    /// </remarks>
    public int Right;

    /// <summary>
    /// tagRECT::bottom
    /// </summary>
    /// <remarks>
    /// Source: system/windef.h:159.
    /// </remarks>
    public int Bottom;

    /// <summary>
    /// Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.
    /// </summary>
    public Rect()
    {
        this = default;
    }
}
