// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// Tagged resource
///
/// {4C6A5AAD-B445-496C-87FF-1AF3845BE653}
/// Extensions as part of the `next` ptr:
/// PrecisionInfo
/// </summary>
/// <remarks>
/// Source: include/sl_core_types.h:412.
/// </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 64)]
public unsafe partial struct ResourceTag : ISLStructure
{
    /// <summary>
    /// sl::BaseStructure::next
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:112.
    /// </remarks>
    public BaseStructure* Next;

    /// <summary>
    /// sl::BaseStructure::structType
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:113.
    /// </remarks>
    public StructType StructType;

    /// <summary>
    /// sl::BaseStructure::structVersion
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:114.
    /// </remarks>
    public nuint StructVersion;

    /// <summary>
    /// Native structure type identifier.
    /// </summary>
    public static StructType TypeId => new(0x4c6a5aad, 0xb445, 0x496c, [0x87, 0xff, 0x1a, 0xf3, 0x84, 0x5b, 0xe6, 0x53]);

    /// <summary>
    /// Resource description
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:420.
    /// </remarks>
    public Resource* Resource;

    /// <summary>
    /// Type of the tagged buffer
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:422.
    /// </remarks>
    public uint Type;

    /// <summary>
    /// The life-cycle for the tag, if resource is volatile a valid command buffer must be specified
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:424.
    /// </remarks>
    public ResourceLifecycle Lifecycle;

    /// <summary>
    /// The area of the tagged resource to use (if using the entire resource leave as null)
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:426.
    /// </remarks>
    public Extent Extent;

    /// <summary>
    /// Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.
    /// </summary>
    public ResourceTag()
    {
        this = default;

        StructType = TypeId;
        StructVersion = SL.StructVersion1;
        Extent = new();
    }

    /// <summary>
    /// sl::ResourceTag::ResourceTag
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:413.
    /// </remarks>
    public ResourceTag(Resource* r, uint t, ResourceLifecycle l, Extent* e = null) : this()
    {
        Resource = r;
        Type = t;
        Lifecycle = l;

        if (e != null)
        {
            Extent = *e;
        }
    }
}
