// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// Native resource
///
/// {3A9D70CF-2418-4B72-8391-13F8721C7261}
/// </summary>
/// <remarks>
/// Source: include/sl_core_types.h:331.
/// </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 112)]
public unsafe partial struct Resource : ISLStructure
{
    /// <summary>
    /// sl::BaseStructure::next
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:112.
    /// </remarks>
    public BaseStructure* Next;

    /// <summary>
    /// sl::BaseStructure::structType
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:113.
    /// </remarks>
    public StructType StructType;

    /// <summary>
    /// sl::BaseStructure::structVersion
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:114.
    /// </remarks>
    public nuint StructVersion;

    /// <summary>
    /// Native structure type identifier.
    /// </summary>
    public static StructType TypeId => new(0x3a9d70cf, 0x2418, 0x4b72, [0x83, 0x91, 0x13, 0xf8, 0x72, 0x1c, 0x72, 0x61]);

    /// <summary>
    /// Indicates the type of resource
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:348.
    /// </remarks>
    public ResourceType Type;

    /// <summary>
    /// ID3D11Resource/ID3D12Resource/VkBuffer/VkImage
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:350.
    /// </remarks>
    public void* Native;

    /// <summary>
    /// vkDeviceMemory or nullptr
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:352.
    /// </remarks>
    public void* Memory;

    /// <summary>
    /// VkImageView/VkBufferView or nullptr
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:354.
    /// </remarks>
    public void* View;

    /// <summary>
    /// State as D3D12_RESOURCE_STATES or VkImageLayout
    ///
    /// IMPORTANT: State is MANDATORY and needs to be correct when tagged resources are actually used.
    ///
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:359.
    /// </remarks>
    public uint State;

    /// <summary>
    /// Width in pixels
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:361.
    /// </remarks>
    public uint Width;

    /// <summary>
    /// Height in pixels
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:363.
    /// </remarks>
    public uint Height;

    /// <summary>
    /// Native format
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:365.
    /// </remarks>
    public uint NativeFormat;

    /// <summary>
    /// Number of mip-map levels
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:367.
    /// </remarks>
    public uint MipLevels;

    /// <summary>
    /// Number of arrays
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:369.
    /// </remarks>
    public uint ArrayLayers;

    /// <summary>
    /// Virtual address on GPU (if applicable)
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:371.
    /// </remarks>
    public ulong GpuVirtualAddress;

    /// <summary>
    /// VkImageCreateFlags
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:373.
    /// </remarks>
    public uint Flags;

    /// <summary>
    /// VkImageUsageFlags
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:375.
    /// </remarks>
    public uint Usage;

    /// <summary>
    /// sl::Resource::internalFlags
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:384.
    /// </remarks>
    public ushort InternalFlagsValue;

    /// <summary>
    /// Reserved for future use
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:386.
    /// </remarks>
    public ushort Reserved;

    /// <summary>
    /// Internal flags (bitfield) - do not modify
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:377.
    /// </remarks>
    [Flags]
    public enum InternalFlags : ushort
    {
        /// <summary>
        /// sl::Resource::InternalFlags::eNone
        /// </summary>
        /// <remarks>
        /// Source: include/sl_core_types.h:379.
        /// </remarks>
        None = 0,

        /// <summary>
        /// Resource wraps a Vulkan swapchain image not allocated by SL or the host callback.
        /// The release callback must not be invoked for such resources.
        /// </summary>
        /// <remarks>
        /// Source: include/sl_core_types.h:382.
        /// </remarks>
        VulkanSwapChainImage = 1,
    }

    /// <summary>
    /// Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.
    /// </summary>
    public Resource()
    {
        this = default;

        StructType = TypeId;
        StructVersion = SL.StructVersion1;
        State = 4294967295;
    }

    /// <summary>
    /// Constructors
    ///
    /// Resource type, native pointer are MANDATORY always
    /// Resource state is MANDATORY unless using D3D11
    /// Resource view, description etc. are MANDATORY only when using Vulkan
    ///
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:338.
    /// </remarks>
    public Resource(ResourceType type, void* native, void* mem, void* view, uint state = 4294967295) : this()
    {
        Type = type;
        Native = native;
        Memory = mem;
        View = view;
        State = state;
    }

    /// <summary>
    /// sl::Resource::Resource
    /// </summary>
    /// <remarks>
    /// Source: include/sl_core_types.h:339.
    /// </remarks>
    public Resource(ResourceType type, void* native, uint state = 4294967295) : this()
    {
        Type = type;
        Native = native;
        State = state;
    }
}
