// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

namespace Streamline.NET;

public static unsafe partial class SL
{
    /// <summary>
    /// Returns whether any bit in the mask is present, preserving the native Boolean operator&amp; semantics.
    /// </summary>
    public static bool HasAnyFlags(PreferenceFlags value, PreferenceFlags mask) => (value & mask) != 0;

    /// <summary>
    /// Returns whether any bit in the mask is present, preserving the native Boolean operator&amp; semantics.
    /// </summary>
    public static bool HasAnyFlags(FeatureRequirementFlags value, FeatureRequirementFlags mask) => (value & mask) != 0;
}
