// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.
// Source: NVIDIA-RTX/Streamline v2.14.1 (2122257e0fce486f91b385aa63b9a09b0a34b363).

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Streamline.NET;

public static unsafe partial class SL
{

    /// <summary>
    /// sl::getResultAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:81. </remarks>
    public static string GetResultAsStr(SLResult v)
    {
        return v switch
        {
            SLResult.Ok => "Result::eOk",
            SLResult.ErrorIO => "Result::eErrorIO",
            SLResult.ErrorDriverOutOfDate => "Result::eErrorDriverOutOfDate",
            SLResult.ErrorOSOutOfDate => "Result::eErrorOSOutOfDate",
            SLResult.ErrorOSDisabledHWS => "Result::eErrorOSDisabledHWS",
            SLResult.ErrorDeviceNotCreated => "Result::eErrorDeviceNotCreated",
            SLResult.ErrorNoSupportedAdapterFound => "Result::eErrorNoSupportedAdapterFound",
            SLResult.ErrorAdapterNotSupported => "Result::eErrorAdapterNotSupported",
            SLResult.ErrorNoPlugins => "Result::eErrorNoPlugins",
            SLResult.ErrorVulkanAPI => "Result::eErrorVulkanAPI",
            SLResult.ErrorDXGIAPI => "Result::eErrorDXGIAPI",
            SLResult.ErrorD3DAPI => "Result::eErrorD3DAPI",
            SLResult.ErrorNRDAPI => "Result::eErrorNRDAPI",
            SLResult.ErrorNVAPI => "Result::eErrorNVAPI",
            SLResult.ErrorReflexAPI => "Result::eErrorReflexAPI",
            SLResult.ErrorNGXFailed => "Result::eErrorNGXFailed",
            SLResult.ErrorJSONParsing => "Result::eErrorJSONParsing",
            SLResult.ErrorMissingProxy => "Result::eErrorMissingProxy",
            SLResult.ErrorMissingResourceState => "Result::eErrorMissingResourceState",
            SLResult.ErrorInvalidIntegration => "Result::eErrorInvalidIntegration",
            SLResult.ErrorMissingInputParameter => "Result::eErrorMissingInputParameter",
            SLResult.ErrorNotInitialized => "Result::eErrorNotInitialized",
            SLResult.ErrorComputeFailed => "Result::eErrorComputeFailed",
            SLResult.ErrorInitNotCalled => "Result::eErrorInitNotCalled",
            SLResult.ErrorExceptionHandler => "Result::eErrorExceptionHandler",
            SLResult.ErrorInvalidParameter => "Result::eErrorInvalidParameter",
            SLResult.ErrorMissingConstants => "Result::eErrorMissingConstants",
            SLResult.ErrorDuplicatedConstants => "Result::eErrorDuplicatedConstants",
            SLResult.ErrorMissingOrInvalidAPI => "Result::eErrorMissingOrInvalidAPI",
            SLResult.ErrorCommonConstantsMissing => "Result::eErrorCommonConstantsMissing",
            SLResult.ErrorUnsupportedInterface => "Result::eErrorUnsupportedInterface",
            SLResult.ErrorFeatureMissing => "Result::eErrorFeatureMissing",
            SLResult.ErrorFeatureNotSupported => "Result::eErrorFeatureNotSupported",
            SLResult.ErrorFeatureMissingHooks => "Result::eErrorFeatureMissingHooks",
            SLResult.ErrorFeatureFailedToLoad => "Result::eErrorFeatureFailedToLoad",
            SLResult.ErrorFeatureWrongPriority => "Result::eErrorFeatureWrongPriority",
            SLResult.ErrorFeatureMissingDependency => "Result::eErrorFeatureMissingDependency",
            SLResult.ErrorFeatureManagerInvalidState => "Result::eErrorFeatureManagerInvalidState",
            SLResult.ErrorInvalidState => "Result::eErrorInvalidState",
            SLResult.WarnOutOfVRAM => "Result::eWarnOutOfVRAM",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getNISModeAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:129. </remarks>
    public static string GetNISModeAsStr(NISMode v)
    {
        return v switch
        {
            NISMode.Off => "NISMode::eOff",
            NISMode.Scaler => "NISMode::eScaler",
            NISMode.Sharpen => "NISMode::eSharpen",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getNISHDRAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:141. </remarks>
    public static string GetNISHDRAsStr(NISHDR v)
    {
        return v switch
        {
            NISHDR.None => "NISHDR::eNone",
            NISHDR.Linear => "NISHDR::eLinear",
            NISHDR.PQ => "NISHDR::ePQ",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getReflexModeAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:153. </remarks>
    public static string GetReflexModeAsStr(ReflexMode mode)
    {
        return mode switch
        {
            ReflexMode.Off => "ReflexMode::eOff",
            ReflexMode.LowLatency => "ReflexMode::eLowLatency",
            ReflexMode.LowLatencyWithBoost => "ReflexMode::eLowLatencyWithBoost",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getPCLMarkerAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:165. </remarks>
    public static string GetPCLMarkerAsStr(PCLMarker marker)
    {
        return marker switch
        {
            PCLMarker.SimulationStart => "PCLMarker::eSimulationStart",
            PCLMarker.SimulationEnd => "PCLMarker::eSimulationEnd",
            PCLMarker.RenderSubmitStart => "PCLMarker::eRenderSubmitStart",
            PCLMarker.RenderSubmitEnd => "PCLMarker::eRenderSubmitEnd",
            PCLMarker.PresentStart => "PCLMarker::ePresentStart",
            PCLMarker.PresentEnd => "PCLMarker::ePresentEnd",
            PCLMarker.TriggerFlash => "PCLMarker::eTriggerFlash",
            PCLMarker.PCLatencyPing => "PCLMarker::ePCLatencyPing",
            PCLMarker.OutOfBandRenderSubmitStart => "PCLMarker::eOutOfBandRenderSubmitStart",
            PCLMarker.OutOfBandRenderSubmitEnd => "PCLMarker::eOutOfBandRenderSubmitEnd",
            PCLMarker.OutOfBandPresentStart => "PCLMarker::eOutOfBandPresentStart",
            PCLMarker.OutOfBandPresentEnd => "PCLMarker::eOutOfBandPresentEnd",
            PCLMarker.ControllerInputSample => "PCLMarker::eControllerInputSample",
            PCLMarker.DeltaTCalculation => "PCLMarker::eDeltaTCalculation",
            PCLMarker.LateWarpPresentStart => "PCLMarker::eLateWarpPresentStart",
            PCLMarker.LateWarpPresentEnd => "PCLMarker::eLateWarpPresentEnd",
            PCLMarker.CameraConstructed => "PCLMarker::eCameraConstructed",
            PCLMarker.LateWarpRenderSubmitStart => "PCLMarker::eLateWarpRenderSubmitStart",
            PCLMarker.LateWarpRenderSubmitEnd => "PCLMarker::eLateWarpRenderSubmitEnd",
            PCLMarker.VendorInternalAsyncPresentStart => "PCLMarker::eVendorInternalAsyncPresentStart",
            PCLMarker.VendorInternalAsyncPresentEnd => "PCLMarker::eVendorInternalAsyncPresentEnd",
            PCLMarker.NumPresentsInBatch => "PCLMarker::eNumPresentsInBatch",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getDLSSModeAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:196. </remarks>
    public static string GetDLSSModeAsStr(DLSSMode mode)
    {
        return mode switch
        {
            DLSSMode.Off => "DLSSMode::eOff",
            DLSSMode.DLAA => "DLSSMode::eDLAA",
            DLSSMode.MaxPerformance => "DLSSMode::eMaxPerformance",
            DLSSMode.Balanced => "DLSSMode::eBalanced",
            DLSSMode.MaxQuality => "DLSSMode::eMaxQuality",
            DLSSMode.UltraPerformance => "DLSSMode::eUltraPerformance",
            DLSSMode.UltraQuality => "DLSSMode::eUltraQuality",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getDLSSGModeAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:212. </remarks>
    public static string GetDLSSGModeAsStr(DLSSGMode mode)
    {
        return mode switch
        {
            DLSSGMode.Off => "sl::DLSSGMode::eOff",
            DLSSGMode.On => "sl::DLSSGMode::eOn",
            DLSSGMode.Auto => "sl::DLSSGMode::eAuto",
            DLSSGMode.Dynamic => "sl::DLSSGMode::eDynamic",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getBufferTypeAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:225. </remarks>
    public static string GetBufferTypeAsStr(uint buf)
    {
        return buf switch
        {
            SL.BufferTypeDepth => "kBufferTypeDepth",
            SL.BufferTypeMotionVectors => "kBufferTypeMotionVectors",
            SL.BufferTypeHUDLessColor => "kBufferTypeHUDLessColor",
            SL.BufferTypeScalingInputColor => "kBufferTypeScalingInputColor",
            SL.BufferTypeScalingOutputColor => "kBufferTypeScalingOutputColor",
            SL.BufferTypeNormals => "kBufferTypeNormals",
            SL.BufferTypeRoughness => "kBufferTypeRoughness",
            SL.BufferTypeAlbedo => "kBufferTypeAlbedo",
            SL.BufferTypeSpecularAlbedo => "kBufferTypeSpecularAlbedo",
            SL.BufferTypeIndirectAlbedo => "kBufferTypeIndirectAlbedo",
            SL.BufferTypeSpecularMotionVectors => "kBufferTypeSpecularMotionVectors",
            SL.BufferTypeDisocclusionMask => "kBufferTypeDisocclusionMask",
            SL.BufferTypeEmissive => "kBufferTypeEmissive",
            SL.BufferTypeExposure => "kBufferTypeExposure",
            SL.BufferTypeNormalRoughness => "kBufferTypeNormalRoughness",
            SL.BufferTypeDiffuseHitNoisy => "kBufferTypeDiffuseHitNoisy",
            SL.BufferTypeDiffuseHitDenoised => "kBufferTypeDiffuseHitDenoised",
            SL.BufferTypeSpecularHitNoisy => "kBufferTypeSpecularHitNoisy",
            SL.BufferTypeSpecularHitDenoised => "kBufferTypeSpecularHitDenoised",
            SL.BufferTypeShadowNoisy => "kBufferTypeShadowNoisy",
            SL.BufferTypeShadowDenoised => "kBufferTypeShadowDenoised",
            SL.BufferTypeAmbientOcclusionNoisy => "kBufferTypeAmbientOcclusionNoisy",
            SL.BufferTypeAmbientOcclusionDenoised => "kBufferTypeAmbientOcclusionDenoised",
            SL.BufferTypeUIColorAndAlpha => "kBufferTypeUIColorAndAlpha",
            SL.BufferTypeUIAlpha => "kBufferTypeUIAlpha",
            SL.BufferTypeUpliftInputColor => "kBufferTypeUpliftInputColor",
            SL.BufferTypeUpliftOutputColor => "kBufferTypeUpliftOutputColor",
            SL.BufferTypeUpliftControlMask => "kBufferTypeUpliftControlMask",
            SL.BufferTypeShadowHint => "kBufferTypeShadowHint",
            SL.BufferTypeReflectionHint => "kBufferTypeReflectionHint",
            SL.BufferTypeParticleHint => "kBufferTypeParticleHint",
            SL.BufferTypeTransparencyHint => "kBufferTypeTransparencyHint",
            SL.BufferTypeAnimatedTextureHint => "kBufferTypeAnimatedTextureHint",
            SL.BufferTypeBiasCurrentColorHint => "kBufferTypeBiasCurrentColorHint",
            SL.BufferTypeRaytracingDistance => "kBufferTypeRaytracingDistance",
            SL.BufferTypeReflectionMotionVectors => "kBufferTypeReflectionMotionVectors",
            SL.BufferTypePosition => "kBufferTypePosition",
            SL.BufferTypeInvalidDepthMotionHint => "kBufferTypeInvalidDepthMotionHint",
            SL.BufferTypeAlpha => "kBufferTypeAlpha",
            SL.BufferTypeOpaqueColor => "kBufferTypeOpaqueColor",
            SL.BufferTypeReactiveMaskHint => "kBufferTypeReactiveMaskHint",
            SL.BufferTypeTransparencyAndCompositionMaskHint => "kBufferTypeTransparencyAndCompositionMaskHint",
            SL.BufferTypeReflectedAlbedo => "kBufferTypeReflectedAlbedo",
            SL.BufferTypeColorBeforeParticles => "kBufferTypeColorBeforeParticles",
            SL.BufferTypeColorBeforeTransparency => "kBufferTypeColorBeforeTransparency",
            SL.BufferTypeColorBeforeFog => "kBufferTypeColorBeforeFog",
            SL.BufferTypeSpecularHitDistance => "kBufferTypeSpecularHitDistance",
            SL.BufferTypeSpecularRayDirectionHitDistance => "kBufferTypeSpecularRayDirectionHitDistance",
            SL.BufferTypeSpecularRayDirection => "kBufferTypeSpecularRayDirection",
            SL.BufferTypeDiffuseHitDistance => "kBufferTypeDiffuseHitDistance",
            SL.BufferTypeDiffuseRayDirectionHitDistance => "kBufferTypeDiffuseRayDirectionHitDistance",
            SL.BufferTypeDiffuseRayDirection => "kBufferTypeDiffuseRayDirection",
            SL.BufferTypeHiResDepth => "kBufferTypeHiResDepth",
            SL.BufferTypeLinearDepth => "kBufferTypeLinearDepth",
            SL.BufferTypeColorAfterParticles => "kBufferTypeColorAfterParticles",
            SL.BufferTypeColorAfterTransparency => "kBufferTypeColorAfterTransparency",
            SL.BufferTypeColorAfterFog => "kBufferTypeColorAfterFog",
            SL.BufferTypeScreenSpaceSubsurfaceScatteringGuide => "kBufferTypeScreenSpaceSubsurfaceScatteringGuide",
            SL.BufferTypeColorBeforeScreenSpaceSubsurfaceScattering => "kBufferTypeColorBeforeScreenSpaceSubsurfaceScattering",
            SL.BufferTypeColorAfterScreenSpaceSubsurfaceScattering => "kBufferTypeColorAfterScreenSpaceSubsurfaceScattering",
            SL.BufferTypeScreenSpaceRefractionGuide => "kBufferTypeScreenSpaceRefractionGuide",
            SL.BufferTypeColorBeforeScreenSpaceRefraction => "kBufferTypeColorBeforeScreenSpaceRefraction",
            SL.BufferTypeColorAfterScreenSpaceRefraction => "kBufferTypeColorAfterScreenSpaceRefraction",
            SL.BufferTypeDepthOfFieldGuide => "kBufferTypeDepthOfFieldGuide",
            SL.BufferTypeColorBeforeDepthOfField => "kBufferTypeColorBeforeDepthOfField",
            SL.BufferTypeColorAfterDepthOfField => "kBufferTypeColorAfterDepthOfField",
            SL.BufferTypeScalingOutputAlpha => "kBufferTypeScalingOutputAlpha",
            SL.BufferTypeResponsivityMask => "kBufferTypeResponsivityMask",
            SL.BufferTypeBidirectionalDistortionField => "kBufferTypeBidirectionalDistortionField",
            SL.BufferTypeTransparencyLayer => "kBufferTypeTransparencyLayer",
            SL.BufferTypeTransparencyLayerOpacity => "kBufferTypeTransparencyLayerOpacity",
            SL.BufferTypeBackbuffer => "kBufferTypeBackbuffer",
            SL.BufferTypeNoWarpMask => "kBufferTypeNoWarpMask",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getFeatureAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:306. </remarks>
    public static string GetFeatureAsStr(uint f)
    {
        return f switch
        {
            SL.FeatureDLSS => "kFeatureDLSS",
            SL.FeatureNIS => "kFeatureNIS",
            SL.FeatureReflex => "kFeatureReflex",
            SL.FeaturePCL => "kFeaturePCL",
            SL.FeatureDLSSG => "kFeatureDLSS_G",
            SL.FeatureNvPerf => "kFeatureNvPerf",
            SL.FeatureImGUI => "kFeatureImGUI",
            SL.FeatureCommon => "kFeatureCommon",
            SL.FeatureDLSSRR => "kFeatureDLSS_RR",
            SL.FeatureDeepDVC => "kFeatureDeepDVC",
            SL.FeatureDirectSR => "kFeatureDirectSR",
            SL.FeatureLatewarp => "kFeatureLatewarp",
            SL.FeatureDLSSNR => "kFeatureDLSS_NR",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getFeatureFilenameAsStrNoSL
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:331. </remarks>
    public static string GetFeatureFilenameAsStrNoSL(uint f)
    {
        return f switch
        {
            SL.FeatureDLSS => "dlss",
            SL.FeatureNIS => "nis",
            SL.FeatureReflex => "reflex",
            SL.FeaturePCL => "pcl",
            SL.FeatureDLSSG => "dlss_g",
            SL.FeatureNvPerf => "nvperf",
            SL.FeatureDeepDVC => "deepdvc",
            SL.FeatureImGUI => "imgui",
            SL.FeatureCommon => "common",
            SL.FeatureDLSSRR => "dlss_d",
            SL.FeatureDirectSR => "directsr",
            SL.FeatureLatewarp => "latewarp",
            SL.FeatureDLSSNR => "dlss_nr",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getLogLevelAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:353. </remarks>
    public static string GetLogLevelAsStr(LogLevel v)
    {
        return v switch
        {
            LogLevel.Off => "LogLevel::eOff",
            LogLevel.Default => "LogLevel::eDefault",
            LogLevel.Verbose => "LogLevel::eVerbose",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getResourceTypeAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:365. </remarks>
    public static string GetResourceTypeAsStr(ResourceType v)
    {
        return v switch
        {
            ResourceType.Tex2d => "ResourceType::eTex2d",
            ResourceType.Buffer => "ResourceType::eBuffer",
            ResourceType.CommandQueue => "ResourceType::eCommandQueue",
            ResourceType.CommandBuffer => "ResourceType::eCommandBuffer",
            ResourceType.CommandPool => "ResourceType::eCommandPool",
            ResourceType.Fence => "ResourceType::eFence",
            ResourceType.Swapchain => "ResourceType::eSwapchain",
            ResourceType.HostFence => "ResourceType::eHostFence",
            _ => "Unknown"
        };
    }

    /// <summary>
    /// sl::getResourceLifecycleAsStr
    /// </summary>
    /// <remarks>Source: include/sl_helpers.h:383. </remarks>
    public static string GetResourceLifecycleAsStr(ResourceLifecycle v)
    {
        return v switch
        {
            ResourceLifecycle.OnlyValidNow => "ResourceLifecycle::eOnlyValidNow",
            ResourceLifecycle.ValidUntilPresent => "ResourceLifecycle::eValidUntilPresent",
            ResourceLifecycle.ValidUntilEvaluate => "ResourceLifecycle::eValidUntilEvaluate",
            _ => "Unknown"
        };
    }
}
