// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

namespace Streamline.NET;

public static unsafe partial class SL
{
    public static unsafe partial class DLSSG
    {
        /// <summary>
        /// Returns whether any bit in the mask is present, preserving the native Boolean operator&amp; semantics.
        /// </summary>
        public static bool HasAnyFlags(DLSSGFlags value, DLSSGFlags mask) => (value & mask) != 0;

        /// <summary>
        /// Returns whether any bit in the mask is present, preserving the native Boolean operator&amp; semantics.
        /// </summary>
        public static bool HasAnyFlags(DLSSGStatus value, DLSSGStatus mask) => (value & mask) != 0;
    }
}
