// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.
// Source: NVIDIA-RTX/Streamline v2.14.1 (2122257e0fce486f91b385aa63b9a09b0a34b363).

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// sl::DLSSGOptions
/// </summary>
/// <remarks>Source: include/sl_dlss_g.h:72. </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 120)]
public unsafe partial struct DLSSGOptions : ISLStructure
{
    /// <summary>
    /// sl::BaseStructure::next
    /// </summary>
    /// <remarks>Source: include/sl_struct.h:112. </remarks>
    public BaseStructure* Next;

    /// <summary>
    /// sl::BaseStructure::structType
    /// </summary>
    /// <remarks>Source: include/sl_struct.h:113. </remarks>
    public StructType StructType;

    /// <summary>
    /// sl::BaseStructure::structVersion
    /// </summary>
    /// <remarks>Source: include/sl_struct.h:114. </remarks>
    public nuint StructVersion;

    /// <summary>Native structure type identifier.</summary>
    public static StructType TypeId => new(0xfac5f1cb, 0x2dfd, 0x4f36, [0xa1, 0xe6, 0x3a, 0x9e, 0x86, 0x52, 0x56, 0xc5]);

    /// <summary>
    /// Specifies which mode should be used.
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:74. </remarks>
    public DLSSGMode Mode;

    /// <summary>
    /// Number of frames to generate inbetween fully rendered frames. Cannot exceed DLSSGState::numFramesToGenerateMax.
    /// For 2x frame multiplier, numFramesToGenerate is 1.
    /// For 3x frame multiplier, numFramesToGenerate is 2.
    /// For 4x frame multiplier, numFramesToGenerate is 3.
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:79. </remarks>
    public uint NumFramesToGenerate;

    /// <summary>
    /// Optional - Flags used to enable or disable certain functionality
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:81. </remarks>
    public DLSSGFlags Flags;

    /// <summary>
    /// Optional - Dynamic resolution optimal width (used only if eDynamicResolutionEnabled is set)
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:83. </remarks>
    public uint DynamicResWidth;

    /// <summary>
    /// Optional - Dynamic resolution optimal height (used only if eDynamicResolutionEnabled is set)
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:85. </remarks>
    public uint DynamicResHeight;

    /// <summary>
    /// Optional - Expected number of buffers in the swap-chain
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:87. </remarks>
    public uint NumBackBuffers;

    /// <summary>
    /// Optional - Expected width of the input render targets (depth, motion-vector buffers etc)
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:89. </remarks>
    public uint MvecDepthWidth;

    /// <summary>
    /// Optional - Expected height of the input render targets (depth, motion-vector buffers etc)
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:91. </remarks>
    public uint MvecDepthHeight;

    /// <summary>
    /// Optional - Expected width of the back buffers in the swap-chain
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:93. </remarks>
    public uint ColorWidth;

    /// <summary>
    /// Optional - Expected height of the back buffers in the swap-chain
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:95. </remarks>
    public uint ColorHeight;

    /// <summary>
    /// Optional - Indicates native format used for the swap-chain back buffers
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:97. </remarks>
    public uint ColorBufferFormat;

    /// <summary>
    /// Optional - Indicates native format used for eMotionVectors
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:99. </remarks>
    public uint MvecBufferFormat;

    /// <summary>
    /// Optional - Indicates native format used for eDepth
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:101. </remarks>
    public uint DepthBufferFormat;

    /// <summary>
    /// Optional - Indicates native format used for eHUDLessColor
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:103. </remarks>
    public uint HudLessBufferFormat;

    /// <summary>
    /// Optional - Indicates native format used for eUIColorAndAlpha
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:105. </remarks>
    public uint UiBufferFormat;

    /// <summary>
    /// Optional - if specified DLSSG will return any errors which occur when calling underlying API (DXGI or Vulkan)
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:107. Keep the callback and any referenced state alive for the native contract&apos;s full duration. Managed exceptions must not cross the callback boundary.</remarks>
    public delegate* unmanaged[Cdecl]<APIError*, void> OnErrorCallback;

    /// <summary>
    /// sl::DLSSGOptions::bReserved15
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:109. </remarks>
    public SLBoolean BReserved15;

    /// <summary>
    /// Optional - determines the level of client and DLSSG queue parallelism to use for performance gain - must be same for all viewports.
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:112. </remarks>
    public DLSSGQueueParallelismMode QueueParallelismMode;

    /// <summary>
    /// Optional - if true, DLSSG will allocate a codepath that supports interpolating &apos;HUDless&apos; and &apos;UI Color &amp; Alpha&apos; separately than the Color Backbuffer.
    /// this property can be overridden by Nvidia App. See the programming guide for more details.
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:116. </remarks>
    public SLBoolean EnableUserInterfaceRecomposition;

    /// <summary>
    /// Optional - Target frame rate for dynamic frame generation when enabled.
    /// If set to 0.0f (default), auto-detects the display refresh rate.
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:120. </remarks>
    public float DynamicTargetFrameRate;

    /// <summary>Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.</summary>
    public DLSSGOptions()
    {
        this = default;
        StructType = TypeId;
        StructVersion = SL.StructVersion5;
        NumFramesToGenerate = 1;
        BReserved15 = (SLBoolean)2;
    }

}

/// <summary>
/// sl::DLSSGState
/// </summary>
/// <remarks>Source: include/sl_dlss_g.h:149. </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 88)]
public unsafe partial struct DLSSGState : ISLStructure
{
    /// <summary>
    /// sl::BaseStructure::next
    /// </summary>
    /// <remarks>Source: include/sl_struct.h:112. </remarks>
    public BaseStructure* Next;

    /// <summary>
    /// sl::BaseStructure::structType
    /// </summary>
    /// <remarks>Source: include/sl_struct.h:113. </remarks>
    public StructType StructType;

    /// <summary>
    /// sl::BaseStructure::structVersion
    /// </summary>
    /// <remarks>Source: include/sl_struct.h:114. </remarks>
    public nuint StructVersion;

    /// <summary>Native structure type identifier.</summary>
    public static StructType TypeId => new(0xcc8ac8e1, 0xa179, 0x44f5, [0x97, 0xfa, 0xe7, 0x41, 0x12, 0xf9, 0xbc, 0x61]);

    /// <summary>
    /// Specifies the amount of memory expected to be used
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:151. </remarks>
    public ulong EstimatedVRAMUsageInBytes;

    /// <summary>
    /// Specifies current status of DLSS-G
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:153. </remarks>
    public DLSSGStatus Status;

    /// <summary>
    /// Specifies minimum supported dimension
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:155. </remarks>
    public uint MinWidthOrHeight;

    /// <summary>
    /// Number of frames presented since the last &apos;slDLSSGGetState&apos; call
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:157. </remarks>
    public uint NumFramesActuallyPresented;

    /// <summary>
    /// The maximum number of interpolated frames the current system can generate per real frame.
    /// This value represents the upper bound for &apos;numFramesToGenerate&apos;.
    /// Examples:
    /// - On devices supporting up to a 2x multiplier: numFramesToGenerateMax is 1.
    /// - On devices supporting up to a 6x multiplier: numFramesToGenerateMax is 5.
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:164. </remarks>
    public uint NumFramesToGenerateMax;

    /// <summary>
    /// Reserved for future use, do not use
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:166. </remarks>
    public SLBoolean BReserved4;

    /// <summary>
    /// Hint to the application to display VSync support in the user interface
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:168. </remarks>
    public SLBoolean BIsVsyncSupportAvailable;

    /// <summary>
    /// SL client must wait on SL DLSS-G plugin-internal fence and associated value, before it can modify or destroy the tagged resources input
    /// to DLSS-G enabled for the corresponding previously presented frame on a non-presenting queue.
    /// If modified on client&apos;s presenting queue, then it&apos;s recommended but not required.
    /// However, if DLSSGQueueParallelismMode::eBlockNoClientQueues is set, then it&apos;s always required.
    /// It must call slDLSSGGetState on the present thread to retrieve the fence value for the inputs consumed by FG, on which client would
    /// wait in the frame it would modify those inputs.
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:176. </remarks>
    public void* InputsProcessingCompletionFence;

    /// <summary>
    /// sl::DLSSGState::lastPresentInputsProcessingCompletionFenceValue
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:177. </remarks>
    public ulong LastPresentInputsProcessingCompletionFenceValue;

    /// <summary>
    /// Whether or not Dynamic Multi Frame Generation (DLSSGMode::eDynamic) is
    /// supported
    /// </summary>
    /// <remarks>Source: include/sl_dlss_g.h:181. </remarks>
    public SLBoolean BIsDynamicMFGSupported;

    /// <summary>Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.</summary>
    public DLSSGState()
    {
        this = default;
        StructType = TypeId;
        StructVersion = SL.StructVersion4;
    }

}
