// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

namespace Streamline.NET;

/// <summary>
/// sl::NISHDR
/// </summary>
/// <remarks>
/// Source: include/sl_nis.h:36.
/// </remarks>
public enum NISHDR : uint
{
    /// <summary>
    /// sl::NISHDR::eNone
    /// </summary>
    /// <remarks>
    /// Source: include/sl_nis.h:38.
    /// </remarks>
    None = 0,

    /// <summary>
    /// sl::NISHDR::eLinear
    /// </summary>
    /// <remarks>
    /// Source: include/sl_nis.h:39.
    /// </remarks>
    Linear = 1,

    /// <summary>
    /// sl::NISHDR::ePQ
    /// </summary>
    /// <remarks>
    /// Source: include/sl_nis.h:40.
    /// </remarks>
    PQ = 2,

    /// <summary>
    /// sl::NISHDR::eCount
    /// </summary>
    /// <remarks>
    /// Source: include/sl_nis.h:41.
    /// </remarks>
    Count = 3,
}
