<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="ImGui.NET" Version="1.91.6.1" />
        <PackageVersion Include="Roslynator.Analyzers" Version="5.0.0" />
        <PackageVersion Include="SharpGLTF.Core" Version="1.0.7" />
        <PackageVersion Include="Slangc.NET" Version="2026.18.0" />
        <PackageVersion Include="StbImageSharp" Version="2.30.16" />
        <PackageVersion Include="Vortice.Direct3D12" Version="3.8.3" />
        <PackageVersion Include="Vortice.DXGI" Version="3.8.3" />
        <PackageVersion Include="Vortice.Vulkan" Version="3.2.3" />
    </ItemGroup>

</Project>
