// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.
// Source: NVIDIA-RTX/Streamline v2.14.1 (2122257e0fce486f91b385aa63b9a09b0a34b363).

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// sl::ReflexMode
/// </summary>
/// <remarks>Source: include/sl_reflex.h:30. </remarks>
public enum ReflexMode : int
{
    /// <summary>
    /// sl::ReflexMode::eOff
    /// </summary>
    /// <remarks>Source: include/sl_reflex.h:32. </remarks>
    Off = 0,

    /// <summary>
    /// sl::ReflexMode::eLowLatency
    /// </summary>
    /// <remarks>Source: include/sl_reflex.h:33. </remarks>
    LowLatency = 1,

    /// <summary>
    /// sl::ReflexMode::eLowLatencyWithBoost
    /// </summary>
    /// <remarks>Source: include/sl_reflex.h:34. </remarks>
    LowLatencyWithBoost = 2,

    /// <summary>
    /// sl::ReflexMode::ReflexMode_eCount
    /// </summary>
    /// <remarks>Source: include/sl_reflex.h:38. </remarks>
    ReflexModeeCount = 3,

}
