// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// sl::ReflexPredictedCameraData
/// </summary>
/// <remarks>
/// Source: include/sl_reflex.h:126.
/// </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 160)]
public unsafe partial struct ReflexPredictedCameraData : ISLStructure
{
    /// <summary>
    /// sl::BaseStructure::next
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:112.
    /// </remarks>
    public BaseStructure* Next;

    /// <summary>
    /// sl::BaseStructure::structType
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:113.
    /// </remarks>
    public StructType StructType;

    /// <summary>
    /// sl::BaseStructure::structVersion
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:114.
    /// </remarks>
    public nuint StructVersion;

    /// <summary>
    /// Native structure type identifier.
    /// </summary>
    public static StructType TypeId => new(0x8b960090, 0xa807, 0x4c85, [0xb0, 0x2f, 0x10, 0x69, 0x95, 0x0d, 0x06, 0x6c]);

    /// <summary>
    /// sl::ReflexPredictedCameraData::predictedWorldToViewMatrix
    /// </summary>
    /// <remarks>
    /// Source: include/sl_reflex.h:127.
    /// </remarks>
    public Float4x4 PredictedWorldToViewMatrix;

    /// <summary>
    /// sl::ReflexPredictedCameraData::predictedViewToClipMatrix
    /// </summary>
    /// <remarks>
    /// Source: include/sl_reflex.h:128.
    /// </remarks>
    public Float4x4 PredictedViewToClipMatrix;

    /// <summary>
    /// Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.
    /// </summary>
    public ReflexPredictedCameraData()
    {
        this = default;

        StructType = TypeId;
        StructVersion = SL.StructVersion1;
        PredictedWorldToViewMatrix = new();
        PredictedViewToClipMatrix = new();
    }
}
