// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_Buffer_Format
/// </summary>
[NativeName("NVSDK_NGX_Buffer_Format")]
public enum BufferFormat : int
{
    /// <summary>
    /// NVSDK_NGX_Buffer_Format_Unknown
    /// </summary>
    [NativeName("NVSDK_NGX_Buffer_Format_Unknown")]
    @Unknown = 0,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGB8UI
    /// </summary>
    [NativeName("NVSDK_NGX_Buffer_Format_RGB8UI")]
    @Rgb8ui = 1,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGB16F
    /// </summary>
    [NativeName("NVSDK_NGX_Buffer_Format_RGB16F")]
    @Rgb16f = 2,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGB32F
    /// </summary>
    [NativeName("NVSDK_NGX_Buffer_Format_RGB32F")]
    @Rgb32f = 3,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGBA8UI
    /// </summary>
    [NativeName("NVSDK_NGX_Buffer_Format_RGBA8UI")]
    @Rgba8ui = 4,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGBA16F
    /// </summary>
    [NativeName("NVSDK_NGX_Buffer_Format_RGBA16F")]
    @Rgba16f = 5,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGBA32F
    /// </summary>
    [NativeName("NVSDK_NGX_Buffer_Format_RGBA32F")]
    @Rgba32f = 6,

}
