// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_CUDA_Feature_Eval_Params
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 24)]
public unsafe partial struct CUDAFeatureEvalParams
{
    /// <summary>
    /// NVSDK_NGX_CUDA_Feature_Eval_Params::pInColor
    /// </summary>
    [FieldOffset(0)]
    public ulong* @PInColor;

    /// <summary>
    /// NVSDK_NGX_CUDA_Feature_Eval_Params::pInOutput
    /// </summary>
    [FieldOffset(8)]
    public ulong* @PInOutput;

    /// <summary>
    /// NVSDK_NGX_CUDA_Feature_Eval_Params::InSharpness
    /// </summary>
    [FieldOffset(16)]
    public float @InSharpness;

}
