// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_D3D12_DLSSG_Eval_Params
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 80)]
public unsafe partial struct D3D12DLSSGEvalParams
{
    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pBackbuffer
    /// </summary>
    [FieldOffset(0)]
    public nint @PBackbuffer;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pDepth
    /// </summary>
    [FieldOffset(8)]
    public nint @PDepth;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pMVecs
    /// </summary>
    [FieldOffset(16)]
    public nint @PMVecs;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pHudless
    /// </summary>
    [FieldOffset(24)]
    public nint @PHudless;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pUI
    /// </summary>
    [FieldOffset(32)]
    public nint @PUI;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pUIAlpha
    /// </summary>
    [FieldOffset(40)]
    public nint @PUIAlpha;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pBidirectionalDistortionField
    /// </summary>
    [FieldOffset(48)]
    public nint @PBidirectionalDistortionField;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pOutputInterpFrame
    /// </summary>
    [FieldOffset(56)]
    public nint @POutputInterpFrame;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pOutputRealFrame
    /// </summary>
    [FieldOffset(64)]
    public nint @POutputRealFrame;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pOutputDisableInterpolation
    /// </summary>
    [FieldOffset(72)]
    public nint @POutputDisableInterpolation;

}
