// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_D3D11_DLSSD_Eval_Params
/// </summary>
[NativeName("NVSDK_NGX_D3D11_DLSSD_Eval_Params")]
[StructLayout(LayoutKind.Explicit, Size = 904)]
public unsafe partial struct D3D11DLSSDEvalParams
{
    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInDiffuseAlbedo
    /// </summary>
    [NativeName("pInDiffuseAlbedo")]
    [FieldOffset(0)]
    public nint @PInDiffuseAlbedo;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInSpecularAlbedo
    /// </summary>
    [NativeName("pInSpecularAlbedo")]
    [FieldOffset(8)]
    public nint @PInSpecularAlbedo;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInNormals
    /// </summary>
    [NativeName("pInNormals")]
    [FieldOffset(16)]
    public nint @PInNormals;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInRoughness
    /// </summary>
    [NativeName("pInRoughness")]
    [FieldOffset(24)]
    public nint @PInRoughness;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColor
    /// </summary>
    [NativeName("pInColor")]
    [FieldOffset(32)]
    public nint @PInColor;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInAlpha
    /// </summary>
    [NativeName("pInAlpha")]
    [FieldOffset(40)]
    public nint @PInAlpha;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInOutput
    /// </summary>
    [NativeName("pInOutput")]
    [FieldOffset(48)]
    public nint @PInOutput;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInOutputAlpha
    /// </summary>
    [NativeName("pInOutputAlpha")]
    [FieldOffset(56)]
    public nint @PInOutputAlpha;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInDepth
    /// </summary>
    [NativeName("pInDepth")]
    [FieldOffset(64)]
    public nint @PInDepth;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInMotionVectors
    /// </summary>
    [NativeName("pInMotionVectors")]
    [FieldOffset(72)]
    public nint @PInMotionVectors;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InJitterOffsetX
    /// </summary>
    [NativeName("InJitterOffsetX")]
    [FieldOffset(80)]
    public float @InJitterOffsetX;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InJitterOffsetY
    /// </summary>
    [NativeName("InJitterOffsetY")]
    [FieldOffset(84)]
    public float @InJitterOffsetY;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InRenderSubrectDimensions
    /// </summary>
    [NativeName("InRenderSubrectDimensions")]
    [FieldOffset(88)]
    public global::NGX.NET.Dimensions @InRenderSubrectDimensions;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InReset
    /// </summary>
    [NativeName("InReset")]
    [FieldOffset(96)]
    public int @InReset;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InMVScaleX
    /// </summary>
    [NativeName("InMVScaleX")]
    [FieldOffset(100)]
    public float @InMVScaleX;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InMVScaleY
    /// </summary>
    [NativeName("InMVScaleY")]
    [FieldOffset(104)]
    public float @InMVScaleY;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInTransparencyMask
    /// </summary>
    [NativeName("pInTransparencyMask")]
    [FieldOffset(112)]
    public nint @PInTransparencyMask;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInExposureTexture
    /// </summary>
    [NativeName("pInExposureTexture")]
    [FieldOffset(120)]
    public nint @PInExposureTexture;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInBiasCurrentColorMask
    /// </summary>
    [NativeName("pInBiasCurrentColorMask")]
    [FieldOffset(128)]
    public nint @PInBiasCurrentColorMask;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InAlphaSubrectBase
    /// </summary>
    [NativeName("InAlphaSubrectBase")]
    [FieldOffset(136)]
    public global::NGX.NET.Coordinates @InAlphaSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InOutputAlphaSubrectBase
    /// </summary>
    [NativeName("InOutputAlphaSubrectBase")]
    [FieldOffset(144)]
    public global::NGX.NET.Coordinates @InOutputAlphaSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InDiffuseAlbedoSubrectBase
    /// </summary>
    [NativeName("InDiffuseAlbedoSubrectBase")]
    [FieldOffset(152)]
    public global::NGX.NET.Coordinates @InDiffuseAlbedoSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InSpecularAlbedoSubrectBase
    /// </summary>
    [NativeName("InSpecularAlbedoSubrectBase")]
    [FieldOffset(160)]
    public global::NGX.NET.Coordinates @InSpecularAlbedoSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InNormalsSubrectBase
    /// </summary>
    [NativeName("InNormalsSubrectBase")]
    [FieldOffset(168)]
    public global::NGX.NET.Coordinates @InNormalsSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InRoughnessSubrectBase
    /// </summary>
    [NativeName("InRoughnessSubrectBase")]
    [FieldOffset(176)]
    public global::NGX.NET.Coordinates @InRoughnessSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorSubrectBase
    /// </summary>
    [NativeName("InColorSubrectBase")]
    [FieldOffset(184)]
    public global::NGX.NET.Coordinates @InColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InDepthSubrectBase
    /// </summary>
    [NativeName("InDepthSubrectBase")]
    [FieldOffset(192)]
    public global::NGX.NET.Coordinates @InDepthSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InMVSubrectBase
    /// </summary>
    [NativeName("InMVSubrectBase")]
    [FieldOffset(200)]
    public global::NGX.NET.Coordinates @InMVSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InTranslucencySubrectBase
    /// </summary>
    [NativeName("InTranslucencySubrectBase")]
    [FieldOffset(208)]
    public global::NGX.NET.Coordinates @InTranslucencySubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InBiasCurrentColorSubrectBase
    /// </summary>
    [NativeName("InBiasCurrentColorSubrectBase")]
    [FieldOffset(216)]
    public global::NGX.NET.Coordinates @InBiasCurrentColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InOutputSubrectBase
    /// </summary>
    [NativeName("InOutputSubrectBase")]
    [FieldOffset(224)]
    public global::NGX.NET.Coordinates @InOutputSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInReflectedAlbedo
    /// </summary>
    [NativeName("pInReflectedAlbedo")]
    [FieldOffset(232)]
    public nint @PInReflectedAlbedo;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorBeforeParticles
    /// </summary>
    [NativeName("pInColorBeforeParticles")]
    [FieldOffset(240)]
    public nint @PInColorBeforeParticles;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorAfterParticles
    /// </summary>
    [NativeName("pInColorAfterParticles")]
    [FieldOffset(248)]
    public nint @PInColorAfterParticles;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorBeforeTransparency
    /// </summary>
    [NativeName("pInColorBeforeTransparency")]
    [FieldOffset(256)]
    public nint @PInColorBeforeTransparency;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorAfterTransparency
    /// </summary>
    [NativeName("pInColorAfterTransparency")]
    [FieldOffset(264)]
    public nint @PInColorAfterTransparency;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorBeforeFog
    /// </summary>
    [NativeName("pInColorBeforeFog")]
    [FieldOffset(272)]
    public nint @PInColorBeforeFog;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorAfterFog
    /// </summary>
    [NativeName("pInColorAfterFog")]
    [FieldOffset(280)]
    public nint @PInColorAfterFog;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInScreenSpaceSubsurfaceScatteringGuide
    /// </summary>
    [NativeName("pInScreenSpaceSubsurfaceScatteringGuide")]
    [FieldOffset(288)]
    public nint @PInScreenSpaceSubsurfaceScatteringGuide;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorBeforeScreenSpaceSubsurfaceScattering
    /// </summary>
    [NativeName("pInColorBeforeScreenSpaceSubsurfaceScattering")]
    [FieldOffset(296)]
    public nint @PInColorBeforeScreenSpaceSubsurfaceScattering;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorAfterScreenSpaceSubsurfaceScattering
    /// </summary>
    [NativeName("pInColorAfterScreenSpaceSubsurfaceScattering")]
    [FieldOffset(304)]
    public nint @PInColorAfterScreenSpaceSubsurfaceScattering;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInScreenSpaceRefractionGuide
    /// </summary>
    [NativeName("pInScreenSpaceRefractionGuide")]
    [FieldOffset(312)]
    public nint @PInScreenSpaceRefractionGuide;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorBeforeScreenSpaceRefraction
    /// </summary>
    [NativeName("pInColorBeforeScreenSpaceRefraction")]
    [FieldOffset(320)]
    public nint @PInColorBeforeScreenSpaceRefraction;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorAfterScreenSpaceRefraction
    /// </summary>
    [NativeName("pInColorAfterScreenSpaceRefraction")]
    [FieldOffset(328)]
    public nint @PInColorAfterScreenSpaceRefraction;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInDepthOfFieldGuide
    /// </summary>
    [NativeName("pInDepthOfFieldGuide")]
    [FieldOffset(336)]
    public nint @PInDepthOfFieldGuide;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorBeforeDepthOfField
    /// </summary>
    [NativeName("pInColorBeforeDepthOfField")]
    [FieldOffset(344)]
    public nint @PInColorBeforeDepthOfField;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInColorAfterDepthOfField
    /// </summary>
    [NativeName("pInColorAfterDepthOfField")]
    [FieldOffset(352)]
    public nint @PInColorAfterDepthOfField;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInDiffuseHitDistance
    /// </summary>
    [NativeName("pInDiffuseHitDistance")]
    [FieldOffset(360)]
    public nint @PInDiffuseHitDistance;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInSpecularHitDistance
    /// </summary>
    [NativeName("pInSpecularHitDistance")]
    [FieldOffset(368)]
    public nint @PInSpecularHitDistance;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInDiffuseRayDirection
    /// </summary>
    [NativeName("pInDiffuseRayDirection")]
    [FieldOffset(376)]
    public nint @PInDiffuseRayDirection;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInSpecularRayDirection
    /// </summary>
    [NativeName("pInSpecularRayDirection")]
    [FieldOffset(384)]
    public nint @PInSpecularRayDirection;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInDiffuseRayDirectionHitDistance
    /// </summary>
    [NativeName("pInDiffuseRayDirectionHitDistance")]
    [FieldOffset(392)]
    public nint @PInDiffuseRayDirectionHitDistance;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInSpecularRayDirectionHitDistance
    /// </summary>
    [NativeName("pInSpecularRayDirectionHitDistance")]
    [FieldOffset(400)]
    public nint @PInSpecularRayDirectionHitDistance;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InReflectedAlbedoSubrectBase
    /// </summary>
    [NativeName("InReflectedAlbedoSubrectBase")]
    [FieldOffset(408)]
    public global::NGX.NET.Coordinates @InReflectedAlbedoSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorBeforeParticlesSubrectBase
    /// </summary>
    [NativeName("InColorBeforeParticlesSubrectBase")]
    [FieldOffset(416)]
    public global::NGX.NET.Coordinates @InColorBeforeParticlesSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorAfterParticlesSubrectBase
    /// </summary>
    [NativeName("InColorAfterParticlesSubrectBase")]
    [FieldOffset(424)]
    public global::NGX.NET.Coordinates @InColorAfterParticlesSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorBeforeTransparencySubrectBase
    /// </summary>
    [NativeName("InColorBeforeTransparencySubrectBase")]
    [FieldOffset(432)]
    public global::NGX.NET.Coordinates @InColorBeforeTransparencySubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorAfterTransparencySubrectBase
    /// </summary>
    [NativeName("InColorAfterTransparencySubrectBase")]
    [FieldOffset(440)]
    public global::NGX.NET.Coordinates @InColorAfterTransparencySubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorBeforeFogSubrectBase
    /// </summary>
    [NativeName("InColorBeforeFogSubrectBase")]
    [FieldOffset(448)]
    public global::NGX.NET.Coordinates @InColorBeforeFogSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorAfterFogSubrectBase
    /// </summary>
    [NativeName("InColorAfterFogSubrectBase")]
    [FieldOffset(456)]
    public global::NGX.NET.Coordinates @InColorAfterFogSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InScreenSpaceSubsurfaceScatteringGuideSubrectBase
    /// </summary>
    [NativeName("InScreenSpaceSubsurfaceScatteringGuideSubrectBase")]
    [FieldOffset(464)]
    public global::NGX.NET.Coordinates @InScreenSpaceSubsurfaceScatteringGuideSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InScreenSpaceRefractionGuideSubrectBase
    /// </summary>
    [NativeName("InScreenSpaceRefractionGuideSubrectBase")]
    [FieldOffset(472)]
    public global::NGX.NET.Coordinates @InScreenSpaceRefractionGuideSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InDepthOfFieldGuideSubrectBase
    /// </summary>
    [NativeName("InDepthOfFieldGuideSubrectBase")]
    [FieldOffset(480)]
    public global::NGX.NET.Coordinates @InDepthOfFieldGuideSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InDiffuseHitDistanceSubrectBase
    /// </summary>
    [NativeName("InDiffuseHitDistanceSubrectBase")]
    [FieldOffset(488)]
    public global::NGX.NET.Coordinates @InDiffuseHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InSpecularHitDistanceSubrectBase
    /// </summary>
    [NativeName("InSpecularHitDistanceSubrectBase")]
    [FieldOffset(496)]
    public global::NGX.NET.Coordinates @InSpecularHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InDiffuseRayDirectionSubrectBase
    /// </summary>
    [NativeName("InDiffuseRayDirectionSubrectBase")]
    [FieldOffset(504)]
    public global::NGX.NET.Coordinates @InDiffuseRayDirectionSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InSpecularRayDirectionSubrectBase
    /// </summary>
    [NativeName("InSpecularRayDirectionSubrectBase")]
    [FieldOffset(512)]
    public global::NGX.NET.Coordinates @InSpecularRayDirectionSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InDiffuseRayDirectionHitDistanceSubrectBase
    /// </summary>
    [NativeName("InDiffuseRayDirectionHitDistanceSubrectBase")]
    [FieldOffset(520)]
    public global::NGX.NET.Coordinates @InDiffuseRayDirectionHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InSpecularRayDirectionHitDistanceSubrectBase
    /// </summary>
    [NativeName("InSpecularRayDirectionHitDistanceSubrectBase")]
    [FieldOffset(528)]
    public global::NGX.NET.Coordinates @InSpecularRayDirectionHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorBeforeScreenSpaceSubsurfaceScatteringSubrectBase
    /// </summary>
    [NativeName("InColorBeforeScreenSpaceSubsurfaceScatteringSubrectBase")]
    [FieldOffset(536)]
    public global::NGX.NET.Coordinates @InColorBeforeScreenSpaceSubsurfaceScatteringSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorAfterScreenSpaceSubsurfaceScatteringSubrectBase
    /// </summary>
    [NativeName("InColorAfterScreenSpaceSubsurfaceScatteringSubrectBase")]
    [FieldOffset(544)]
    public global::NGX.NET.Coordinates @InColorAfterScreenSpaceSubsurfaceScatteringSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorBeforeScreenSpaceRefractionSubrectBase
    /// </summary>
    [NativeName("InColorBeforeScreenSpaceRefractionSubrectBase")]
    [FieldOffset(552)]
    public global::NGX.NET.Coordinates @InColorBeforeScreenSpaceRefractionSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorAfterScreenSpaceRefractionSubrectBase
    /// </summary>
    [NativeName("InColorAfterScreenSpaceRefractionSubrectBase")]
    [FieldOffset(560)]
    public global::NGX.NET.Coordinates @InColorAfterScreenSpaceRefractionSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorBeforeDepthOfFieldSubrectBase
    /// </summary>
    [NativeName("InColorBeforeDepthOfFieldSubrectBase")]
    [FieldOffset(568)]
    public global::NGX.NET.Coordinates @InColorBeforeDepthOfFieldSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InColorAfterDepthOfFieldSubtectBase
    /// </summary>
    [NativeName("InColorAfterDepthOfFieldSubtectBase")]
    [FieldOffset(576)]
    public global::NGX.NET.Coordinates @InColorAfterDepthOfFieldSubtectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInWorldToViewMatrix
    /// </summary>
    [NativeName("pInWorldToViewMatrix")]
    [FieldOffset(584)]
    public float* @PInWorldToViewMatrix;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInViewToClipMatrix
    /// </summary>
    [NativeName("pInViewToClipMatrix")]
    [FieldOffset(592)]
    public float* @PInViewToClipMatrix;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InPreExposure
    /// </summary>
    [NativeName("InPreExposure")]
    [FieldOffset(600)]
    public float @InPreExposure;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InExposureScale
    /// </summary>
    [NativeName("InExposureScale")]
    [FieldOffset(604)]
    public float @InExposureScale;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InIndicatorInvertXAxis
    /// </summary>
    [NativeName("InIndicatorInvertXAxis")]
    [FieldOffset(608)]
    public int @InIndicatorInvertXAxis;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InIndicatorInvertYAxis
    /// </summary>
    [NativeName("InIndicatorInvertYAxis")]
    [FieldOffset(612)]
    public int @InIndicatorInvertYAxis;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::GBufferSurface
    /// </summary>
    [NativeName("GBufferSurface")]
    [FieldOffset(616)]
    public global::NGX.NET.D3D11GBuffer @GBufferSurface;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InToneMapperType
    /// </summary>
    [NativeName("InToneMapperType")]
    [FieldOffset(752)]
    public global::NGX.NET.ToneMapperType @InToneMapperType;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInMotionVectors3D
    /// </summary>
    [NativeName("pInMotionVectors3D")]
    [FieldOffset(760)]
    public nint @PInMotionVectors3D;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInIsParticleMask
    /// </summary>
    [NativeName("pInIsParticleMask")]
    [FieldOffset(768)]
    public nint @PInIsParticleMask;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInAnimatedTextureMask
    /// </summary>
    [NativeName("pInAnimatedTextureMask")]
    [FieldOffset(776)]
    public nint @PInAnimatedTextureMask;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInDepthHighRes
    /// </summary>
    [NativeName("pInDepthHighRes")]
    [FieldOffset(784)]
    public nint @PInDepthHighRes;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInPositionViewSpace
    /// </summary>
    [NativeName("pInPositionViewSpace")]
    [FieldOffset(792)]
    public nint @PInPositionViewSpace;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InFrameTimeDeltaInMsec
    /// </summary>
    [NativeName("InFrameTimeDeltaInMsec")]
    [FieldOffset(800)]
    public float @InFrameTimeDeltaInMsec;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInRayTracingHitDistance
    /// </summary>
    [NativeName("pInRayTracingHitDistance")]
    [FieldOffset(808)]
    public nint @PInRayTracingHitDistance;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInMotionVectorsReflections
    /// </summary>
    [NativeName("pInMotionVectorsReflections")]
    [FieldOffset(816)]
    public nint @PInMotionVectorsReflections;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInTransparencyLayer
    /// </summary>
    [NativeName("pInTransparencyLayer")]
    [FieldOffset(824)]
    public nint @PInTransparencyLayer;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InTransparencyLayerSubrectBase
    /// </summary>
    [NativeName("InTransparencyLayerSubrectBase")]
    [FieldOffset(832)]
    public global::NGX.NET.Coordinates @InTransparencyLayerSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInTransparencyLayerOpacity
    /// </summary>
    [NativeName("pInTransparencyLayerOpacity")]
    [FieldOffset(840)]
    public nint @PInTransparencyLayerOpacity;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InTransparencyLayerOpacitySubrectBase
    /// </summary>
    [NativeName("InTransparencyLayerOpacitySubrectBase")]
    [FieldOffset(848)]
    public global::NGX.NET.Coordinates @InTransparencyLayerOpacitySubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInTransparencyLayerMvecs
    /// </summary>
    [NativeName("pInTransparencyLayerMvecs")]
    [FieldOffset(856)]
    public nint @PInTransparencyLayerMvecs;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InTransparencyLayerMvecsSubrectBase
    /// </summary>
    [NativeName("InTransparencyLayerMvecsSubrectBase")]
    [FieldOffset(864)]
    public global::NGX.NET.Coordinates @InTransparencyLayerMvecsSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInDisocclusionMask
    /// </summary>
    [NativeName("pInDisocclusionMask")]
    [FieldOffset(872)]
    public nint @PInDisocclusionMask;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InDisocclusionMaskSubrectBase
    /// </summary>
    [NativeName("InDisocclusionMaskSubrectBase")]
    [FieldOffset(880)]
    public global::NGX.NET.Coordinates @InDisocclusionMaskSubrectBase;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::pInResponsivityMask
    /// </summary>
    [NativeName("pInResponsivityMask")]
    [FieldOffset(888)]
    public nint @PInResponsivityMask;

    /// <summary>
    /// NVSDK_NGX_D3D11_DLSSD_Eval_Params::InResponsivityMaskSubrectBase
    /// </summary>
    [NativeName("InResponsivityMaskSubrectBase")]
    [FieldOffset(896)]
    public global::NGX.NET.Coordinates @InResponsivityMaskSubrectBase;

}
