// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_DLSS_Create_Params
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 28)]
public unsafe partial struct DLSSCreateParams
{
    /// <summary>
    /// NVSDK_NGX_DLSS_Create_Params::Feature
    /// </summary>
    [FieldOffset(0)]
    public global::NGX.NET.FeatureCreateParams @Feature;

    /// <summary>
    /// NVSDK_NGX_DLSS_Create_Params::InFeatureCreateFlags
    /// </summary>
    [FieldOffset(20)]
    public int @InFeatureCreateFlags;

    /// <summary>
    /// NVSDK_NGX_DLSS_Create_Params::InEnableOutputSubrects
    /// </summary>
    [FieldOffset(24)]
    public global::NGX.NET.Bool8 @InEnableOutputSubrects;

}
