// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_DLSSD_Create_Params
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 40)]
public unsafe partial struct DLSSDCreateParams
{
    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InDenoiseMode
    /// </summary>
    [FieldOffset(0)]
    public global::NGX.NET.DLSSDenoiseMode @InDenoiseMode;

    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InRoughnessMode
    /// </summary>
    [FieldOffset(4)]
    public global::NGX.NET.DLSSRoughnessMode @InRoughnessMode;

    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InUseHWDepth
    /// </summary>
    [FieldOffset(8)]
    public global::NGX.NET.DLSSDepthType @InUseHWDepth;

    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InWidth
    /// </summary>
    [FieldOffset(12)]
    public uint @InWidth;

    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InHeight
    /// </summary>
    [FieldOffset(16)]
    public uint @InHeight;

    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InTargetWidth
    /// </summary>
    [FieldOffset(20)]
    public uint @InTargetWidth;

    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InTargetHeight
    /// </summary>
    [FieldOffset(24)]
    public uint @InTargetHeight;

    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InPerfQualityValue
    /// </summary>
    [FieldOffset(28)]
    public global::NGX.NET.PerfQualityValue @InPerfQualityValue;

    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InFeatureCreateFlags
    /// </summary>
    [FieldOffset(32)]
    public int @InFeatureCreateFlags;

    /// <summary>
    /// NVSDK_NGX_DLSSD_Create_Params::InEnableOutputSubrects
    /// </summary>
    [FieldOffset(36)]
    public global::NGX.NET.Bool8 @InEnableOutputSubrects;

}
