// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_DLSSG_Create_Params
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 24)]
public unsafe partial struct DLSSGCreateParams
{
    /// <summary>
    /// NVSDK_NGX_DLSSG_Create_Params::Width
    /// </summary>
    [FieldOffset(0)]
    public uint @Width;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Create_Params::Height
    /// </summary>
    [FieldOffset(4)]
    public uint @Height;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Create_Params::NativeBackbufferFormat
    /// </summary>
    [FieldOffset(8)]
    public uint @NativeBackbufferFormat;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Create_Params::RenderWidth
    /// </summary>
    [FieldOffset(12)]
    public uint @RenderWidth;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Create_Params::RenderHeight
    /// </summary>
    [FieldOffset(16)]
    public uint @RenderHeight;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Create_Params::DynamicResolutionScaling
    /// </summary>
    [FieldOffset(20)]
    public global::NGX.NET.Bool8 @DynamicResolutionScaling;

}
