// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_DLSS_Hint_Render_Preset
/// </summary>
[NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset")]
public enum DLSSHintRenderPreset : int
{
    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_Default
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_Default")]
    @Default = 0,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_E
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_E")]
    @E = 5,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_F
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_F")]
    @F = 6,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_G
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_G")]
    @G = 7,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_H_Reserved
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_H_Reserved")]
    @HReserved = 8,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_I_Reserved
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_I_Reserved")]
    @IReserved = 9,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_J
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_J")]
    @J = 10,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_K
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_K")]
    @K = 11,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_L
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_L")]
    @L = 12,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_M
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_M")]
    @M = 13,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_N
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_N")]
    @N = 14,

    /// <summary>
    /// NVSDK_NGX_DLSS_Hint_Render_Preset_O
    /// </summary>
    [NativeName("NVSDK_NGX_DLSS_Hint_Render_Preset_O")]
    @O = 15,

}
