// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_DLSSG_EvalFlags
/// </summary>
public enum DLSSGEvalFlags : int
{
    /// <summary>
    /// NVSDK_NGX_DLSSG_EvalFlags_UpdateOnlyInsideExtents
    /// </summary>
    @UpdateOnlyInsideExtents = 1,

}
