// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

namespace NGX.NET;

/// <summary>
/// Managed outputs of RequiredExtensions.
/// </summary>
public readonly struct Extensions(string[] instanceExtensions, string[] deviceExtensions)
{
    /// <summary>
    /// The InstanceExtensions output.
    /// </summary>
    public string[] InstanceExtensions { get; } = instanceExtensions;

    /// <summary>
    /// The DeviceExtensions output.
    /// </summary>
    public string[] DeviceExtensions { get; } = deviceExtensions;
}
