// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_FeatureCommonInfo
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 40)]
public unsafe partial struct FeatureCommonInfo
{
    /// <summary>
    /// NVSDK_NGX_FeatureCommonInfo::PathListInfo
    /// </summary>
    [FieldOffset(0)]
    public global::NGX.NET.PathListInfo @PathListInfo;

    /// <summary>
    /// NVSDK_NGX_FeatureCommonInfo::InternalData
    /// </summary>
    [FieldOffset(16)]
    public global::NGX.NET.FeatureCommonInfoInternal* @InternalData;

    /// <summary>
    /// NVSDK_NGX_FeatureCommonInfo::LoggingInfo
    /// </summary>
    [FieldOffset(24)]
    public global::NGX.NET.LoggingInfo @LoggingInfo;

}
