// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_GraphicsAPI
/// </summary>
public enum GraphicsAPI : int
{
    /// <summary>
    /// NVSDK_NGX_GRAPHICS_API_CUDA
    /// </summary>
    @GraphicsAPICUDA = 0,

    /// <summary>
    /// NVSDK_NGX_GRAPHICS_API_D3D11
    /// </summary>
    @GraphicsAPID3D11 = 1,

    /// <summary>
    /// NVSDK_NGX_GRAPHICS_API_D3D12
    /// </summary>
    @GraphicsAPID3D12 = 2,

    /// <summary>
    /// NVSDK_NGX_GRAPHICS_API_VULKAN
    /// </summary>
    @GraphicsAPIVulkan = 3,

    /// <summary>
    /// NVSDK_NGX_GRAPHICS_API_COUNT
    /// </summary>
    @GraphicsAPICount = 4,

}
