// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_Logging_Level
/// </summary>
[NativeName("NVSDK_NGX_Logging_Level")]
public enum LoggingLevel : int
{
    /// <summary>
    /// NVSDK_NGX_LOGGING_LEVEL_OFF
    /// </summary>
    [NativeName("NVSDK_NGX_LOGGING_LEVEL_OFF")]
    @Off = 0,

    /// <summary>
    /// NVSDK_NGX_LOGGING_LEVEL_ON
    /// </summary>
    [NativeName("NVSDK_NGX_LOGGING_LEVEL_ON")]
    @On = 1,

    /// <summary>
    /// NVSDK_NGX_LOGGING_LEVEL_VERBOSE
    /// </summary>
    [NativeName("NVSDK_NGX_LOGGING_LEVEL_VERBOSE")]
    @Verbose = 2,

    /// <summary>
    /// NVSDK_NGX_LOGGING_LEVEL_NUM
    /// </summary>
    [NativeName("NVSDK_NGX_LOGGING_LEVEL_NUM")]
    @Num = 3,

}
