// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_Buffer_Format
/// </summary>
public enum NGXBufferFormat : int
{
    /// <summary>
    /// NVSDK_NGX_Buffer_Format_Unknown
    /// </summary>
    Unknown = 0,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGB8UI
    /// </summary>
    Rgb8Ui = 1,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGB16F
    /// </summary>
    Rgb16F = 2,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGB32F
    /// </summary>
    Rgb32F = 3,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGBA8UI
    /// </summary>
    Rgba8Ui = 4,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGBA16F
    /// </summary>
    Rgba16F = 5,

    /// <summary>
    /// NVSDK_NGX_Buffer_Format_RGBA32F
    /// </summary>
    Rgba32F = 6,
}
