// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_CUDA_DLSSD_Eval_Params
/// </summary>
[NGXNativeName("NVSDK_NGX_CUDA_DLSSD_Eval_Params")]
[StructLayout(LayoutKind.Explicit, Size = 632)]
public unsafe partial struct NGXCUDADLSSDEvalParams
{
    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDiffuseAlbedo
    /// </summary>
    [NGXNativeName("pInDiffuseAlbedo")]
    [FieldOffset(0)]
    public void* PInDiffuseAlbedo;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInSpecularAlbedo
    /// </summary>
    [NGXNativeName("pInSpecularAlbedo")]
    [FieldOffset(8)]
    public void* PInSpecularAlbedo;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInNormals
    /// </summary>
    [NGXNativeName("pInNormals")]
    [FieldOffset(16)]
    public void* PInNormals;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInRoughness
    /// </summary>
    [NGXNativeName("pInRoughness")]
    [FieldOffset(24)]
    public void* PInRoughness;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInColor
    /// </summary>
    [NGXNativeName("pInColor")]
    [FieldOffset(32)]
    public void* PInColor;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInOutput
    /// </summary>
    [NGXNativeName("pInOutput")]
    [FieldOffset(40)]
    public void* PInOutput;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDepth
    /// </summary>
    [NGXNativeName("pInDepth")]
    [FieldOffset(48)]
    public void* PInDepth;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInMotionVectors
    /// </summary>
    [NGXNativeName("pInMotionVectors")]
    [FieldOffset(56)]
    public void* PInMotionVectors;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InJitterOffsetX
    /// </summary>
    [NGXNativeName("InJitterOffsetX")]
    [FieldOffset(64)]
    public float InJitterOffsetX;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InJitterOffsetY
    /// </summary>
    [NGXNativeName("InJitterOffsetY")]
    [FieldOffset(68)]
    public float InJitterOffsetY;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InRenderSubrectDimensions
    /// </summary>
    [NGXNativeName("InRenderSubrectDimensions")]
    [FieldOffset(72)]
    public NGXDimensions InRenderSubrectDimensions;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InReset
    /// </summary>
    [NGXNativeName("InReset")]
    [FieldOffset(80)]
    public int InReset;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InMVScaleX
    /// </summary>
    [NGXNativeName("InMVScaleX")]
    [FieldOffset(84)]
    public float InMVScaleX;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InMVScaleY
    /// </summary>
    [NGXNativeName("InMVScaleY")]
    [FieldOffset(88)]
    public float InMVScaleY;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInTransparencyMask
    /// </summary>
    [NGXNativeName("pInTransparencyMask")]
    [FieldOffset(96)]
    public void* PInTransparencyMask;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInExposureTexture
    /// </summary>
    [NGXNativeName("pInExposureTexture")]
    [FieldOffset(104)]
    public void* PInExposureTexture;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInBiasCurrentColorMask
    /// </summary>
    [NGXNativeName("pInBiasCurrentColorMask")]
    [FieldOffset(112)]
    public void* PInBiasCurrentColorMask;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDiffuseAlbedoSubrectBase
    /// </summary>
    [NGXNativeName("InDiffuseAlbedoSubrectBase")]
    [FieldOffset(120)]
    public NGXCoordinates InDiffuseAlbedoSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InSpecularAlbedoSubrectBase
    /// </summary>
    [NGXNativeName("InSpecularAlbedoSubrectBase")]
    [FieldOffset(128)]
    public NGXCoordinates InSpecularAlbedoSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InNormalsSubrectBase
    /// </summary>
    [NGXNativeName("InNormalsSubrectBase")]
    [FieldOffset(136)]
    public NGXCoordinates InNormalsSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InRoughnessSubrectBase
    /// </summary>
    [NGXNativeName("InRoughnessSubrectBase")]
    [FieldOffset(144)]
    public NGXCoordinates InRoughnessSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InColorSubrectBase
    /// </summary>
    [NGXNativeName("InColorSubrectBase")]
    [FieldOffset(152)]
    public NGXCoordinates InColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDepthSubrectBase
    /// </summary>
    [NGXNativeName("InDepthSubrectBase")]
    [FieldOffset(160)]
    public NGXCoordinates InDepthSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InMVSubrectBase
    /// </summary>
    [NGXNativeName("InMVSubrectBase")]
    [FieldOffset(168)]
    public NGXCoordinates InMVSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InTranslucencySubrectBase
    /// </summary>
    [NGXNativeName("InTranslucencySubrectBase")]
    [FieldOffset(176)]
    public NGXCoordinates InTranslucencySubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InBiasCurrentColorSubrectBase
    /// </summary>
    [NGXNativeName("InBiasCurrentColorSubrectBase")]
    [FieldOffset(184)]
    public NGXCoordinates InBiasCurrentColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InOutputSubrectBase
    /// </summary>
    [NGXNativeName("InOutputSubrectBase")]
    [FieldOffset(192)]
    public NGXCoordinates InOutputSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInReflectedAlbedo
    /// </summary>
    [NGXNativeName("pInReflectedAlbedo")]
    [FieldOffset(200)]
    public void* PInReflectedAlbedo;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInColorBeforeParticles
    /// </summary>
    [NGXNativeName("pInColorBeforeParticles")]
    [FieldOffset(208)]
    public void* PInColorBeforeParticles;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInColorBeforeTransparency
    /// </summary>
    [NGXNativeName("pInColorBeforeTransparency")]
    [FieldOffset(216)]
    public void* PInColorBeforeTransparency;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInColorBeforeFog
    /// </summary>
    [NGXNativeName("pInColorBeforeFog")]
    [FieldOffset(224)]
    public void* PInColorBeforeFog;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDiffuseHitDistance
    /// </summary>
    [NGXNativeName("pInDiffuseHitDistance")]
    [FieldOffset(232)]
    public void* PInDiffuseHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInSpecularHitDistance
    /// </summary>
    [NGXNativeName("pInSpecularHitDistance")]
    [FieldOffset(240)]
    public void* PInSpecularHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDiffuseRayDirection
    /// </summary>
    [NGXNativeName("pInDiffuseRayDirection")]
    [FieldOffset(248)]
    public void* PInDiffuseRayDirection;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInSpecularRayDirection
    /// </summary>
    [NGXNativeName("pInSpecularRayDirection")]
    [FieldOffset(256)]
    public void* PInSpecularRayDirection;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDiffuseRayDirectionHitDistance
    /// </summary>
    [NGXNativeName("pInDiffuseRayDirectionHitDistance")]
    [FieldOffset(264)]
    public void* PInDiffuseRayDirectionHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInSpecularRayDirectionHitDistance
    /// </summary>
    [NGXNativeName("pInSpecularRayDirectionHitDistance")]
    [FieldOffset(272)]
    public void* PInSpecularRayDirectionHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InReflectedAlbedoSubrectBase
    /// </summary>
    [NGXNativeName("InReflectedAlbedoSubrectBase")]
    [FieldOffset(280)]
    public NGXCoordinates InReflectedAlbedoSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InColorBeforeParticlesSubrectBase
    /// </summary>
    [NGXNativeName("InColorBeforeParticlesSubrectBase")]
    [FieldOffset(288)]
    public NGXCoordinates InColorBeforeParticlesSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InColorBeforeTransparencySubrectBase
    /// </summary>
    [NGXNativeName("InColorBeforeTransparencySubrectBase")]
    [FieldOffset(296)]
    public NGXCoordinates InColorBeforeTransparencySubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InColorBeforeFogSubrectBase
    /// </summary>
    [NGXNativeName("InColorBeforeFogSubrectBase")]
    [FieldOffset(304)]
    public NGXCoordinates InColorBeforeFogSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDiffuseHitDistanceSubrectBase
    /// </summary>
    [NGXNativeName("InDiffuseHitDistanceSubrectBase")]
    [FieldOffset(312)]
    public NGXCoordinates InDiffuseHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InSpecularHitDistanceSubrectBase
    /// </summary>
    [NGXNativeName("InSpecularHitDistanceSubrectBase")]
    [FieldOffset(320)]
    public NGXCoordinates InSpecularHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDiffuseRayDirectionSubrectBase
    /// </summary>
    [NGXNativeName("InDiffuseRayDirectionSubrectBase")]
    [FieldOffset(328)]
    public NGXCoordinates InDiffuseRayDirectionSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InSpecularRayDirectionSubrectBase
    /// </summary>
    [NGXNativeName("InSpecularRayDirectionSubrectBase")]
    [FieldOffset(336)]
    public NGXCoordinates InSpecularRayDirectionSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDiffuseRayDirectionHitDistanceSubrectBase
    /// </summary>
    [NGXNativeName("InDiffuseRayDirectionHitDistanceSubrectBase")]
    [FieldOffset(344)]
    public NGXCoordinates InDiffuseRayDirectionHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InSpecularRayDirectionHitDistanceSubrectBase
    /// </summary>
    [NGXNativeName("InSpecularRayDirectionHitDistanceSubrectBase")]
    [FieldOffset(352)]
    public NGXCoordinates InSpecularRayDirectionHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInWorldToViewMatrix
    /// </summary>
    [NGXNativeName("pInWorldToViewMatrix")]
    [FieldOffset(360)]
    public float* PInWorldToViewMatrix;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInViewToClipMatrix
    /// </summary>
    [NGXNativeName("pInViewToClipMatrix")]
    [FieldOffset(368)]
    public float* PInViewToClipMatrix;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InPreExposure
    /// </summary>
    [NGXNativeName("InPreExposure")]
    [FieldOffset(376)]
    public float InPreExposure;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InExposureScale
    /// </summary>
    [NGXNativeName("InExposureScale")]
    [FieldOffset(380)]
    public float InExposureScale;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InIndicatorInvertXAxis
    /// </summary>
    [NGXNativeName("InIndicatorInvertXAxis")]
    [FieldOffset(384)]
    public int InIndicatorInvertXAxis;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InIndicatorInvertYAxis
    /// </summary>
    [NGXNativeName("InIndicatorInvertYAxis")]
    [FieldOffset(388)]
    public int InIndicatorInvertYAxis;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::GBufferSurface
    /// </summary>
    [NGXNativeName("GBufferSurface")]
    [FieldOffset(392)]
    public NGXCUDAGBuffer GBufferSurface;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InToneMapperType
    /// </summary>
    [NGXNativeName("InToneMapperType")]
    [FieldOffset(528)]
    public NGXToneMapperType InToneMapperType;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInMotionVectors3D
    /// </summary>
    [NGXNativeName("pInMotionVectors3D")]
    [FieldOffset(536)]
    public void* PInMotionVectors3D;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInIsParticleMask
    /// </summary>
    [NGXNativeName("pInIsParticleMask")]
    [FieldOffset(544)]
    public void* PInIsParticleMask;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInAnimatedTextureMask
    /// </summary>
    [NGXNativeName("pInAnimatedTextureMask")]
    [FieldOffset(552)]
    public void* PInAnimatedTextureMask;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDepthHighRes
    /// </summary>
    [NGXNativeName("pInDepthHighRes")]
    [FieldOffset(560)]
    public void* PInDepthHighRes;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInPositionViewSpace
    /// </summary>
    [NGXNativeName("pInPositionViewSpace")]
    [FieldOffset(568)]
    public void* PInPositionViewSpace;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InFrameTimeDeltaInMsec
    /// </summary>
    [NGXNativeName("InFrameTimeDeltaInMsec")]
    [FieldOffset(576)]
    public float InFrameTimeDeltaInMsec;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInRayTracingHitDistance
    /// </summary>
    [NGXNativeName("pInRayTracingHitDistance")]
    [FieldOffset(584)]
    public void* PInRayTracingHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInMotionVectorsReflections
    /// </summary>
    [NGXNativeName("pInMotionVectorsReflections")]
    [FieldOffset(592)]
    public void* PInMotionVectorsReflections;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInTransparencyLayer
    /// </summary>
    [NGXNativeName("pInTransparencyLayer")]
    [FieldOffset(600)]
    public void* PInTransparencyLayer;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InTransparencyLayerSubrectBase
    /// </summary>
    [NGXNativeName("InTransparencyLayerSubrectBase")]
    [FieldOffset(608)]
    public NGXCoordinates InTransparencyLayerSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInTransparencyLayerOpacity
    /// </summary>
    [NGXNativeName("pInTransparencyLayerOpacity")]
    [FieldOffset(616)]
    public void* PInTransparencyLayerOpacity;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InTransparencyLayerOpacitySubrectBase
    /// </summary>
    [NGXNativeName("InTransparencyLayerOpacitySubrectBase")]
    [FieldOffset(624)]
    public NGXCoordinates InTransparencyLayerOpacitySubrectBase;

}
