// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_Dimensions
/// </summary>
public struct NGXDimensions
{
    /// <summary>
    /// NVSDK_NGX_Dimensions::Width
    /// </summary>
    public uint Width;

    /// <summary>
    /// NVSDK_NGX_Dimensions::Height
    /// </summary>
    public uint Height;

    internal unsafe NGXDimensions(in NGXDimensionsNative native)
    {
        this = default;
        Width = native.Width;
        Height = native.Height;
    }
}
