// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_D3D12_GBuffer
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 136)]
public unsafe partial struct NGXD3D12GBuffer
{
    /// <summary>
    /// NVSDK_NGX_D3D12_GBuffer::pInAttrib
    /// </summary>
    [FieldOffset(0)]
    public NGXPInAttribBuffer PInAttrib;

    /// <summary>
    /// Inline storage for 17 native elements.
    /// </summary>
    [InlineArray(17)]
    public struct NGXPInAttribBuffer
    {
        private nint element;
    }
}
