// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_D3D12_DLSSG_Eval_Params
/// </summary>
public partial struct NGXD3D12DLSSGEvalParams
{
    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pBackbuffer
    /// </summary>
    public nint PBackbuffer;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pDepth
    /// </summary>
    public nint PDepth;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pMVecs
    /// </summary>
    public nint PMVecs;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pHudless
    /// </summary>
    public nint PHudless;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pUI
    /// </summary>
    public nint PUI;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pUIAlpha
    /// </summary>
    public nint PUIAlpha;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pBidirectionalDistortionField
    /// </summary>
    public nint PBidirectionalDistortionField;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pOutputInterpFrame
    /// </summary>
    public nint POutputInterpFrame;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pOutputRealFrame
    /// </summary>
    public nint POutputRealFrame;

    /// <summary>
    /// NVSDK_NGX_D3D12_DLSSG_Eval_Params::pOutputDisableInterpolation
    /// </summary>
    public nint POutputDisableInterpolation;

    internal unsafe NGXD3D12DLSSGEvalParams(in NGXD3D12DLSSGEvalParamsNative native)
    {
        this = default;
        PBackbuffer = (nint)native.PBackbuffer;
        PDepth = (nint)native.PDepth;
        PMVecs = (nint)native.PMVecs;
        PHudless = (nint)native.PHudless;
        PUI = (nint)native.PUI;
        PUIAlpha = (nint)native.PUIAlpha;
        PBidirectionalDistortionField = (nint)native.PBidirectionalDistortionField;
        POutputInterpFrame = (nint)native.POutputInterpFrame;
        POutputRealFrame = (nint)native.POutputRealFrame;
        POutputDisableInterpolation = (nint)native.POutputDisableInterpolation;
    }
}
