// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_D3D12_GBuffer
/// </summary>
public struct NGXD3D12GBuffer
{
    /// <summary>
    /// NVSDK_NGX_D3D12_GBuffer::pInAttrib
    /// </summary>
    public nint[]? PInAttrib;

    internal unsafe NGXD3D12GBuffer(in NGXD3D12GBufferNative native)
    {
        this = default;
        PInAttrib = new nint[17];
        for (int i = 0; i < PInAttrib.Length; i++)
        {
            PInAttrib[i] = (nint)native.PInAttrib[i];
        }
    }
}
