// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_D3D12_Feature_Eval_Params
/// </summary>
public partial struct NGXD3D12FeatureEvalParams
{
    /// <summary>
    /// NVSDK_NGX_D3D12_Feature_Eval_Params::pInColor
    /// </summary>
    public nint PInColor;

    /// <summary>
    /// NVSDK_NGX_D3D12_Feature_Eval_Params::pInOutput
    /// </summary>
    public nint PInOutput;

    /// <summary>
    /// NVSDK_NGX_D3D12_Feature_Eval_Params::InSharpness
    /// </summary>
    public float InSharpness;

    internal unsafe NGXD3D12FeatureEvalParams(in NGXD3D12FeatureEvalParamsNative native)
    {
        this = default;
        PInColor = (nint)native.PInColor;
        PInOutput = (nint)native.PInOutput;
        InSharpness = native.InSharpness;
    }
}
