// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_FeatureDiscoveryInfo
/// </summary>
[NGXNativeName("NVSDK_NGX_FeatureDiscoveryInfo")]
[StructLayout(LayoutKind.Explicit, Size = 56)]
public unsafe partial struct NGXFeatureDiscoveryInfo
{
    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::SDKVersion
    /// </summary>
    [NGXNativeName("SDKVersion")]
    [FieldOffset(0)]
    public NGXVersion SDKVersion;

    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::FeatureID
    /// </summary>
    [NGXNativeName("FeatureID")]
    [FieldOffset(4)]
    public NGXFeature FeatureID;

    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::Identifier
    /// </summary>
    [NGXNativeName("Identifier")]
    [FieldOffset(8)]
    public NGXApplicationIdentifier Identifier;

    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::ApplicationDataPath
    /// </summary>
    [NGXNativeName("ApplicationDataPath")]
    [FieldOffset(40)]
    public void* ApplicationDataPath;

    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::FeatureInfo
    /// </summary>
    [NGXNativeName("FeatureInfo")]
    [FieldOffset(48)]
    public NGXFeatureCommonInfo* FeatureInfo;

}
