// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_FeatureDiscoveryInfo
/// </summary>
public struct NGXFeatureDiscoveryInfo
{
    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::SDKVersion
    /// </summary>
    public NGXVersion SDKVersion;

    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::FeatureID
    /// </summary>
    public NGXFeature FeatureID;

    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::Identifier
    /// </summary>
    public NGXApplicationIdentifier Identifier;

    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::ApplicationDataPath
    /// </summary>
    public string? ApplicationDataPath;

    /// <summary>
    /// NVSDK_NGX_FeatureDiscoveryInfo::FeatureInfo
    /// </summary>
    public NGXFeatureCommonInfo? FeatureInfo;

    internal unsafe NGXFeatureDiscoveryInfo(in NGXFeatureDiscoveryInfoNative native)
    {
        this = default;
        SDKVersion = native.SDKVersion;
        FeatureID = native.FeatureID;
        Identifier = new(in native.Identifier);
        ApplicationDataPath = NGXMarshal.PtrToString(native.ApplicationDataPath, NGXEncoding.NativeWide);
        FeatureInfo = (NGXFeatureCommonInfoNative*)native.FeatureInfo == null ? null : new NGXFeatureCommonInfo(in *(NGXFeatureCommonInfoNative*)native.FeatureInfo);
    }
}
