// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_FeatureCommonInfo
/// </summary>
[NGXNativeName("NVSDK_NGX_FeatureCommonInfo")]
[StructLayout(LayoutKind.Explicit, Size = 40)]
public unsafe partial struct NGXFeatureCommonInfo
{
    /// <summary>
    /// NVSDK_NGX_FeatureCommonInfo::PathListInfo
    /// </summary>
    [NGXNativeName("PathListInfo")]
    [FieldOffset(0)]
    public global::NGX.NET.NGXPathListInfo PathListInfo;

    /// <summary>
    /// NVSDK_NGX_FeatureCommonInfo::InternalData
    /// </summary>
    [NGXNativeName("InternalData")]
    [FieldOffset(16)]
    public global::NGX.NET.NGXFeatureCommonInfoInternal* InternalData;

    /// <summary>
    /// NVSDK_NGX_FeatureCommonInfo::LoggingInfo
    /// </summary>
    [NGXNativeName("LoggingInfo")]
    [FieldOffset(24)]
    public global::NGX.NET.NGXLoggingInfo LoggingInfo;

}
