// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_FeatureRequirement
/// </summary>
public struct NGXFeatureRequirement
{
    /// <summary>
    /// NVSDK_NGX_FeatureRequirement::FeatureSupported
    /// </summary>
    public NGXFeatureSupportResult FeatureSupported;

    /// <summary>
    /// NVSDK_NGX_FeatureRequirement::MinHWArchitecture
    /// </summary>
    public uint MinHWArchitecture;

    /// <summary>
    /// NVSDK_NGX_FeatureRequirement::MinOSVersion
    /// </summary>
    public string? MinOSVersion;

    internal unsafe NGXFeatureRequirement(in NGXFeatureRequirementNative native)
    {
        this = default;
        FeatureSupported = native.FeatureSupported;
        MinHWArchitecture = native.MinHWArchitecture;

        fixed (sbyte* buffer = native.MinOSVersion)
        {
            MinOSVersion = NGXMarshal.ReadUtf8(new ReadOnlySpan<byte>(buffer, 255));
        }
    }
}
