// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_Feature_Support_Result
/// </summary>
[Flags]
public enum NGXFeatureSupportResult : int
{
    /// <summary>
    /// NVSDK_NGX_FeatureSupportResult_Supported
    /// </summary>
    Supported = 0,

    /// <summary>
    /// NVSDK_NGX_FeatureSupportResult_CheckNotPresent
    /// </summary>
    CheckNotPresent = 1 << 0,

    /// <summary>
    /// NVSDK_NGX_FeatureSupportResult_DriverVersionUnsupported
    /// </summary>
    DriverVersionUnsupported = 1 << 1,

    /// <summary>
    /// NVSDK_NGX_FeatureSupportResult_AdapterUnsupported
    /// </summary>
    AdapterUnsupported = 1 << 2,

    /// <summary>
    /// NVSDK_NGX_FeatureSupportResult_OSVersionBelowMinimumSupported
    /// </summary>
    OsVersionBelowMinimumSupported = 1 << 3,

    /// <summary>
    /// NVSDK_NGX_FeatureSupportResult_NotImplemented
    /// </summary>
    NotImplemented = 1 << 4,

    /// <summary>
    /// No flags are set.
    /// </summary>
    None = 0
}
