// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_GBufferType
/// </summary>
public enum NGXGBufferType : int
{
    /// <summary>
    /// NVSDK_NGX_GBUFFER_ALBEDO
    /// </summary>
    GBUFFERALBEDO = 0,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_ROUGHNESS
    /// </summary>
    GBUFFERROUGHNESS = 1,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_METALLIC
    /// </summary>
    GBUFFERMETALLIC = 2,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SPECULAR
    /// </summary>
    GBUFFERSPECULAR = 3,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SUBSURFACE
    /// </summary>
    GBUFFERSUBSURFACE = 4,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_NORMALS
    /// </summary>
    GBUFFERNORMALS = 5,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SHADINGMODELID
    /// </summary>
    GBUFFERSHADINGMODELID = 6,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_MATERIALID
    /// </summary>
    GBUFFERMATERIALID = 7,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SPECULAR_ALBEDO
    /// </summary>
    GBUFFERSPECULARALBEDO = 8,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_INDIRECT_ALBEDO
    /// </summary>
    GBUFFERINDIRECTALBEDO = 9,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SPECULAR_MVEC
    /// </summary>
    GBUFFERSPECULARMVEC = 10,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_DISOCCL_MASK
    /// </summary>
    GBUFFERDISOCCLMASK = 11,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_EMISSIVE
    /// </summary>
    GBUFFEREMISSIVE = 12,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_RESPONSIVITY_MASK
    /// </summary>
    GBUFFERRESPONSIVITYMASK = 13,

    /// <summary>
    /// NVSDK_NGX_GBUFFERTYPE_NUM
    /// </summary>
    NUM = 17,
}
