// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_GBufferType
/// </summary>
[NGXNativeName("NVSDK_NGX_GBufferType")]
public enum NGXGBufferType : int
{
    /// <summary>
    /// NVSDK_NGX_GBUFFER_ALBEDO
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_ALBEDO")]
    GbufferAlbedo = 0,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_ROUGHNESS
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_ROUGHNESS")]
    GbufferRoughness = 1,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_METALLIC
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_METALLIC")]
    GbufferMetallic = 2,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SPECULAR
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_SPECULAR")]
    GbufferSpecular = 3,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SUBSURFACE
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_SUBSURFACE")]
    GbufferSubsurface = 4,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_NORMALS
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_NORMALS")]
    GbufferNormals = 5,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SHADINGMODELID
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_SHADINGMODELID")]
    GbufferShadingmodelid = 6,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_MATERIALID
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_MATERIALID")]
    GbufferMaterialid = 7,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SPECULAR_ALBEDO
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_SPECULAR_ALBEDO")]
    GbufferSpecularAlbedo = 8,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_INDIRECT_ALBEDO
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_INDIRECT_ALBEDO")]
    GbufferIndirectAlbedo = 9,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_SPECULAR_MVEC
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_SPECULAR_MVEC")]
    GbufferSpecularMvec = 10,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_DISOCCL_MASK
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_DISOCCL_MASK")]
    GbufferDisocclMask = 11,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_EMISSIVE
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_EMISSIVE")]
    GbufferEmissive = 12,

    /// <summary>
    /// NVSDK_NGX_GBUFFER_RESPONSIVITY_MASK
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFER_RESPONSIVITY_MASK")]
    GbufferResponsivityMask = 13,

    /// <summary>
    /// NVSDK_NGX_GBUFFERTYPE_NUM
    /// </summary>
    [NGXNativeName("NVSDK_NGX_GBUFFERTYPE_NUM")]
    Num = 17,

}
