// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_ImageViewInfo_VK
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 48)]
public unsafe partial struct NGXImageViewInfoVK
{
    /// <summary>
    /// NVSDK_NGX_ImageViewInfo_VK::ImageView
    /// </summary>
    [FieldOffset(0)]
    public nint ImageView;

    /// <summary>
    /// NVSDK_NGX_ImageViewInfo_VK::Image
    /// </summary>
    [FieldOffset(8)]
    public nint Image;

    /// <summary>
    /// NVSDK_NGX_ImageViewInfo_VK::SubresourceRange
    /// </summary>
    [FieldOffset(16)]
    public NGXVkImageSubresourceRange SubresourceRange;

    /// <summary>
    /// NVSDK_NGX_ImageViewInfo_VK::Format
    /// </summary>
    [FieldOffset(36)]
    public NGXVkFormat Format;

    /// <summary>
    /// NVSDK_NGX_ImageViewInfo_VK::Width
    /// </summary>
    [FieldOffset(40)]
    public uint Width;

    /// <summary>
    /// NVSDK_NGX_ImageViewInfo_VK::Height
    /// </summary>
    [FieldOffset(44)]
    public uint Height;
}
