// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_Logging_Level
/// </summary>
[NGXNativeName("NVSDK_NGX_Logging_Level")]
public enum NGXLoggingLevel : int
{
    /// <summary>
    /// NVSDK_NGX_LOGGING_LEVEL_OFF
    /// </summary>
    [NGXNativeName("NVSDK_NGX_LOGGING_LEVEL_OFF")]
    Off = 0,

    /// <summary>
    /// NVSDK_NGX_LOGGING_LEVEL_ON
    /// </summary>
    [NGXNativeName("NVSDK_NGX_LOGGING_LEVEL_ON")]
    On = 1,

    /// <summary>
    /// NVSDK_NGX_LOGGING_LEVEL_VERBOSE
    /// </summary>
    [NGXNativeName("NVSDK_NGX_LOGGING_LEVEL_VERBOSE")]
    Verbose = 2,

    /// <summary>
    /// NVSDK_NGX_LOGGING_LEVEL_NUM
    /// </summary>
    [NGXNativeName("NVSDK_NGX_LOGGING_LEVEL_NUM")]
    Num = 3,

}
