// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_LoggingInfo
/// </summary>
public partial struct NGXLoggingInfo
{
    /// <summary>
    /// NVSDK_NGX_LoggingInfo::LoggingCallback
    /// </summary>
    public NGXAppLogCallback? LoggingCallback;

    /// <summary>
    /// NVSDK_NGX_LoggingInfo::MinimumLoggingLevel
    /// </summary>
    public NGXLoggingLevel MinimumLoggingLevel;

    /// <summary>
    /// NVSDK_NGX_LoggingInfo::DisableOtherLoggingSinks
    /// </summary>
    public bool DisableOtherLoggingSinks;

    internal unsafe NGXLoggingInfo(in NGXLoggingInfoNative native)
    {
        this = default;
        LoggingCallback = native.LoggingCallback == 0 ? null : Marshal.GetDelegateForFunctionPointer<NGXAppLogCallback>(native.LoggingCallback);
        MinimumLoggingLevel = native.MinimumLoggingLevel;
        DisableOtherLoggingSinks = native.DisableOtherLoggingSinks;
    }
}
