// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_PrecisionInfo
/// </summary>
public partial struct NGXPrecisionInfo
{
    /// <summary>
    /// NVSDK_NGX_PrecisionInfo::IsLowPrecision
    /// </summary>
    public uint IsLowPrecision;

    /// <summary>
    /// NVSDK_NGX_PrecisionInfo::Bias
    /// </summary>
    public float Bias;

    /// <summary>
    /// NVSDK_NGX_PrecisionInfo::Scale
    /// </summary>
    public float Scale;

    internal unsafe NGXPrecisionInfo(in NGXPrecisionInfoNative native)
    {
        this = default;
        IsLowPrecision = native.IsLowPrecision;
        Bias = native.Bias;
        Scale = native.Scale;
    }
}
