// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// Anonymous_94_5
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 48)]
public unsafe partial struct NGXResourceVKUnion
{
    /// <summary>
    /// Anonymous_94_5::ImageViewInfo
    /// </summary>
    [FieldOffset(0)]
    public NGXImageViewInfoVK ImageViewInfo;

    /// <summary>
    /// Anonymous_94_5::BufferInfo
    /// </summary>
    [FieldOffset(0)]
    public NGXBufferInfoVK BufferInfo;
}
