// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_Resource_VK_Type
/// </summary>
public enum NGXResourceVKType : int
{
    /// <summary>
    /// NVSDK_NGX_RESOURCE_VK_TYPE_VK_IMAGEVIEW
    /// </summary>
    VkImageView = 0,

    /// <summary>
    /// NVSDK_NGX_RESOURCE_VK_TYPE_VK_BUFFER
    /// </summary>
    VkBuffer = 1,
}
