// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_VK_Feature_Eval_Params
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 24)]
public unsafe partial struct NGXVKFeatureEvalParams
{
    /// <summary>
    /// NVSDK_NGX_VK_Feature_Eval_Params::pInColor
    /// </summary>
    [FieldOffset(0)]
    public NGXResourceVK* PInColor;

    /// <summary>
    /// NVSDK_NGX_VK_Feature_Eval_Params::pInOutput
    /// </summary>
    [FieldOffset(8)]
    public NGXResourceVK* PInOutput;

    /// <summary>
    /// NVSDK_NGX_VK_Feature_Eval_Params::InSharpness
    /// </summary>
    [FieldOffset(16)]
    public float InSharpness;
}
