// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_VK_DLSS_Eval_Params
/// </summary>
public struct NGXVKDLSSEvalParams
{
    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::Feature
    /// </summary>
    public NGXVKFeatureEvalParams Feature;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInDepth
    /// </summary>
    public NGXResourceVK? PInDepth;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInMotionVectors
    /// </summary>
    public NGXResourceVK? PInMotionVectors;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InJitterOffsetX
    /// </summary>
    public float InJitterOffsetX;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InJitterOffsetY
    /// </summary>
    public float InJitterOffsetY;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InRenderSubrectDimensions
    /// </summary>
    public NGXDimensions InRenderSubrectDimensions;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InReset
    /// </summary>
    public int InReset;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InMVScaleX
    /// </summary>
    public float InMVScaleX;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InMVScaleY
    /// </summary>
    public float InMVScaleY;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInTransparencyMask
    /// </summary>
    public NGXResourceVK? PInTransparencyMask;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInExposureTexture
    /// </summary>
    public NGXResourceVK? PInExposureTexture;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInBiasCurrentColorMask
    /// </summary>
    public NGXResourceVK? PInBiasCurrentColorMask;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InColorSubrectBase
    /// </summary>
    public NGXCoordinates InColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InDepthSubrectBase
    /// </summary>
    public NGXCoordinates InDepthSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InMVSubrectBase
    /// </summary>
    public NGXCoordinates InMVSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InTranslucencySubrectBase
    /// </summary>
    public NGXCoordinates InTranslucencySubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InBiasCurrentColorSubrectBase
    /// </summary>
    public NGXCoordinates InBiasCurrentColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InOutputSubrectBase
    /// </summary>
    public NGXCoordinates InOutputSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InPreExposure
    /// </summary>
    public float InPreExposure;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InExposureScale
    /// </summary>
    public float InExposureScale;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InIndicatorInvertXAxis
    /// </summary>
    public int InIndicatorInvertXAxis;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InIndicatorInvertYAxis
    /// </summary>
    public int InIndicatorInvertYAxis;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::GBufferSurface
    /// </summary>
    public NGXVKGBuffer GBufferSurface;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InToneMapperType
    /// </summary>
    public NGXToneMapperType InToneMapperType;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInMotionVectors3D
    /// </summary>
    public NGXResourceVK? PInMotionVectors3D;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInIsParticleMask
    /// </summary>
    public NGXResourceVK? PInIsParticleMask;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInAnimatedTextureMask
    /// </summary>
    public NGXResourceVK? PInAnimatedTextureMask;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInDepthHighRes
    /// </summary>
    public NGXResourceVK? PInDepthHighRes;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInPositionViewSpace
    /// </summary>
    public NGXResourceVK? PInPositionViewSpace;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InFrameTimeDeltaInMsec
    /// </summary>
    public float InFrameTimeDeltaInMsec;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInRayTracingHitDistance
    /// </summary>
    public NGXResourceVK? PInRayTracingHitDistance;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInMotionVectorsReflections
    /// </summary>
    public NGXResourceVK? PInMotionVectorsReflections;

    internal unsafe NGXVKDLSSEvalParams(in NGXVKDLSSEvalParamsNative native)
    {
        this = default;
        Feature = new(in native.Feature);
        PInDepth = (NGXResourceVKNative*)native.PInDepth == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInDepth);
        PInMotionVectors = (NGXResourceVKNative*)native.PInMotionVectors == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInMotionVectors);
        InJitterOffsetX = native.InJitterOffsetX;
        InJitterOffsetY = native.InJitterOffsetY;
        InRenderSubrectDimensions = new(in native.InRenderSubrectDimensions);
        InReset = native.InReset;
        InMVScaleX = native.InMVScaleX;
        InMVScaleY = native.InMVScaleY;
        PInTransparencyMask = (NGXResourceVKNative*)native.PInTransparencyMask == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInTransparencyMask);
        PInExposureTexture = (NGXResourceVKNative*)native.PInExposureTexture == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInExposureTexture);
        PInBiasCurrentColorMask = (NGXResourceVKNative*)native.PInBiasCurrentColorMask == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInBiasCurrentColorMask);
        InColorSubrectBase = new(in native.InColorSubrectBase);
        InDepthSubrectBase = new(in native.InDepthSubrectBase);
        InMVSubrectBase = new(in native.InMVSubrectBase);
        InTranslucencySubrectBase = new(in native.InTranslucencySubrectBase);
        InBiasCurrentColorSubrectBase = new(in native.InBiasCurrentColorSubrectBase);
        InOutputSubrectBase = new(in native.InOutputSubrectBase);
        InPreExposure = native.InPreExposure;
        InExposureScale = native.InExposureScale;
        InIndicatorInvertXAxis = native.InIndicatorInvertXAxis;
        InIndicatorInvertYAxis = native.InIndicatorInvertYAxis;
        GBufferSurface = new(in native.GBufferSurface);
        InToneMapperType = native.InToneMapperType;
        PInMotionVectors3D = (NGXResourceVKNative*)native.PInMotionVectors3D == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInMotionVectors3D);
        PInIsParticleMask = (NGXResourceVKNative*)native.PInIsParticleMask == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInIsParticleMask);
        PInAnimatedTextureMask = (NGXResourceVKNative*)native.PInAnimatedTextureMask == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInAnimatedTextureMask);
        PInDepthHighRes = (NGXResourceVKNative*)native.PInDepthHighRes == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInDepthHighRes);
        PInPositionViewSpace = (NGXResourceVKNative*)native.PInPositionViewSpace == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInPositionViewSpace);
        InFrameTimeDeltaInMsec = native.InFrameTimeDeltaInMsec;
        PInRayTracingHitDistance = (NGXResourceVKNative*)native.PInRayTracingHitDistance == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInRayTracingHitDistance);
        PInMotionVectorsReflections = (NGXResourceVKNative*)native.PInMotionVectorsReflections == null ? null : new NGXResourceVK(in *(NGXResourceVKNative*)native.PInMotionVectorsReflections);
    }
}
