// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// VkExtensionProperties
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 260)]
public unsafe partial struct NGXVkExtensionProperties
{
    /// <summary>
    /// VkExtensionProperties::extensionName
    /// </summary>
    [FieldOffset(0)]
    public fixed sbyte ExtensionName[256];

    /// <summary>
    /// VkExtensionProperties::specVersion
    /// </summary>
    [FieldOffset(256)]
    public uint SpecVersion;
}
