// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_PerfQuality_Value
/// </summary>
public enum PerfQualityValue : int
{
    /// <summary>
    /// NVSDK_NGX_PerfQuality_Value_MaxPerf
    /// </summary>
    @MaxPerf = 0,

    /// <summary>
    /// NVSDK_NGX_PerfQuality_Value_Balanced
    /// </summary>
    @Balanced = 1,

    /// <summary>
    /// NVSDK_NGX_PerfQuality_Value_MaxQuality
    /// </summary>
    @MaxQuality = 2,

    /// <summary>
    /// NVSDK_NGX_PerfQuality_Value_UltraPerformance
    /// </summary>
    @UltraPerformance = 3,

    /// <summary>
    /// NVSDK_NGX_PerfQuality_Value_UltraQuality
    /// </summary>
    @UltraQuality = 4,

    /// <summary>
    /// NVSDK_NGX_PerfQuality_Value_DLAA
    /// </summary>
    @DLAA = 5,

}
