// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_RTX_Value
/// </summary>
public enum RtxValue : int
{
    /// <summary>
    /// NVSDK_NGX_RTX_Value_Off
    /// </summary>
    @Off = 0,

    /// <summary>
    /// NVSDK_NGX_RTX_Value_On
    /// </summary>
    @On = 1,

}
