// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_VK_DLSS_Eval_Params
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 368)]
public unsafe partial struct VKDLSSEvalParams
{
    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::Feature
    /// </summary>
    [FieldOffset(0)]
    public global::NGX.NET.VKFeatureEvalParams @Feature;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInDepth
    /// </summary>
    [FieldOffset(24)]
    public global::NGX.NET.ResourceVK* @PInDepth;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInMotionVectors
    /// </summary>
    [FieldOffset(32)]
    public global::NGX.NET.ResourceVK* @PInMotionVectors;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InJitterOffsetX
    /// </summary>
    [FieldOffset(40)]
    public float @InJitterOffsetX;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InJitterOffsetY
    /// </summary>
    [FieldOffset(44)]
    public float @InJitterOffsetY;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InRenderSubrectDimensions
    /// </summary>
    [FieldOffset(48)]
    public global::NGX.NET.Dimensions @InRenderSubrectDimensions;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InReset
    /// </summary>
    [FieldOffset(56)]
    public int @InReset;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InMVScaleX
    /// </summary>
    [FieldOffset(60)]
    public float @InMVScaleX;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InMVScaleY
    /// </summary>
    [FieldOffset(64)]
    public float @InMVScaleY;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInTransparencyMask
    /// </summary>
    [FieldOffset(72)]
    public global::NGX.NET.ResourceVK* @PInTransparencyMask;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInExposureTexture
    /// </summary>
    [FieldOffset(80)]
    public global::NGX.NET.ResourceVK* @PInExposureTexture;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInBiasCurrentColorMask
    /// </summary>
    [FieldOffset(88)]
    public global::NGX.NET.ResourceVK* @PInBiasCurrentColorMask;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InColorSubrectBase
    /// </summary>
    [FieldOffset(96)]
    public global::NGX.NET.Coordinates @InColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InDepthSubrectBase
    /// </summary>
    [FieldOffset(104)]
    public global::NGX.NET.Coordinates @InDepthSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InMVSubrectBase
    /// </summary>
    [FieldOffset(112)]
    public global::NGX.NET.Coordinates @InMVSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InTranslucencySubrectBase
    /// </summary>
    [FieldOffset(120)]
    public global::NGX.NET.Coordinates @InTranslucencySubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InBiasCurrentColorSubrectBase
    /// </summary>
    [FieldOffset(128)]
    public global::NGX.NET.Coordinates @InBiasCurrentColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InOutputSubrectBase
    /// </summary>
    [FieldOffset(136)]
    public global::NGX.NET.Coordinates @InOutputSubrectBase;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InPreExposure
    /// </summary>
    [FieldOffset(144)]
    public float @InPreExposure;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InExposureScale
    /// </summary>
    [FieldOffset(148)]
    public float @InExposureScale;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InIndicatorInvertXAxis
    /// </summary>
    [FieldOffset(152)]
    public int @InIndicatorInvertXAxis;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InIndicatorInvertYAxis
    /// </summary>
    [FieldOffset(156)]
    public int @InIndicatorInvertYAxis;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::GBufferSurface
    /// </summary>
    [FieldOffset(160)]
    public global::NGX.NET.VKGBuffer @GBufferSurface;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InToneMapperType
    /// </summary>
    [FieldOffset(296)]
    public global::NGX.NET.ToneMapperType @InToneMapperType;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInMotionVectors3D
    /// </summary>
    [FieldOffset(304)]
    public global::NGX.NET.ResourceVK* @PInMotionVectors3D;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInIsParticleMask
    /// </summary>
    [FieldOffset(312)]
    public global::NGX.NET.ResourceVK* @PInIsParticleMask;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInAnimatedTextureMask
    /// </summary>
    [FieldOffset(320)]
    public global::NGX.NET.ResourceVK* @PInAnimatedTextureMask;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInDepthHighRes
    /// </summary>
    [FieldOffset(328)]
    public global::NGX.NET.ResourceVK* @PInDepthHighRes;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInPositionViewSpace
    /// </summary>
    [FieldOffset(336)]
    public global::NGX.NET.ResourceVK* @PInPositionViewSpace;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::InFrameTimeDeltaInMsec
    /// </summary>
    [FieldOffset(344)]
    public float @InFrameTimeDeltaInMsec;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInRayTracingHitDistance
    /// </summary>
    [FieldOffset(352)]
    public global::NGX.NET.ResourceVK* @PInRayTracingHitDistance;

    /// <summary>
    /// NVSDK_NGX_VK_DLSS_Eval_Params::pInMotionVectorsReflections
    /// </summary>
    [FieldOffset(360)]
    public global::NGX.NET.ResourceVK* @PInMotionVectorsReflections;

}
