// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// VkPhysicalDeviceVulkan13Features
/// </summary>
/// <remarks>
/// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6726.
/// </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 80)]
public unsafe partial struct VkPhysicalDeviceVulkan13Features
{
    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::sType
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6727.
    /// </remarks>
    public int SType;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::pNext
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6728.
    /// </remarks>
    public void* PNext;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::robustImageAccess
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6729.
    /// </remarks>
    public uint RobustImageAccess;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::inlineUniformBlock
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6730.
    /// </remarks>
    public uint InlineUniformBlock;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::descriptorBindingInlineUniformBlockUpdateAfterBind
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6731.
    /// </remarks>
    public uint DescriptorBindingInlineUniformBlockUpdateAfterBind;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::pipelineCreationCacheControl
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6732.
    /// </remarks>
    public uint PipelineCreationCacheControl;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::privateData
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6733.
    /// </remarks>
    public uint PrivateData;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::shaderDemoteToHelperInvocation
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6734.
    /// </remarks>
    public uint ShaderDemoteToHelperInvocation;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::shaderTerminateInvocation
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6735.
    /// </remarks>
    public uint ShaderTerminateInvocation;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::subgroupSizeControl
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6736.
    /// </remarks>
    public uint SubgroupSizeControl;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::computeFullSubgroups
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6737.
    /// </remarks>
    public uint ComputeFullSubgroups;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::synchronization2
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6738.
    /// </remarks>
    public uint Synchronization2;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::textureCompressionASTC_HDR
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6739.
    /// </remarks>
    public uint TextureCompressionASTCHDR;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::shaderZeroInitializeWorkgroupMemory
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6740.
    /// </remarks>
    public uint ShaderZeroInitializeWorkgroupMemory;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::dynamicRendering
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6741.
    /// </remarks>
    public uint DynamicRendering;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::shaderIntegerDotProduct
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6742.
    /// </remarks>
    public uint ShaderIntegerDotProduct;

    /// <summary>
    /// VkPhysicalDeviceVulkan13Features::maintenance4
    /// </summary>
    /// <remarks>
    /// Source: Vulkan-Headers/include/vulkan/vulkan_core.h:6743.
    /// </remarks>
    public uint Maintenance4;

    /// <summary>
    /// Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.
    /// </summary>
    public VkPhysicalDeviceVulkan13Features()
    {
        this = default;
    }
}
