// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// sl::DirectSROptions
/// </summary>
/// <remarks>
/// Source: include/sl_directsr.h:59.
/// </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 80)]
public unsafe partial struct DirectSROptions : ISLStructure
{
    /// <summary>
    /// sl::BaseStructure::next
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:112.
    /// </remarks>
    public BaseStructure* Next;

    /// <summary>
    /// sl::BaseStructure::structType
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:113.
    /// </remarks>
    public StructType StructType;

    /// <summary>
    /// sl::BaseStructure::structVersion
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:114.
    /// </remarks>
    public nuint StructVersion;

    /// <summary>
    /// Native structure type identifier.
    /// </summary>
    public static StructType TypeId => new(0x1ad87504, 0x774e, 0x4bf3, [0x96, 0x33, 0xa4, 0x4d, 0x1f, 0x7f, 0x9c, 0xb8]);

    /// <summary>
    /// sl::DirectSROptions::variantIndex
    /// </summary>
    /// <remarks>
    /// Source: include/sl_directsr.h:61.
    /// </remarks>
    public uint VariantIndex;

    /// <summary>
    /// sl::DirectSROptions::pCommandQueue
    /// </summary>
    /// <remarks>
    /// Source: include/sl_directsr.h:64.
    /// </remarks>
    public nint PCommandQueue;

    /// <summary>
    /// Specifies which mode should be used
    /// </summary>
    /// <remarks>
    /// Source: include/sl_directsr.h:67.
    /// </remarks>
    public DirectSROptimizationType OptType;

    /// <summary>
    /// Specifies output (final) target width
    /// </summary>
    /// <remarks>
    /// Source: include/sl_directsr.h:70.
    /// </remarks>
    public uint OutputWidth;

    /// <summary>
    /// Specifies output (final) target height
    /// </summary>
    /// <remarks>
    /// Source: include/sl_directsr.h:73.
    /// </remarks>
    public uint OutputHeight;

    /// <summary>
    /// Specifies sharpening level in range [0,1]
    /// </summary>
    /// <remarks>
    /// Source: include/sl_directsr.h:76.
    /// </remarks>
    public float Sharpness;

    /// <summary>
    /// Specifies pre-exposure value
    /// </summary>
    /// <remarks>
    /// Source: include/sl_directsr.h:79.
    /// </remarks>
    public float PreExposure;

    /// <summary>
    /// Specifies exposure scale value
    /// </summary>
    /// <remarks>
    /// Source: include/sl_directsr.h:82.
    /// </remarks>
    public float ExposureScale;

    /// <summary>
    /// Specifies if tagged color buffers are full HDR or not (DLSS in HDR pipeline or not)
    /// </summary>
    /// <remarks>
    /// Source: include/sl_directsr.h:85.
    /// </remarks>
    public SLBoolean ColorBuffersHDR;

    /// <summary>
    /// Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.
    /// </summary>
    public DirectSROptions()
    {
        this = default;

        StructType = TypeId;
        StructVersion = SL.StructVersion1;
        OutputWidth = 4294967295;
        OutputHeight = 4294967295;
        PreExposure = 1f;
        ExposureScale = 1f;
        ColorBuffersHDR = (SLBoolean)1;
    }
}
