<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
        <IsAotCompatible>true</IsAotCompatible>
        <IsTrimmable>true</IsTrimmable>
        <NoWarn>IDE0130</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Version>0.1.0</Version>
        <Authors>qian-o</Authors>
        <Copyright>Copyright (c) 2026 qian-o</Copyright>
        <Description>C# bindings for NVIDIA Streamline.</Description>
        <PackageTags>Streamline;NVIDIA;DLSS;Graphics;CSharp</PackageTags>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/qian-o/Streamline.NET.git</RepositoryUrl>
        <PackageProjectUrl>https://github.com/qian-o/Streamline.NET</PackageProjectUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
