<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
        <IsAotCompatible>true</IsAotCompatible>
        <NoWarn>IDE0130</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Version>2.14.1-alpha</Version>
        <Authors>qian-o</Authors>
        <Copyright>Copyright (c) 2026 qian-o</Copyright>
        <Description>C# bindings for NVIDIA Streamline.</Description>

        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/qian-o/Streamline.NET.git</RepositoryUrl>

        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>Streamline;NVIDIA;DLSS;Graphics;CSharp</PackageTags>
        <PackageProjectUrl>https://github.com/qian-o/Streamline.NET</PackageProjectUrl>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\THIRD-PARTY-NOTICES" Pack="true" PackagePath="\" />
        <None Include="..\README.md" Pack="true" PackagePath="\" />
        <None Update="readme.txt" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
