<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
        <IsAotCompatible>true</IsAotCompatible>
        <NoWarn>IDE0130</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Version>310.9.1-alpha</Version>
        <Authors>qian-o</Authors>
        <Copyright>Copyright (c) 2026 qian-o</Copyright>
        <Description>C# bindings for NVIDIA NGX.</Description>

        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/qian-o/Streamline.NET.git</RepositoryUrl>

        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>NGX;NVIDIA;DLSS;Graphics;CSharp</PackageTags>
        <PackageProjectUrl>https://github.com/qian-o/Streamline.NET</PackageProjectUrl>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\native\win-x64\*.dll">
            <Link>runtimes\win-x64\native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <PackagePath>runtimes/win-x64/native/</PackagePath>
            <Pack>true</Pack>
        </None>

        <None Include="..\native\win-arm64\*.dll">
            <Link>runtimes\win-arm64\native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <PackagePath>runtimes/win-arm64/native/</PackagePath>
            <Pack>true</Pack>
        </None>

        <None Include="..\native\linux-x64\*.so*">
            <Link>runtimes\linux-x64\native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <PackagePath>runtimes/linux-x64/native/</PackagePath>
            <Pack>true</Pack>
        </None>

        <None Include="..\native\linux-arm64\*.so*">
            <Link>runtimes\linux-arm64\native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <PackagePath>runtimes/linux-arm64/native/</PackagePath>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

</Project>
