<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
        <IsAotCompatible>true</IsAotCompatible>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="NGX.NET.Marshalling.Tests" />
        <None Include="..\native\**\*.dll;..\native\**\*.so*">
            <Link>runtimes\%(RecursiveDir)native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <PackagePath>runtimes/%(RecursiveDir)native/%(Filename)%(Extension)</PackagePath>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

    <Import Project="../NuGet.Packaging.props" />

</Project>
