<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
        <IsAotCompatible>true</IsAotCompatible>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NGXSdkVersion>$([System.Text.RegularExpressions.Regex]::Match($([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)../NGX.NET.Generator/ast.json')), '"release"\s*:\s*"v?([^&quot;]+)"').Groups[1].Value)</NGXSdkVersion>
        <Version>$(NGXSdkVersion)-alpha</Version>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <Authors>qian-o</Authors>
        <Copyright>Copyright (c) 2026 qian-o</Copyright>
        <Description>C# bindings for NVIDIA NGX.</Description>

        <RepositoryType>Git</RepositoryType>
        <RepositoryUrl>https://github.com/qian-o/NGX.NET.git</RepositoryUrl>

        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>NGX;NVIDIA;DLSS;Graphics;CSharp</PackageTags>
        <PackageProjectUrl>https://github.com/qian-o/NGX.NET</PackageProjectUrl>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\native\**\*.dll;..\native\**\*.so*">
            <Link>runtimes\%(RecursiveDir)native\%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
            <PackagePath>runtimes/%(RecursiveDir)native/%(Filename)%(Extension)</PackagePath>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

</Project>
