// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// sl::DeepDVCState
/// </summary>
/// <remarks>
/// Source: include/sl_deepdvc.h:51.
/// </remarks>
[StructLayout(LayoutKind.Sequential, Pack = 8, Size = 40)]
public unsafe partial struct DeepDVCState : ISLStructure
{
    /// <summary>
    /// sl::BaseStructure::next
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:112.
    /// </remarks>
    public BaseStructure* Next;

    /// <summary>
    /// sl::BaseStructure::structType
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:113.
    /// </remarks>
    public StructType StructType;

    /// <summary>
    /// sl::BaseStructure::structVersion
    /// </summary>
    /// <remarks>
    /// Source: include/sl_struct.h:114.
    /// </remarks>
    public nuint StructVersion;

    /// <summary>
    /// Native structure type identifier.
    /// </summary>
    public static StructType TypeId => new(0x934fd3d3, 0xb34c, 0x70a7, [0xa1, 0x39, 0xf1, 0x9f, 0xe0, 0x4d, 0x91, 0xd3]);

    /// <summary>
    /// Specified the amount of memory expected to be used
    /// </summary>
    /// <remarks>
    /// Source: include/sl_deepdvc.h:53.
    /// </remarks>
    public ulong EstimatedVRAMUsageInBytes;

    /// <summary>
    /// Initializes native defaults, including nested structures. Unspecified native values remain CLR-zeroed.
    /// </summary>
    public DeepDVCState()
    {
        this = default;

        StructType = TypeId;
        StructVersion = SL.StructVersion1;
    }
}
