// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.
// Source: NVIDIA-RTX/Streamline v2.14.1 (2122257e0fce486f91b385aa63b9a09b0a34b363).

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Streamline.NET;

/// <summary>
/// sl::DeepDVCMode
/// </summary>
/// <remarks>Source: include/sl_deepdvc.h:31.</remarks>
public enum DeepDVCMode : uint
{
    /// <summary>
    /// sl::DeepDVCMode::eOff
    /// </summary>
    /// <remarks>Source: include/sl_deepdvc.h:33.</remarks>
    Off = 0,

    /// <summary>
    /// sl::DeepDVCMode::eOn
    /// </summary>
    /// <remarks>Source: include/sl_deepdvc.h:34.</remarks>
    On = 1,

    /// <summary>
    /// sl::DeepDVCMode::eCount
    /// </summary>
    /// <remarks>Source: include/sl_deepdvc.h:35.</remarks>
    Count = 2,

}
