// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.
// Source: NVIDIA-RTX/Streamline v2.14.1 (2122257e0fce486f91b385aa63b9a09b0a34b363).

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Streamline.NET;

public static unsafe partial class SL
{
    /// <summary>
    /// HELPERS
    /// 
    /// </summary>
    /// <remarks>Source: include/sl_dlss.h:177.</remarks>
    public static SLResult DLSSGetOptimalSettings(DLSSOptions* options, DLSSOptimalSettings* settings)
    {
        SLResult result = FeatureFunctions.Get(FeatureDLSS, "slDLSSGetOptimalSettings"u8, out nint address);
        if (result != SLResult.Ok)
        {
            return result;
        }
        return ((delegate* unmanaged[Cdecl]<DLSSOptions*, DLSSOptimalSettings*, SLResult>)address)(options, settings);
    }

    /// <summary>Convenience overload. References are fixed only until the native call returns; nested pointers retain their original lifetime requirements.</summary>
    public static SLResult DLSSGetOptimalSettings(in DLSSOptions options, ref DLSSOptimalSettings settings)
    {
        fixed (DLSSOptions* optionsPointer = &options)
        fixed (DLSSOptimalSettings* settingsPointer = &settings)
        {
            return DLSSGetOptimalSettings(optionsPointer, settingsPointer);
        }
    }
}

public static unsafe partial class SL
{
    /// <summary>
    /// Provides DLSS state for the given viewport
    /// 
    /// Call this method to obtain optimal render target size and other DLSS related settings.
    /// 
    /// @param viewport Specified viewport we are working with
    /// @param state Reference to a structure where state is to be returned
    /// @return sl::ResultCode::eOk if successful, error code otherwise (see sl_result.h for details)
    /// 
    /// This method is NOT thread safe.
    /// </summary>
    /// <remarks>Source: include/sl_dlss.h:162.</remarks>
    public static SLResult DLSSGetState(ViewportHandle* viewport, DLSSState* state)
    {
        SLResult result = FeatureFunctions.Get(FeatureDLSS, "slDLSSGetState"u8, out nint address);
        if (result != SLResult.Ok)
        {
            return result;
        }
        return ((delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSState*, SLResult>)address)(viewport, state);
    }

    /// <summary>Convenience overload. References are fixed only until the native call returns; nested pointers retain their original lifetime requirements.</summary>
    public static SLResult DLSSGetState(in ViewportHandle viewport, ref DLSSState state)
    {
        fixed (ViewportHandle* viewportPointer = &viewport)
        fixed (DLSSState* statePointer = &state)
        {
            return DLSSGetState(viewportPointer, statePointer);
        }
    }
}

public static unsafe partial class SL
{
    /// <summary>
    /// Sets DLSS options
    /// 
    /// Call this method to turn DLSS on/off, change mode etc.
    /// 
    /// @param viewport Specified viewport we are working with
    /// @param options Specifies DLSS options to use
    /// @return sl::ResultCode::eOk if successful, error code otherwise (see sl_result.h for details)
    /// 
    /// This method is NOT thread safe.
    /// </summary>
    /// <remarks>Source: include/sl_dlss.h:173.</remarks>
    public static SLResult DLSSSetOptions(ViewportHandle* viewport, DLSSOptions* options)
    {
        SLResult result = FeatureFunctions.Get(FeatureDLSS, "slDLSSSetOptions"u8, out nint address);
        if (result != SLResult.Ok)
        {
            return result;
        }
        return ((delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSOptions*, SLResult>)address)(viewport, options);
    }

    /// <summary>Convenience overload. References are fixed only until the native call returns; nested pointers retain their original lifetime requirements.</summary>
    public static SLResult DLSSSetOptions(in ViewportHandle viewport, in DLSSOptions options)
    {
        fixed (ViewportHandle* viewportPointer = &viewport)
        fixed (DLSSOptions* optionsPointer = &options)
        {
            return DLSSSetOptions(viewportPointer, optionsPointer);
        }
    }
}
