// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.
// Source: NVIDIA-RTX/Streamline v2.14.1 (2122257e0fce486f91b385aa63b9a09b0a34b363).

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Streamline.NET;

public static unsafe partial class SL
{

    public static unsafe partial class DLSS
    {

        /// <summary>
        /// sl::getDLSSModeAsStr
        /// </summary>
        /// <remarks>Source: include/sl_helpers.h:196. </remarks>
        public static string GetModeAsStr(DLSSMode mode)
        {
            return mode switch
            {
                DLSSMode.Off => "DLSSMode::eOff",
                DLSSMode.DLAA => "DLSSMode::eDLAA",
                DLSSMode.MaxPerformance => "DLSSMode::eMaxPerformance",
                DLSSMode.Balanced => "DLSSMode::eBalanced",
                DLSSMode.MaxQuality => "DLSSMode::eMaxQuality",
                DLSSMode.UltraPerformance => "DLSSMode::eUltraPerformance",
                DLSSMode.UltraQuality => "DLSSMode::eUltraQuality",
                _ => "Unknown"
            };
        }
    }
}
