// <auto-generated/>
// Generated by Streamline.NET.Generator. Changes belong in the generator.

namespace Streamline.NET;

internal sealed unsafe partial class FeatureFunctions
{
    private nint slDeepDVCSetOptions;

    internal SLResult ResolveDeepDVCSetOptions(out delegate* unmanaged[Cdecl]<ViewportHandle*, DeepDVCOptions*, SLResult> function)
    {
        SLResult result = Resolve(ref slDeepDVCSetOptions, SL.FeatureDeepDVC, "slDeepDVCSetOptions"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, DeepDVCOptions*, SLResult>)address;

        return result;
    }

    private nint slDeepDVCGetState;

    internal SLResult ResolveDeepDVCGetState(out delegate* unmanaged[Cdecl]<ViewportHandle*, DeepDVCState*, SLResult> function)
    {
        SLResult result = Resolve(ref slDeepDVCGetState, SL.FeatureDeepDVC, "slDeepDVCGetState"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, DeepDVCState*, SLResult>)address;

        return result;
    }

    private nint slDirectSRGetOptimalSettings;

    internal SLResult ResolveDirectSRGetOptimalSettings(out delegate* unmanaged[Cdecl]<DirectSROptions*, DirectSROptimalSettings*, SLResult> function)
    {
        SLResult result = Resolve(ref slDirectSRGetOptimalSettings, SL.FeatureDirectSR, "slDirectSRGetOptimalSettings"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<DirectSROptions*, DirectSROptimalSettings*, SLResult>)address;

        return result;
    }

    private nint slDirectSRGetVariantInfo;

    internal SLResult ResolveDirectSRGetVariantInfo(out delegate* unmanaged[Cdecl]<uint*, DirectSRVariantInfo*, SLResult> function)
    {
        SLResult result = Resolve(ref slDirectSRGetVariantInfo, SL.FeatureDirectSR, "slDirectSRGetVariantInfo"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<uint*, DirectSRVariantInfo*, SLResult>)address;

        return result;
    }

    private nint slDirectSRSetOptions;

    internal SLResult ResolveDirectSRSetOptions(out delegate* unmanaged[Cdecl]<ViewportHandle*, DirectSROptions*, SLResult> function)
    {
        SLResult result = Resolve(ref slDirectSRSetOptions, SL.FeatureDirectSR, "slDirectSRSetOptions"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, DirectSROptions*, SLResult>)address;

        return result;
    }

    private nint slDLSSGetOptimalSettings;

    internal SLResult ResolveDLSSGetOptimalSettings(out delegate* unmanaged[Cdecl]<DLSSOptions*, DLSSOptimalSettings*, SLResult> function)
    {
        SLResult result = Resolve(ref slDLSSGetOptimalSettings, SL.FeatureDLSS, "slDLSSGetOptimalSettings"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<DLSSOptions*, DLSSOptimalSettings*, SLResult>)address;

        return result;
    }

    private nint slDLSSGetState;

    internal SLResult ResolveDLSSGetState(out delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSState*, SLResult> function)
    {
        SLResult result = Resolve(ref slDLSSGetState, SL.FeatureDLSS, "slDLSSGetState"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSState*, SLResult>)address;

        return result;
    }

    private nint slDLSSSetOptions;

    internal SLResult ResolveDLSSSetOptions(out delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSOptions*, SLResult> function)
    {
        SLResult result = Resolve(ref slDLSSSetOptions, SL.FeatureDLSS, "slDLSSSetOptions"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSOptions*, SLResult>)address;

        return result;
    }

    private nint slDLSSDGetOptimalSettings;

    internal SLResult ResolveDLSSDGetOptimalSettings(out delegate* unmanaged[Cdecl]<DLSSDOptions*, DLSSDOptimalSettings*, SLResult> function)
    {
        SLResult result = Resolve(ref slDLSSDGetOptimalSettings, SL.FeatureDLSSRR, "slDLSSDGetOptimalSettings"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<DLSSDOptions*, DLSSDOptimalSettings*, SLResult>)address;

        return result;
    }

    private nint slDLSSDGetState;

    internal SLResult ResolveDLSSDGetState(out delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSDState*, SLResult> function)
    {
        SLResult result = Resolve(ref slDLSSDGetState, SL.FeatureDLSSRR, "slDLSSDGetState"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSDState*, SLResult>)address;

        return result;
    }

    private nint slDLSSDSetOptions;

    internal SLResult ResolveDLSSDSetOptions(out delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSDOptions*, SLResult> function)
    {
        SLResult result = Resolve(ref slDLSSDSetOptions, SL.FeatureDLSSRR, "slDLSSDSetOptions"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSDOptions*, SLResult>)address;

        return result;
    }

    private nint slDLSSGGetState;

    internal SLResult ResolveDLSSGGetState(out delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSGState*, DLSSGOptions*, SLResult> function)
    {
        SLResult result = Resolve(ref slDLSSGGetState, SL.FeatureDLSSG, "slDLSSGGetState"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSGState*, DLSSGOptions*, SLResult>)address;

        return result;
    }

    private nint slDLSSGSetOptions;

    internal SLResult ResolveDLSSGSetOptions(out delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSGOptions*, SLResult> function)
    {
        SLResult result = Resolve(ref slDLSSGSetOptions, SL.FeatureDLSSG, "slDLSSGSetOptions"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, DLSSGOptions*, SLResult>)address;

        return result;
    }

    private nint slNISSetOptions;

    internal SLResult ResolveNISSetOptions(out delegate* unmanaged[Cdecl]<ViewportHandle*, NISOptions*, SLResult> function)
    {
        SLResult result = Resolve(ref slNISSetOptions, SL.FeatureNIS, "slNISSetOptions"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, NISOptions*, SLResult>)address;

        return result;
    }

    private nint slNISGetState;

    internal SLResult ResolveNISGetState(out delegate* unmanaged[Cdecl]<ViewportHandle*, NISState*, SLResult> function)
    {
        SLResult result = Resolve(ref slNISGetState, SL.FeatureNIS, "slNISGetState"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, NISState*, SLResult>)address;

        return result;
    }

    private nint slPCLGetState;

    internal SLResult ResolvePCLGetState(out delegate* unmanaged[Cdecl]<PCLState*, SLResult> function)
    {
        SLResult result = Resolve(ref slPCLGetState, SL.FeaturePCL, "slPCLGetState"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<PCLState*, SLResult>)address;

        return result;
    }

    private nint slPCLSetMarker;

    internal SLResult ResolvePCLSetMarker(out delegate* unmanaged[Cdecl]<PCLMarker, nint, SLResult> function)
    {
        SLResult result = Resolve(ref slPCLSetMarker, SL.FeaturePCL, "slPCLSetMarker"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<PCLMarker, nint, SLResult>)address;

        return result;
    }

    private nint slPCLSetOptions;

    internal SLResult ResolvePCLSetOptions(out delegate* unmanaged[Cdecl]<PCLOptions*, SLResult> function)
    {
        SLResult result = Resolve(ref slPCLSetOptions, SL.FeaturePCL, "slPCLSetOptions"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<PCLOptions*, SLResult>)address;

        return result;
    }

    private nint slReflexGetState;

    internal SLResult ResolveReflexGetState(out delegate* unmanaged[Cdecl]<ReflexState*, SLResult> function)
    {
        SLResult result = Resolve(ref slReflexGetState, SL.FeatureReflex, "slReflexGetState"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ReflexState*, SLResult>)address;

        return result;
    }

    private nint slReflexSleep;

    internal SLResult ResolveReflexSleep(out delegate* unmanaged[Cdecl]<nint, SLResult> function)
    {
        SLResult result = Resolve(ref slReflexSleep, SL.FeatureReflex, "slReflexSleep"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<nint, SLResult>)address;

        return result;
    }

    private nint slReflexSetOptions;

    internal SLResult ResolveReflexSetOptions(out delegate* unmanaged[Cdecl]<ReflexOptions*, SLResult> function)
    {
        SLResult result = Resolve(ref slReflexSetOptions, SL.FeatureReflex, "slReflexSetOptions"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ReflexOptions*, SLResult>)address;

        return result;
    }

    private nint slReflexSetCameraData;

    internal SLResult ResolveReflexSetCameraData(out delegate* unmanaged[Cdecl]<ViewportHandle*, nint, ReflexCameraData*, SLResult> function)
    {
        SLResult result = Resolve(ref slReflexSetCameraData, SL.FeatureReflex, "slReflexSetCameraData"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, nint, ReflexCameraData*, SLResult>)address;

        return result;
    }

    private nint slReflexGetPredictedCameraData;

    internal SLResult ResolveReflexGetPredictedCameraData(out delegate* unmanaged[Cdecl]<ViewportHandle*, nint, ReflexPredictedCameraData*, SLResult> function)
    {
        SLResult result = Resolve(ref slReflexGetPredictedCameraData, SL.FeatureReflex, "slReflexGetPredictedCameraData"u8, out nint address);
        function = (delegate* unmanaged[Cdecl]<ViewportHandle*, nint, ReflexPredictedCameraData*, SLResult>)address;

        return result;
    }
}
