<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../Streamline.NET/Streamline.NET.csproj" />
        <PackageReference Include="Vortice.Direct3D12" />
        <PackageReference Include="Vortice.DXGI" />
        <PackageReference Include="Vortice.Vulkan" />
        <PackageReference Include="Slangc.NET" />
        <PackageReference Include="Vortice.Dxc.Native" />
        <PackageReference Include="SharpGLTF.Core" />
        <PackageReference Include="SixLabors.ImageSharp" />
        <PackageReference Include="ImGui.NET" />
    </ItemGroup>
    <ItemGroup>
        <None Update="Assets/Shaders/**/*;Assets/Scenes/**/*" CopyToOutputDirectory="PreserveNewest" />
        <None Remove="Assets/Streamline/**/*" />
        <Content Include="Assets/Streamline/sl.interposer.*;Assets/Streamline/sl.common.*;Assets/Streamline/sl.dlss*;Assets/Streamline/sl.reflex.*;Assets/Streamline/sl.pcl.*;Assets/Streamline/nvngx_dlss*;Assets/Streamline/NvLowLatencyVk.*;Assets/Streamline/reflex.license.*;Assets/Streamline/streamline-runtime.*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" TargetPath="%(Filename)%(Extension)" />
        <Content Include="Assets/Streamline/Licenses/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" TargetPath="Licenses/%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>
</Project>
