<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(StandardTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NGX.NET\NGX.NET.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ImGui.NET" />
        <PackageReference Include="SharpGLTF.Core" />
        <PackageReference Include="Slangc.NET" />
        <PackageReference Include="StbImageSharp" />
        <PackageReference Include="Vortice.Direct3D12" />
        <PackageReference Include="Vortice.DXGI" />
        <PackageReference Include="Vortice.Vulkan" />
    </ItemGroup>

    <ItemGroup>
        <None Update="Assets\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
