namespace Generation;

internal static class SourceStyleChecks
{
    internal static void Run(string path, string source)
    {
        Require(!source.Contains("///", StringComparison.Ordinal) && !source.Contains("// <auto-generated/>", StringComparison.Ordinal), $"Generated header or documentation: {path}.");
        Require(source.StartsWith("#nullable enable\n", StringComparison.Ordinal), $"Generated nullable context: {path}.");
        Require(source.EndsWith('\n') && !source.EndsWith("\n\n", StringComparison.Ordinal), $"Final newline: {path}.");
        Require(!source.Contains('\r') && !source.Contains('\t') && !source.Contains("\n\n\n", StringComparison.Ordinal), $"Whitespace: {path}.");
        string[] lines = source.Split('\n');
        foreach (string line in lines)
        {
            Require(line.TrimEnd() == line, $"Trailing whitespace: {path}.");
            Require((line.Length - line.TrimStart().Length) % 4 is 0, $"Indentation: {path}.");
        }

        CompilationUnitSyntax syntax = CSharpSyntaxTree.ParseText(source).GetCompilationUnitRoot();
        Require(!syntax.ContainsDiagnostics, $"Invalid C# syntax: {path}.");
        Require(syntax.Usings.Count is 0, $"Generated imports must use Usings.cs: {path}.");
        Require(syntax.Members is [FileScopedNamespaceDeclarationSyntax], $"File-scoped namespace: {path}.");
        FileScopedNamespaceDeclarationSyntax fileNamespace = (FileScopedNamespaceDeclarationSyntax)syntax.Members[0];
        Require(fileNamespace.Members.Count > 0, $"Missing main type: {path}.");
        foreach (MemberDeclarationSyntax helper in fileNamespace.Members.Skip(1))
        {
            Require(helper is TypeDeclarationSyntax type && (type.Modifiers.Any(SyntaxKind.InternalKeyword) || type.Modifiers.Any(SyntaxKind.FileKeyword)), $"Invalid auxiliary type: {path}.");
        }

        SyntaxStyleChecks.Run(path, syntax);

        foreach (SyntaxNode node in syntax.DescendantNodes())
        {
            Require(node is not RecordDeclarationSyntax, $"Record declaration: {path}.");

            if (node is VariableDeclarationSyntax declaration)
            {
                Require(!declaration.Type.IsVar, $"Implicit variable type: {path}.");
                Require(declaration.Variables.Count is 1 || declaration.Parent is ForStatementSyntax, $"Multiple variable declarations: {path}.");
            }

            if (node is MethodDeclarationSyntax method)
            {
                Require(method.ExpressionBody is null, $"Expression-bodied method: {path}.");
            }

            if (node is BlockSyntax block)
            {
                CheckBrace(path, lines, block.OpenBraceToken);
                CheckBrace(path, lines, block.CloseBraceToken);
                CheckStatements(path, lines, block);
            }

            if (node is EnumDeclarationSyntax enumeration)
            {
                CheckBrace(path, lines, enumeration.OpenBraceToken);
                CheckBrace(path, lines, enumeration.CloseBraceToken);

                for (int i = 1; i < enumeration.Members.Count; i++)
                {
                    int previousLine = enumeration.Members[i - 1].GetLastToken().GetLocation().GetLineSpan().EndLinePosition.Line;
                    Require(lines[previousLine + 1].Length is 0, $"Enum member spacing: {path}:{previousLine + 1}.");
                }

                if (enumeration.AttributeLists.SelectMany(static list => list.Attributes).Any(static attribute => attribute.Name.ToString() is "Flags"))
                {
                    Require(enumeration.Members.Any(static member => member.Identifier.ValueText is "None" && member.EqualsValue?.Value is LiteralExpressionSyntax { Token.ValueText: "0" }), $"Flags without None: {path}.");
                }
            }

            if (node is TypeDeclarationSyntax type)
            {
                Require(!type.Modifiers.Any(SyntaxKind.SealedKeyword), $"Sealed type: {path}.");
                CheckBrace(path, lines, type.OpenBraceToken);
                CheckBrace(path, lines, type.CloseBraceToken);
                CheckMembers(path, lines, type.Members);
            }

            StatementSyntax? embedded = node switch
            {
                IfStatementSyntax value => value.Statement,
                ElseClauseSyntax { Statement: not IfStatementSyntax } value => value.Statement,
                ForStatementSyntax value => value.Statement,
                ForEachStatementSyntax value => value.Statement,
                WhileStatementSyntax value => value.Statement,
                DoStatementSyntax value => value.Statement,
                FixedStatementSyntax value => value.Statement,
                LockStatementSyntax value => value.Statement,
                UsingStatementSyntax value => value.Statement,
                _ => null
            };
            Require(embedded is null or BlockSyntax, $"Unbraced control statement: {path}.");
        }
    }

    private static void CheckBrace(string path, string[] lines, SyntaxToken token)
    {
        int line = token.GetLocation().GetLineSpan().StartLinePosition.Line;
        Require(lines[line].Trim() is "{" or "}" or "};", $"Allman brace at {path}:{line + 1}.");

        if (token.IsKind(SyntaxKind.OpenBraceToken))
        {
            Require(line + 1 < lines.Length && lines[line + 1].Length is not 0, $"Blank line after opening brace: {path}:{line + 1}.");
        }
        else
        {
            Require(line > 0 && lines[line - 1].Length is not 0, $"Blank line before closing brace: {path}:{line + 1}.");
        }
    }

    private static void CheckStatements(string path, string[] lines, BlockSyntax block)
    {
        for (int i = 1; i < block.Statements.Count; i++)
        {
            StatementSyntax statement = block.Statements[i];
            if (statement is ReturnStatementSyntax or BreakStatementSyntax or ContinueStatementSyntax)
            {
                int line = statement.GetLocation().GetLineSpan().StartLinePosition.Line;
                Require(lines[line - 1].Length is 0, $"Missing blank line before exit: {path}:{line + 1}.");
            }
        }
    }

    private static void CheckMembers(string path, string[] lines, SyntaxList<MemberDeclarationSyntax> members)
    {
        int previousRank = -1;
        for (int i = 0; i < members.Count; i++)
        {
            MemberDeclarationSyntax member = members[i];
            int rank = SyntaxStyleChecks.MemberRank(member);
            Require(rank >= previousRank, $"Member order: {path}.");
            previousRank = rank;

            if (i is 0)
            {
                continue;
            }

            int previousLine = members[i - 1].GetLastToken().GetLocation().GetLineSpan().EndLinePosition.Line;
            bool constants = member is FieldDeclarationSyntax current && current.Modifiers.Any(SyntaxKind.ConstKeyword) && members[i - 1] is FieldDeclarationSyntax previous && previous.Modifiers.Any(SyntaxKind.ConstKeyword);
            Require(constants ? lines[previousLine + 1].Length is not 0 : lines[previousLine + 1].Length is 0, $"Member spacing: {path}:{previousLine + 1}.");
        }
    }
}
