// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

public static unsafe partial class NGX
{
    /// <summary>
    /// D3D11 application API and native inline helpers.
    /// </summary>
    public static partial class D3D11
    {
        /// <summary>
        /// NGX_D3D11_CREATE_DLISP_EXT. Source: nvsdk_ngx_helpers_d3d.h:169.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_CREATE_DLISP_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result CreateDLISPExt(nint @PInCtx, global::NGX.NET.Handle** @PpOutHandle, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.FeatureCreateParams* @PDlispCreateParams);

        /// <summary>
        /// Pins native structures for NGX_D3D11_CREATE_DLISP_EXT.
        /// </summary>
        public static global::NGX.NET.Result CreateDLISPExt(nint @PInCtx, global::NGX.NET.Handle** @PpOutHandle, global::NGX.NET.Parameter* @PInParams, ref global::NGX.NET.FeatureCreateParams @PDlispCreateParams)
        {
            fixed (global::NGX.NET.FeatureCreateParams* pointer0 = &@PDlispCreateParams)
            {
                return CreateDLISPExt(@PInCtx, @PpOutHandle, @PInParams, pointer0);
            }
        }

        /// <summary>
        /// Returns the reviewed output of NGX_D3D11_CREATE_DLISP_EXT; throws on NGX failure. The caller owns any returned handle or parameter map.
        /// </summary>
        public static global::NGX.NET.Handle* CreateDLISPExt(nint @PInCtx, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.FeatureCreateParams* @PDlispCreateParams)
        {
            global::NGX.NET.Handle* value = default;
            ThrowIfFailed(CreateDLISPExt(@PInCtx, &value, @PInParams, @PDlispCreateParams), "NGX_D3D11_CREATE_DLISP_EXT");

            return value;
        }

        /// <summary>
        /// Preserves the native result and writes the output of NGX_D3D11_CREATE_DLISP_EXT.
        /// </summary>
        public static global::NGX.NET.Result CreateDLISPExt(nint @PInCtx, out global::NGX.NET.Handle* value, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.FeatureCreateParams* @PDlispCreateParams)
        {
            value = default;

            fixed (global::NGX.NET.Handle** pointer = &value)
            {
                return CreateDLISPExt(@PInCtx, pointer, @PInParams, @PDlispCreateParams);
            }
        }

        /// <summary>
        /// NGX_D3D11_CREATE_DLSSD_EXT. Source: nvsdk_ngx_helpers_dlssd_d3d.h:227.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_CREATE_DLSSD_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result CreateDLSSDExt(nint @PInCtx, global::NGX.NET.Handle** @PpOutHandle, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.DLSSDCreateParams* @PInDlssDCreateParams);

        /// <summary>
        /// Pins native structures for NGX_D3D11_CREATE_DLSSD_EXT.
        /// </summary>
        public static global::NGX.NET.Result CreateDLSSDExt(nint @PInCtx, global::NGX.NET.Handle** @PpOutHandle, global::NGX.NET.Parameter* @PInParams, ref global::NGX.NET.DLSSDCreateParams @PInDlssDCreateParams)
        {
            fixed (global::NGX.NET.DLSSDCreateParams* pointer0 = &@PInDlssDCreateParams)
            {
                return CreateDLSSDExt(@PInCtx, @PpOutHandle, @PInParams, pointer0);
            }
        }

        /// <summary>
        /// Returns the reviewed output of NGX_D3D11_CREATE_DLSSD_EXT; throws on NGX failure. The caller owns any returned handle or parameter map.
        /// </summary>
        public static global::NGX.NET.Handle* CreateDLSSDExt(nint @PInCtx, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.DLSSDCreateParams* @PInDlssDCreateParams)
        {
            global::NGX.NET.Handle* value = default;
            ThrowIfFailed(CreateDLSSDExt(@PInCtx, &value, @PInParams, @PInDlssDCreateParams), "NGX_D3D11_CREATE_DLSSD_EXT");

            return value;
        }

        /// <summary>
        /// Preserves the native result and writes the output of NGX_D3D11_CREATE_DLSSD_EXT.
        /// </summary>
        public static global::NGX.NET.Result CreateDLSSDExt(nint @PInCtx, out global::NGX.NET.Handle* value, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.DLSSDCreateParams* @PInDlssDCreateParams)
        {
            value = default;

            fixed (global::NGX.NET.Handle** pointer = &value)
            {
                return CreateDLSSDExt(@PInCtx, pointer, @PInParams, @PInDlssDCreateParams);
            }
        }

        /// <summary>
        /// NGX_D3D11_CREATE_DLSS_EXT. Source: nvsdk_ngx_helpers_d3d.h:85.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_CREATE_DLSS_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result CreateDLSSExt(nint @PInCtx, global::NGX.NET.Handle** @PpOutHandle, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.DLSSCreateParams* @PInDlssCreateParams);

        /// <summary>
        /// Pins native structures for NGX_D3D11_CREATE_DLSS_EXT.
        /// </summary>
        public static global::NGX.NET.Result CreateDLSSExt(nint @PInCtx, global::NGX.NET.Handle** @PpOutHandle, global::NGX.NET.Parameter* @PInParams, ref global::NGX.NET.DLSSCreateParams @PInDlssCreateParams)
        {
            fixed (global::NGX.NET.DLSSCreateParams* pointer0 = &@PInDlssCreateParams)
            {
                return CreateDLSSExt(@PInCtx, @PpOutHandle, @PInParams, pointer0);
            }
        }

        /// <summary>
        /// Returns the reviewed output of NGX_D3D11_CREATE_DLSS_EXT; throws on NGX failure. The caller owns any returned handle or parameter map.
        /// </summary>
        public static global::NGX.NET.Handle* CreateDLSSExt(nint @PInCtx, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.DLSSCreateParams* @PInDlssCreateParams)
        {
            global::NGX.NET.Handle* value = default;
            ThrowIfFailed(CreateDLSSExt(@PInCtx, &value, @PInParams, @PInDlssCreateParams), "NGX_D3D11_CREATE_DLSS_EXT");

            return value;
        }

        /// <summary>
        /// Preserves the native result and writes the output of NGX_D3D11_CREATE_DLSS_EXT.
        /// </summary>
        public static global::NGX.NET.Result CreateDLSSExt(nint @PInCtx, out global::NGX.NET.Handle* value, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.DLSSCreateParams* @PInDlssCreateParams)
        {
            value = default;

            fixed (global::NGX.NET.Handle** pointer = &value)
            {
                return CreateDLSSExt(@PInCtx, pointer, @PInParams, @PInDlssCreateParams);
            }
        }

        /// <summary>
        /// NGX_D3D11_EVALUATE_DLISP_EXT. Source: nvsdk_ngx_helpers_d3d.h:183.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_EVALUATE_DLISP_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result EvaluateDLISPExt(nint @PInCtx, global::NGX.NET.Handle* @PInHandle, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.D3D11DLISPEvalParams* @PDlispEvalParams);

        /// <summary>
        /// Pins native structures for NGX_D3D11_EVALUATE_DLISP_EXT.
        /// </summary>
        public static global::NGX.NET.Result EvaluateDLISPExt(nint @PInCtx, global::NGX.NET.Handle* @PInHandle, global::NGX.NET.Parameter* @PInParams, ref global::NGX.NET.D3D11DLISPEvalParams @PDlispEvalParams)
        {
            fixed (global::NGX.NET.D3D11DLISPEvalParams* pointer0 = &@PDlispEvalParams)
            {
                return EvaluateDLISPExt(@PInCtx, @PInHandle, @PInParams, pointer0);
            }
        }

        /// <summary>
        /// NGX_D3D11_EVALUATE_DLSSD_EXT. Source: nvsdk_ngx_helpers_dlssd_d3d.h:247.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_EVALUATE_DLSSD_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result EvaluateDLSSDExt(nint @PInCtx, global::NGX.NET.Handle* @PInHandle, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.D3D11DLSSDEvalParams* @PInDlssDEvalParams);

        /// <summary>
        /// Pins native structures for NGX_D3D11_EVALUATE_DLSSD_EXT.
        /// </summary>
        public static global::NGX.NET.Result EvaluateDLSSDExt(nint @PInCtx, global::NGX.NET.Handle* @PInHandle, global::NGX.NET.Parameter* @PInParams, ref global::NGX.NET.D3D11DLSSDEvalParams @PInDlssDEvalParams)
        {
            fixed (global::NGX.NET.D3D11DLSSDEvalParams* pointer0 = &@PInDlssDEvalParams)
            {
                return EvaluateDLSSDExt(@PInCtx, @PInHandle, @PInParams, pointer0);
            }
        }

        /// <summary>
        /// NGX_D3D11_EVALUATE_DLSS_EXT. Source: nvsdk_ngx_helpers_d3d.h:103.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_EVALUATE_DLSS_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result EvaluateDLSSExt(nint @PInCtx, global::NGX.NET.Handle* @PInHandle, global::NGX.NET.Parameter* @PInParams, global::NGX.NET.D3D11DLSSEvalParams* @PInDlssEvalParams);

        /// <summary>
        /// Pins native structures for NGX_D3D11_EVALUATE_DLSS_EXT.
        /// </summary>
        public static global::NGX.NET.Result EvaluateDLSSExt(nint @PInCtx, global::NGX.NET.Handle* @PInHandle, global::NGX.NET.Parameter* @PInParams, ref global::NGX.NET.D3D11DLSSEvalParams @PInDlssEvalParams)
        {
            fixed (global::NGX.NET.D3D11DLSSEvalParams* pointer0 = &@PInDlssEvalParams)
            {
                return EvaluateDLSSExt(@PInCtx, @PInHandle, @PInParams, pointer0);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_AllocateParameters. Source: nvsdk_ngx.h:380.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_AllocateParameters")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result AllocateParameters(global::NGX.NET.Parameter** @OutParameters);

        /// <summary>
        /// Returns the reviewed output of NVSDK_NGX_D3D11_AllocateParameters; throws on NGX failure. The caller owns any returned handle or parameter map.
        /// </summary>
        public static global::NGX.NET.Parameter* AllocateParameters()
        {
            global::NGX.NET.Parameter* value = default;
            ThrowIfFailed(AllocateParameters(&value), "NVSDK_NGX_D3D11_AllocateParameters");

            return value;
        }

        /// <summary>
        /// Preserves the native result and writes the output of NVSDK_NGX_D3D11_AllocateParameters.
        /// </summary>
        public static global::NGX.NET.Result AllocateParameters(out global::NGX.NET.Parameter* value)
        {
            value = default;

            fixed (global::NGX.NET.Parameter** pointer = &value)
            {
                return AllocateParameters(pointer);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_CreateFeature. Source: nvsdk_ngx.h:549.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_CreateFeature")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result CreateFeature(nint @InDevCtx, global::NGX.NET.Feature @InFeatureID, global::NGX.NET.Parameter* @InParameters, global::NGX.NET.Handle** @OutHandle);

        /// <summary>
        /// Returns the reviewed output of NVSDK_NGX_D3D11_CreateFeature; throws on NGX failure. The caller owns any returned handle or parameter map.
        /// </summary>
        public static global::NGX.NET.Handle* CreateFeature(nint @InDevCtx, global::NGX.NET.Feature @InFeatureID, global::NGX.NET.Parameter* @InParameters)
        {
            global::NGX.NET.Handle* value = default;
            ThrowIfFailed(CreateFeature(@InDevCtx, @InFeatureID, @InParameters, &value), "NVSDK_NGX_D3D11_CreateFeature");

            return value;
        }

        /// <summary>
        /// Preserves the native result and writes the output of NVSDK_NGX_D3D11_CreateFeature.
        /// </summary>
        public static global::NGX.NET.Result CreateFeature(nint @InDevCtx, global::NGX.NET.Feature @InFeatureID, global::NGX.NET.Parameter* @InParameters, out global::NGX.NET.Handle* value)
        {
            value = default;

            fixed (global::NGX.NET.Handle** pointer = &value)
            {
                return CreateFeature(@InDevCtx, @InFeatureID, @InParameters, pointer);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_DestroyParameters. Source: nvsdk_ngx.h:449.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_DestroyParameters")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result DestroyParameters(global::NGX.NET.Parameter* @InParameters);

        /// <summary>
        /// NVSDK_NGX_D3D11_EvaluateFeature. Source: nvsdk_ngx.h:683.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_EvaluateFeature")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result EvaluateFeature(nint @InDevCtx, global::NGX.NET.Handle* @InFeatureHandle, global::NGX.NET.Parameter* @InParameters, delegate* unmanaged[Cdecl]<float, global::NGX.NET.Bool8*, void> @InCallback);

        /// <summary>
        /// NVSDK_NGX_D3D11_EvaluateFeature_C. Source: nvsdk_ngx.h:688.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_EvaluateFeature_C")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result EvaluateFeatureC(nint @InDevCtx, global::NGX.NET.Handle* @InFeatureHandle, global::NGX.NET.Parameter* @InParameters, delegate* unmanaged[Cdecl]<float, global::NGX.NET.Bool8*, void> @InCallback);

        /// <summary>
        /// NVSDK_NGX_D3D11_GetCapabilityParameters. Source: nvsdk_ngx.h:422.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_GetCapabilityParameters")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetCapabilityParameters(global::NGX.NET.Parameter** @OutParameters);

        /// <summary>
        /// Returns the reviewed output of NVSDK_NGX_D3D11_GetCapabilityParameters; throws on NGX failure. The caller owns any returned handle or parameter map.
        /// </summary>
        public static global::NGX.NET.Parameter* GetCapabilityParameters()
        {
            global::NGX.NET.Parameter* value = default;
            ThrowIfFailed(GetCapabilityParameters(&value), "NVSDK_NGX_D3D11_GetCapabilityParameters");

            return value;
        }

        /// <summary>
        /// Preserves the native result and writes the output of NVSDK_NGX_D3D11_GetCapabilityParameters.
        /// </summary>
        public static global::NGX.NET.Result GetCapabilityParameters(out global::NGX.NET.Parameter* value)
        {
            value = default;

            fixed (global::NGX.NET.Parameter** pointer = &value)
            {
                return GetCapabilityParameters(pointer);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_GetFeatureRequirements. Source: nvsdk_ngx.h:617.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_GetFeatureRequirements")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetFeatureRequirements(nint @Adapter, global::NGX.NET.FeatureDiscoveryInfo* @FeatureDiscoveryInfo, global::NGX.NET.FeatureRequirement* @OutSupported);

        /// <summary>
        /// Pins native structures for NVSDK_NGX_D3D11_GetFeatureRequirements.
        /// </summary>
        public static global::NGX.NET.Result GetFeatureRequirements(nint @Adapter, ref global::NGX.NET.FeatureDiscoveryInfo @FeatureDiscoveryInfo, ref global::NGX.NET.FeatureRequirement @OutSupported)
        {
            fixed (global::NGX.NET.FeatureDiscoveryInfo* pointer0 = &@FeatureDiscoveryInfo)
            fixed (global::NGX.NET.FeatureRequirement* pointer1 = &@OutSupported)
            {
                return GetFeatureRequirements(@Adapter, pointer0, pointer1);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_GetParameters. Source: nvsdk_ngx.h:332.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_GetParameters")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetParameters(global::NGX.NET.Parameter** @OutParameters);

        /// <summary>
        /// NVSDK_NGX_D3D11_GetScratchBufferSize. Source: nvsdk_ngx.h:483.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_GetScratchBufferSize")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetScratchBufferSize(global::NGX.NET.Feature @InFeatureId, global::NGX.NET.Parameter* @InParameters, nuint* @OutSizeInBytes);

        /// <summary>
        /// Returns the reviewed output of NVSDK_NGX_D3D11_GetScratchBufferSize; throws on NGX failure. The caller owns any returned handle or parameter map.
        /// </summary>
        public static nuint GetScratchBufferSize(global::NGX.NET.Feature @InFeatureId, global::NGX.NET.Parameter* @InParameters)
        {
            nuint value = default;
            ThrowIfFailed(GetScratchBufferSize(@InFeatureId, @InParameters, &value), "NVSDK_NGX_D3D11_GetScratchBufferSize");

            return value;
        }

        /// <summary>
        /// Preserves the native result and writes the output of NVSDK_NGX_D3D11_GetScratchBufferSize.
        /// </summary>
        public static global::NGX.NET.Result GetScratchBufferSize(global::NGX.NET.Feature @InFeatureId, global::NGX.NET.Parameter* @InParameters, out nuint value)
        {
            value = default;

            fixed (nuint* pointer = &value)
            {
                return GetScratchBufferSize(@InFeatureId, @InParameters, pointer);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_Init. Source: nvsdk_ngx.h:168.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_Init")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result Init(ulong @InApplicationId, void* @InApplicationDataPath, nint @InDevice, global::NGX.NET.FeatureCommonInfo* @InFeatureInfo, global::NGX.NET.Version @InSDKVersion);

        /// <summary>
        /// Pins native structures for NVSDK_NGX_D3D11_Init.
        /// </summary>
        public static global::NGX.NET.Result Init(ulong @InApplicationId, void* @InApplicationDataPath, nint @InDevice, ref global::NGX.NET.FeatureCommonInfo @InFeatureInfo, global::NGX.NET.Version @InSDKVersion)
        {
            fixed (global::NGX.NET.FeatureCommonInfo* pointer0 = &@InFeatureInfo)
            {
                return Init(@InApplicationId, @InApplicationDataPath, @InDevice, pointer0, @InSDKVersion);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_Init_with_ProjectID. Source: nvsdk_ngx.h:246.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_Init_with_ProjectID")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result InitWithProjectID(sbyte* @InProjectId, global::NGX.NET.EngineType @InEngineType, sbyte* @InEngineVersion, void* @InApplicationDataPath, nint @InDevice, global::NGX.NET.FeatureCommonInfo* @InFeatureInfo, global::NGX.NET.Version @InSDKVersion);

        /// <summary>
        /// Pins native structures for NVSDK_NGX_D3D11_Init_with_ProjectID.
        /// </summary>
        public static global::NGX.NET.Result InitWithProjectID(sbyte* @InProjectId, global::NGX.NET.EngineType @InEngineType, sbyte* @InEngineVersion, void* @InApplicationDataPath, nint @InDevice, ref global::NGX.NET.FeatureCommonInfo @InFeatureInfo, global::NGX.NET.Version @InSDKVersion)
        {
            fixed (global::NGX.NET.FeatureCommonInfo* pointer0 = &@InFeatureInfo)
            {
                return InitWithProjectID(@InProjectId, @InEngineType, @InEngineVersion, @InApplicationDataPath, @InDevice, pointer0, @InSDKVersion);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_ReleaseFeature. Source: nvsdk_ngx.h:573.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_ReleaseFeature")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result ReleaseFeature(global::NGX.NET.Handle* @InHandle);

        /// <summary>
        /// NVSDK_NGX_D3D11_Shutdown. Source: nvsdk_ngx.h:278.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_Shutdown")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result Shutdown();

        /// <summary>
        /// NVSDK_NGX_D3D11_Shutdown1. Source: nvsdk_ngx.h:281.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_Shutdown1")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result Shutdown1(nint @InDevice);

    }
}
