// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

public static unsafe partial class Ngx
{
    /// <summary>
    /// D3D11 application API and native helpers.
    /// </summary>
    public static partial class D3D11
    {
        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_CREATE_DLISP_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult CreateDLISPExtNative(nint pInCtx, nint* ppOutHandle, nint pInParams, NGXFeatureCreateParamsNative* pDlispCreateParams);

        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_CREATE_DLSSD_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult CreateDLSSDExtNative(nint pInCtx, nint* ppOutHandle, nint pInParams, NGXDLSSDCreateParamsNative* pInDlssDCreateParams);

        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_CREATE_DLSS_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult CreateDLSSExtNative(nint pInCtx, nint* ppOutHandle, nint pInParams, NGXDLSSCreateParamsNative* pInDlssCreateParams);

        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_EVALUATE_DLISP_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult EvaluateDLISPExtNative(nint pInCtx, nint pInHandle, nint pInParams, NGXD3D11DLISPEvalParamsNative* pDlispEvalParams);

        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_EVALUATE_DLSSD_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult EvaluateDLSSDExtNative(nint pInCtx, nint pInHandle, nint pInParams, NGXD3D11DLSSDEvalParamsNative* pInDlssDEvalParams);

        [LibraryImport(LibraryName, EntryPoint = "NGX_Bridge_NGX_D3D11_EVALUATE_DLSS_EXT")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult EvaluateDLSSExtNative(nint pInCtx, nint pInHandle, nint pInParams, NGXD3D11DLSSEvalParamsNative* pInDlssEvalParams);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_AllocateParameters")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult AllocateParametersNative(nint* outParameters);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_CreateFeature")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult CreateFeatureNative(nint inDevCtx, NGXFeature inFeatureID, nint inParameters, nint* outHandle);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_DestroyParameters")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult DestroyParametersNative(nint inParameters);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_EvaluateFeature")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult EvaluateFeatureNative(nint inDevCtx, nint inFeatureHandle, nint inParameters, nint inCallback);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_EvaluateFeature_C")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult EvaluateFeatureCNative(nint inDevCtx, nint inFeatureHandle, nint inParameters, nint inCallback);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_GetCapabilityParameters")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetCapabilityParametersNative(nint* outParameters);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_GetFeatureRequirements")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetFeatureRequirementsNative(nint adapter, NGXFeatureDiscoveryInfoNative* featureDiscoveryInfo, NGXFeatureRequirementNative* outSupported);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_GetParameters")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetParametersNative(nint* outParameters);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_GetScratchBufferSize")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetScratchBufferSizeNative(NGXFeature inFeatureId, nint inParameters, nuint* outSizeInBytes);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_Init")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult InitNative(ulong inApplicationId, void* inApplicationDataPath, nint inDevice, NGXFeatureCommonInfoNative* inFeatureInfo, NGXVersion inSDKVersion);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_Init_with_ProjectID")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult InitWithProjectIDNative(sbyte* inProjectId, NGXEngineType inEngineType, sbyte* inEngineVersion, void* inApplicationDataPath, nint inDevice, NGXFeatureCommonInfoNative* inFeatureInfo, NGXVersion inSDKVersion);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_ReleaseFeature")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult ReleaseFeatureNative(nint inHandle);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_Shutdown")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult ShutdownNative();

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_D3D11_Shutdown1")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult Shutdown1Native(nint inDevice);

        static D3D11()
        {
            NativeLoader.Register();
        }

        /// <summary>
        /// NGX_D3D11_CREATE_DLISP_EXT
        /// </summary>
        public static NGXResult CreateDLISPExt(nint pInCtx, out NGXHandle ppOutHandle, NGXParameter pInParams, in NGXFeatureCreateParams pDlispCreateParams)
        {
            ppOutHandle = default;
            nint ppOutHandleNative = default;
            NGXFeatureCreateParamsNative pDlispCreateParamsNative = default;

            try
            {
                if (pInParams.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(pInParams));
                }

                pDlispCreateParamsNative = new(in pDlispCreateParams);
                NGXResult result = CreateDLISPExtNative(pInCtx, &ppOutHandleNative, pInParams.Value, &pDlispCreateParamsNative);
                if (result is NGXResult.Success)
                {
                    ppOutHandle = new(ppOutHandleNative);
                }

                return result;
            }
            finally
            {
                pDlispCreateParamsNative.Dispose();
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.D3D11.CreateDLISPExt after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static NGXHandle CreateDLISPExt(nint pInCtx, NGXParameter pInParams, in NGXFeatureCreateParams pDlispCreateParams)
        {
            NGXResult result = CreateDLISPExt(pInCtx, out NGXHandle ppOutHandle, pInParams, in pDlispCreateParams);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.D3D11.CreateDLISPExt");
            }

            return ppOutHandle;
        }

        /// <summary>
        /// NGX_D3D11_CREATE_DLSSD_EXT
        /// </summary>
        public static NGXResult CreateDLSSDExt(nint pInCtx, out NGXHandle ppOutHandle, NGXParameter pInParams, in NGXDLSSDCreateParams pInDlssDCreateParams)
        {
            ppOutHandle = default;
            nint ppOutHandleNative = default;
            NGXDLSSDCreateParamsNative pInDlssDCreateParamsNative = default;

            try
            {
                if (pInParams.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(pInParams));
                }

                pInDlssDCreateParamsNative = new(in pInDlssDCreateParams);
                NGXResult result = CreateDLSSDExtNative(pInCtx, &ppOutHandleNative, pInParams.Value, &pInDlssDCreateParamsNative);
                if (result is NGXResult.Success)
                {
                    ppOutHandle = new(ppOutHandleNative);
                }

                return result;
            }
            finally
            {
                pInDlssDCreateParamsNative.Dispose();
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.D3D11.CreateDLSSDExt after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static NGXHandle CreateDLSSDExt(nint pInCtx, NGXParameter pInParams, in NGXDLSSDCreateParams pInDlssDCreateParams)
        {
            NGXResult result = CreateDLSSDExt(pInCtx, out NGXHandle ppOutHandle, pInParams, in pInDlssDCreateParams);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.D3D11.CreateDLSSDExt");
            }

            return ppOutHandle;
        }

        /// <summary>
        /// NGX_D3D11_CREATE_DLSS_EXT
        /// </summary>
        public static NGXResult CreateDLSSExt(nint pInCtx, out NGXHandle ppOutHandle, NGXParameter pInParams, in NGXDLSSCreateParams pInDlssCreateParams)
        {
            ppOutHandle = default;
            nint ppOutHandleNative = default;
            NGXDLSSCreateParamsNative pInDlssCreateParamsNative = default;

            try
            {
                if (pInParams.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(pInParams));
                }

                pInDlssCreateParamsNative = new(in pInDlssCreateParams);
                NGXResult result = CreateDLSSExtNative(pInCtx, &ppOutHandleNative, pInParams.Value, &pInDlssCreateParamsNative);
                if (result is NGXResult.Success)
                {
                    ppOutHandle = new(ppOutHandleNative);
                }

                return result;
            }
            finally
            {
                pInDlssCreateParamsNative.Dispose();
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.D3D11.CreateDLSSExt after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static NGXHandle CreateDLSSExt(nint pInCtx, NGXParameter pInParams, in NGXDLSSCreateParams pInDlssCreateParams)
        {
            NGXResult result = CreateDLSSExt(pInCtx, out NGXHandle ppOutHandle, pInParams, in pInDlssCreateParams);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.D3D11.CreateDLSSExt");
            }

            return ppOutHandle;
        }

        /// <summary>
        /// NGX_D3D11_EVALUATE_DLISP_EXT
        /// </summary>
        public static NGXResult EvaluateDLISPExt(nint pInCtx, NGXHandle pInHandle, NGXParameter pInParams, in NGXD3D11DLISPEvalParams pDlispEvalParams)
        {
            NativeCall? storage = new();
            NGXResult result = NGXResult.Fail;
            bool attached = false;
            bool returned = false;
            NGXD3D11DLISPEvalParamsNative pDlispEvalParamsNative = default;
            NGXD3D11DLISPEvalParamsNative* pDlispEvalParamsNativePointer = null;

            try
            {
                if (pInHandle.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(pInHandle));
                }

                if (pInParams.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(pInParams));
                }

                pDlispEvalParamsNative = new(in pDlispEvalParams);
                pDlispEvalParamsNativePointer = storage!.Take(ref pDlispEvalParamsNative);
                NgxLifetime.BeginParameters(pInParams.Value, "D3D11.EvaluateDLISPExt", storage!);
                attached = true;
                result = EvaluateDLISPExtNative(pInCtx, pInHandle.Value, pInParams.Value, pDlispEvalParamsNativePointer);
                returned = true;

                return result;
            }
            finally
            {
                if (attached)
                {
                    NgxLifetime.EndParameters(pInParams.Value, "D3D11.EvaluateDLISPExt", returned, result is NGXResult.Success, ref storage);
                }

                storage?.Dispose();
                pDlispEvalParamsNative.Dispose();
            }
        }

        /// <summary>
        /// NGX_D3D11_EVALUATE_DLSSD_EXT
        /// </summary>
        public static NGXResult EvaluateDLSSDExt(nint pInCtx, NGXHandle pInHandle, NGXParameter pInParams, in NGXD3D11DLSSDEvalParams pInDlssDEvalParams)
        {
            NativeCall? storage = new();
            NGXResult result = NGXResult.Fail;
            bool attached = false;
            bool returned = false;
            NGXD3D11DLSSDEvalParamsNative pInDlssDEvalParamsNative = default;
            NGXD3D11DLSSDEvalParamsNative* pInDlssDEvalParamsNativePointer = null;

            try
            {
                if (pInHandle.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(pInHandle));
                }

                if (pInParams.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(pInParams));
                }

                pInDlssDEvalParamsNative = new(in pInDlssDEvalParams);
                pInDlssDEvalParamsNativePointer = storage!.Take(ref pInDlssDEvalParamsNative);
                NgxLifetime.BeginParameters(pInParams.Value, "D3D11.EvaluateDLSSDExt", storage!);
                attached = true;
                result = EvaluateDLSSDExtNative(pInCtx, pInHandle.Value, pInParams.Value, pInDlssDEvalParamsNativePointer);
                returned = true;

                return result;
            }
            finally
            {
                if (attached)
                {
                    NgxLifetime.EndParameters(pInParams.Value, "D3D11.EvaluateDLSSDExt", returned, result is NGXResult.Success, ref storage);
                }

                storage?.Dispose();
                pInDlssDEvalParamsNative.Dispose();
            }
        }

        /// <summary>
        /// NGX_D3D11_EVALUATE_DLSS_EXT
        /// </summary>
        public static NGXResult EvaluateDLSSExt(nint pInCtx, NGXHandle pInHandle, NGXParameter pInParams, in NGXD3D11DLSSEvalParams pInDlssEvalParams)
        {
            NativeCall? storage = new();
            NGXResult result = NGXResult.Fail;
            bool attached = false;
            bool returned = false;
            NGXD3D11DLSSEvalParamsNative pInDlssEvalParamsNative = default;
            NGXD3D11DLSSEvalParamsNative* pInDlssEvalParamsNativePointer = null;

            try
            {
                if (pInHandle.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(pInHandle));
                }

                if (pInParams.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(pInParams));
                }

                pInDlssEvalParamsNative = new(in pInDlssEvalParams);
                pInDlssEvalParamsNativePointer = storage!.Take(ref pInDlssEvalParamsNative);
                NgxLifetime.BeginParameters(pInParams.Value, "D3D11.EvaluateDLSSExt", storage!);
                attached = true;
                result = EvaluateDLSSExtNative(pInCtx, pInHandle.Value, pInParams.Value, pInDlssEvalParamsNativePointer);
                returned = true;

                return result;
            }
            finally
            {
                if (attached)
                {
                    NgxLifetime.EndParameters(pInParams.Value, "D3D11.EvaluateDLSSExt", returned, result is NGXResult.Success, ref storage);
                }

                storage?.Dispose();
                pInDlssEvalParamsNative.Dispose();
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_AllocateParameters
        /// </summary>
        public static NGXResult AllocateParameters(out NGXParameter outParameters)
        {
            outParameters = default;
            nint outParametersNative = default;
            NgxLifetime.PrepareParameters();
            NGXResult result = AllocateParametersNative(&outParametersNative);
            if (result is NGXResult.Success)
            {
                outParameters = new(outParametersNative);
                NgxLifetime.RegisterParameters("D3D11", outParameters.Value);
            }

            return result;
        }

        /// <summary>
        /// Returns the outputs of Ngx.D3D11.AllocateParameters after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static NGXParameter AllocateParameters()
        {
            NGXResult result = AllocateParameters(out NGXParameter outParameters);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.D3D11.AllocateParameters");
            }

            return outParameters;
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_CreateFeature
        /// </summary>
        public static NGXResult CreateFeature(nint inDevCtx, NGXFeature inFeatureID, NGXParameter inParameters, out NGXHandle outHandle)
        {
            outHandle = default;
            nint outHandleNative = default;

            if (inParameters.IsNull)
            {
                throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameters));
            }

            NGXResult result = CreateFeatureNative(inDevCtx, inFeatureID, inParameters.Value, &outHandleNative);
            if (result is NGXResult.Success)
            {
                outHandle = new(outHandleNative);
            }

            return result;
        }

        /// <summary>
        /// Returns the outputs of Ngx.D3D11.CreateFeature after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static NGXHandle CreateFeature(nint inDevCtx, NGXFeature inFeatureID, NGXParameter inParameters)
        {
            NGXResult result = CreateFeature(inDevCtx, inFeatureID, inParameters, out NGXHandle outHandle);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.D3D11.CreateFeature");
            }

            return outHandle;
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_DestroyParameters
        /// </summary>
        public static NGXResult DestroyParameters(NGXParameter inParameters)
        {
            if (inParameters.IsNull)
            {
                throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameters));
            }

            NGXResult result = DestroyParametersNative(inParameters.Value);

            if (result is NGXResult.Success)
            {
                NgxLifetime.ReleaseParameters(inParameters.Value, destroyed: true);
            }

            return result;
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_EvaluateFeature
        /// </summary>
        public static NGXResult EvaluateFeature(nint inDevCtx, NGXHandle inFeatureHandle, NGXParameter inParameters, NGXPfnProgressCallback? inCallback)
        {
            nint inCallbackNative = 0;

            try
            {
                if (inFeatureHandle.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inFeatureHandle));
                }

                if (inParameters.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameters));
                }

                inCallbackNative = NgxCallbacks.Acquire(inCallback);
                NGXResult result = EvaluateFeatureNative(inDevCtx, inFeatureHandle.Value, inParameters.Value, inCallbackNative);

                return result;
            }
            finally
            {
                NgxCallbacks.Release(inCallbackNative);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_EvaluateFeature_C
        /// </summary>
        public static NGXResult EvaluateFeatureC(nint inDevCtx, NGXHandle inFeatureHandle, NGXParameter inParameters, NGXPfnProgressCallbackC? inCallback)
        {
            nint inCallbackNative = 0;

            try
            {
                if (inFeatureHandle.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inFeatureHandle));
                }

                if (inParameters.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameters));
                }

                inCallbackNative = NgxCallbacks.Acquire(inCallback);
                NGXResult result = EvaluateFeatureCNative(inDevCtx, inFeatureHandle.Value, inParameters.Value, inCallbackNative);

                return result;
            }
            finally
            {
                NgxCallbacks.Release(inCallbackNative);
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_GetCapabilityParameters
        /// </summary>
        public static NGXResult GetCapabilityParameters(out NGXParameter outParameters)
        {
            outParameters = default;
            nint outParametersNative = default;
            NgxLifetime.PrepareParameters();
            NGXResult result = GetCapabilityParametersNative(&outParametersNative);
            if (result is NGXResult.Success)
            {
                outParameters = new(outParametersNative);
                NgxLifetime.RegisterParameters("D3D11", outParameters.Value);
            }

            return result;
        }

        /// <summary>
        /// Returns the outputs of Ngx.D3D11.GetCapabilityParameters after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static NGXParameter GetCapabilityParameters()
        {
            NGXResult result = GetCapabilityParameters(out NGXParameter outParameters);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.D3D11.GetCapabilityParameters");
            }

            return outParameters;
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_GetFeatureRequirements
        /// </summary>
        public static NGXResult GetFeatureRequirements(nint adapter, in NGXFeatureDiscoveryInfo featureDiscoveryInfo, out NGXFeatureRequirement outSupported)
        {
            NGXFeatureDiscoveryInfoNative featureDiscoveryInfoNative = default;
            NGXFeatureRequirementNative outSupportedNative = default;
            outSupported = default;

            try
            {
                featureDiscoveryInfoNative = new(in featureDiscoveryInfo);
                NGXResult result = GetFeatureRequirementsNative(adapter, &featureDiscoveryInfoNative, &outSupportedNative);
                if (result is NGXResult.Success)
                {
                    outSupported = new(in outSupportedNative);
                }

                return result;
            }
            finally
            {
                featureDiscoveryInfoNative.Dispose();
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.D3D11.GetFeatureRequirements after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static NGXFeatureRequirement GetFeatureRequirements(nint adapter, in NGXFeatureDiscoveryInfo featureDiscoveryInfo)
        {
            NGXResult result = GetFeatureRequirements(adapter, in featureDiscoveryInfo, out NGXFeatureRequirement outSupported);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.D3D11.GetFeatureRequirements");
            }

            return outSupported;
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_GetParameters
        /// </summary>
        public static NGXResult GetParameters(out NGXParameter outParameters)
        {
            outParameters = default;
            nint outParametersNative = default;
            NgxLifetime.PrepareParameters();
            NGXResult result = GetParametersNative(&outParametersNative);
            if (result is NGXResult.Success)
            {
                outParameters = new(outParametersNative);
                NgxLifetime.RegisterParameters("D3D11", outParameters.Value);
            }

            return result;
        }

        /// <summary>
        /// Returns the outputs of Ngx.D3D11.GetParameters after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static NGXParameter GetParameters()
        {
            NGXResult result = GetParameters(out NGXParameter outParameters);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.D3D11.GetParameters");
            }

            return outParameters;
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_GetScratchBufferSize
        /// </summary>
        public static NGXResult GetScratchBufferSize(NGXFeature inFeatureId, NGXParameter inParameters, out nuint outSizeInBytes)
        {
            outSizeInBytes = default;
            nuint outSizeInBytesNative = default;

            if (inParameters.IsNull)
            {
                throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameters));
            }

            NGXResult result = GetScratchBufferSizeNative(inFeatureId, inParameters.Value, &outSizeInBytesNative);
            if (result is NGXResult.Success)
            {
                outSizeInBytes = outSizeInBytesNative;
            }

            return result;
        }

        /// <summary>
        /// Returns the outputs of Ngx.D3D11.GetScratchBufferSize after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static nuint GetScratchBufferSize(NGXFeature inFeatureId, NGXParameter inParameters)
        {
            NGXResult result = GetScratchBufferSize(inFeatureId, inParameters, out nuint outSizeInBytes);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.D3D11.GetScratchBufferSize");
            }

            return outSizeInBytes;
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_Init
        /// </summary>
        public static NGXResult Init(ulong inApplicationId, string? inApplicationDataPath, nint inDevice, NGXFeatureCommonInfo? inFeatureInfo, NGXVersion inSDKVersion)
        {
            NativeCall? storage = new();
            NGXResult result = NGXResult.Fail;
            bool attached = false;
            bool returned = false;
            void* inApplicationDataPathNative = null;
            NGXFeatureCommonInfoNative inFeatureInfoNative = default;
            NGXFeatureCommonInfoNative* inFeatureInfoNativePointer = null;

            try
            {
                inApplicationDataPathNative = (void*)storage!.String(inApplicationDataPath, NGXEncoding.NativeWide);

                if (inFeatureInfo is NGXFeatureCommonInfo inFeatureInfoValue)
                {
                    inFeatureInfoNative = new(in inFeatureInfoValue);
                }

                inFeatureInfoNativePointer = inFeatureInfo.HasValue ? storage!.Take(ref inFeatureInfoNative) : null;
                NgxLifetime.BeginInitialization("D3D11", inDevice, storage!);
                attached = true;
                result = InitNative(inApplicationId, inApplicationDataPathNative, inDevice, inFeatureInfoNativePointer, inSDKVersion);
                returned = true;

                return result;
            }
            finally
            {
                if (attached)
                {
                    NgxLifetime.EndInitialization("D3D11", inDevice, returned && result is NGXResult.Success, ref storage);
                }

                storage?.Dispose();
                inFeatureInfoNative.Dispose();
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_Init. Overload for a present optional structure.
        /// </summary>
        public static NGXResult Init(ulong inApplicationId, string? inApplicationDataPath, nint inDevice, in NGXFeatureCommonInfo inFeatureInfo, NGXVersion inSDKVersion)
        {
            return Init(inApplicationId, inApplicationDataPath, inDevice, (NGXFeatureCommonInfo?)inFeatureInfo, inSDKVersion);
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_Init_with_ProjectID
        /// </summary>
        public static NGXResult InitWithProjectID(string? inProjectId, NGXEngineType inEngineType, string? inEngineVersion, string? inApplicationDataPath, nint inDevice, NGXFeatureCommonInfo? inFeatureInfo, NGXVersion inSDKVersion)
        {
            NativeCall? storage = new();
            NGXResult result = NGXResult.Fail;
            bool attached = false;
            bool returned = false;
            sbyte* inProjectIdNative = null;
            sbyte* inEngineVersionNative = null;
            void* inApplicationDataPathNative = null;
            NGXFeatureCommonInfoNative inFeatureInfoNative = default;
            NGXFeatureCommonInfoNative* inFeatureInfoNativePointer = null;

            try
            {
                inProjectIdNative = (sbyte*)storage!.String(inProjectId, NGXEncoding.Utf8);
                inEngineVersionNative = (sbyte*)storage!.String(inEngineVersion, NGXEncoding.Utf8);
                inApplicationDataPathNative = (void*)storage!.String(inApplicationDataPath, NGXEncoding.NativeWide);

                if (inFeatureInfo is NGXFeatureCommonInfo inFeatureInfoValue)
                {
                    inFeatureInfoNative = new(in inFeatureInfoValue);
                }

                inFeatureInfoNativePointer = inFeatureInfo.HasValue ? storage!.Take(ref inFeatureInfoNative) : null;
                NgxLifetime.BeginInitialization("D3D11", inDevice, storage!);
                attached = true;
                result = InitWithProjectIDNative(inProjectIdNative, inEngineType, inEngineVersionNative, inApplicationDataPathNative, inDevice, inFeatureInfoNativePointer, inSDKVersion);
                returned = true;

                return result;
            }
            finally
            {
                if (attached)
                {
                    NgxLifetime.EndInitialization("D3D11", inDevice, returned && result is NGXResult.Success, ref storage);
                }

                storage?.Dispose();
                inFeatureInfoNative.Dispose();
            }
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_Init_with_ProjectID. Overload for a present optional structure.
        /// </summary>
        public static NGXResult InitWithProjectID(string? inProjectId, NGXEngineType inEngineType, string? inEngineVersion, string? inApplicationDataPath, nint inDevice, in NGXFeatureCommonInfo inFeatureInfo, NGXVersion inSDKVersion)
        {
            return InitWithProjectID(inProjectId, inEngineType, inEngineVersion, inApplicationDataPath, inDevice, (NGXFeatureCommonInfo?)inFeatureInfo, inSDKVersion);
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_ReleaseFeature
        /// </summary>
        public static NGXResult ReleaseFeature(NGXHandle inHandle)
        {
            if (inHandle.IsNull)
            {
                throw new ArgumentException("A non-null NGX handle is required.", nameof(inHandle));
            }

            NGXResult result = ReleaseFeatureNative(inHandle.Value);

            return result;
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_Shutdown
        /// </summary>
        public static NGXResult Shutdown()
        {
            NGXResult result = ShutdownNative();

            if (result is NGXResult.Success)
            {
                NgxLifetime.Shutdown("D3D11", 0);
            }

            return result;
        }

        /// <summary>
        /// NVSDK_NGX_D3D11_Shutdown1
        /// </summary>
        public static NGXResult Shutdown1(nint inDevice)
        {
            NGXResult result = Shutdown1Native(inDevice);

            if (result is NGXResult.Success)
            {
                NgxLifetime.Shutdown("D3D11", inDevice);
            }

            return result;
        }
    }
}
