// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

public static unsafe partial class NGX
{
    /// <summary>
    /// Parameter application API and native inline helpers.
    /// </summary>
    public static partial class Parameter
    {
        /// <summary>
        /// NVSDK_NGX_Parameter_GetD. Source: nvsdk_ngx_params.h:100.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetD")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetD(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, double* @OutValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_GetD.
        /// </summary>
        public static global::NGX.NET.Result GetD(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, out double value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            value = default;
            fixed (double* output = &value)
            fixed (byte* key = terminated)
            {
                return GetD(parameters, (sbyte*)key, output);
            }
        }

        /// <summary>
        /// Returns a typed parameter value and throws on NGX failure.
        /// </summary>
        public static double GetD(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name)
        {
            ThrowIfFailed(GetD(parameters, name, out double value), "NVSDK_NGX_Parameter_GetD");

            return value;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetD3d11Resource. Source: nvsdk_ngx_params.h:106.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetD3d11Resource")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetD3d11Resource(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, nint* @OutValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_GetD3d11Resource.
        /// </summary>
        public static global::NGX.NET.Result GetD3d11Resource(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, out nint value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            value = default;
            fixed (nint* output = &value)
            fixed (byte* key = terminated)
            {
                return GetD3d11Resource(parameters, (sbyte*)key, output);
            }
        }

        /// <summary>
        /// Returns a typed parameter value and throws on NGX failure.
        /// </summary>
        public static nint GetD3d11Resource(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name)
        {
            ThrowIfFailed(GetD3d11Resource(parameters, name, out nint value), "NVSDK_NGX_Parameter_GetD3d11Resource");

            return value;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetD3d12Resource. Source: nvsdk_ngx_params.h:108.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetD3d12Resource")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetD3d12Resource(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, nint* @OutValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_GetD3d12Resource.
        /// </summary>
        public static global::NGX.NET.Result GetD3d12Resource(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, out nint value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            value = default;
            fixed (nint* output = &value)
            fixed (byte* key = terminated)
            {
                return GetD3d12Resource(parameters, (sbyte*)key, output);
            }
        }

        /// <summary>
        /// Returns a typed parameter value and throws on NGX failure.
        /// </summary>
        public static nint GetD3d12Resource(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name)
        {
            ThrowIfFailed(GetD3d12Resource(parameters, name, out nint value), "NVSDK_NGX_Parameter_GetD3d12Resource");

            return value;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetF. Source: nvsdk_ngx_params.h:98.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetF")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetF(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, float* @OutValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_GetF.
        /// </summary>
        public static global::NGX.NET.Result GetF(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, out float value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            value = default;
            fixed (float* output = &value)
            fixed (byte* key = terminated)
            {
                return GetF(parameters, (sbyte*)key, output);
            }
        }

        /// <summary>
        /// Returns a typed parameter value and throws on NGX failure.
        /// </summary>
        public static float GetF(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name)
        {
            ThrowIfFailed(GetF(parameters, name, out float value), "NVSDK_NGX_Parameter_GetF");

            return value;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetI. Source: nvsdk_ngx_params.h:104.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetI")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetI(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, int* @OutValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_GetI.
        /// </summary>
        public static global::NGX.NET.Result GetI(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, out int value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            value = default;
            fixed (int* output = &value)
            fixed (byte* key = terminated)
            {
                return GetI(parameters, (sbyte*)key, output);
            }
        }

        /// <summary>
        /// Returns a typed parameter value and throws on NGX failure.
        /// </summary>
        public static int GetI(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name)
        {
            ThrowIfFailed(GetI(parameters, name, out int value), "NVSDK_NGX_Parameter_GetI");

            return value;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetUI. Source: nvsdk_ngx_params.h:102.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetUI")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetUI(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, uint* @OutValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_GetUI.
        /// </summary>
        public static global::NGX.NET.Result GetUI(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, out uint value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            value = default;
            fixed (uint* output = &value)
            fixed (byte* key = terminated)
            {
                return GetUI(parameters, (sbyte*)key, output);
            }
        }

        /// <summary>
        /// Returns a typed parameter value and throws on NGX failure.
        /// </summary>
        public static uint GetUI(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name)
        {
            ThrowIfFailed(GetUI(parameters, name, out uint value), "NVSDK_NGX_Parameter_GetUI");

            return value;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetULL. Source: nvsdk_ngx_params.h:96.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetULL")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetULL(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, ulong* @OutValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_GetULL.
        /// </summary>
        public static global::NGX.NET.Result GetULL(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, out ulong value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            value = default;
            fixed (ulong* output = &value)
            fixed (byte* key = terminated)
            {
                return GetULL(parameters, (sbyte*)key, output);
            }
        }

        /// <summary>
        /// Returns a typed parameter value and throws on NGX failure.
        /// </summary>
        public static ulong GetULL(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name)
        {
            ThrowIfFailed(GetULL(parameters, name, out ulong value), "NVSDK_NGX_Parameter_GetULL");

            return value;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetVoidPointer. Source: nvsdk_ngx_params.h:110.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetVoidPointer")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial global::NGX.NET.Result GetVoidPointer(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, void** @OutValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_GetVoidPointer.
        /// </summary>
        public static global::NGX.NET.Result GetVoidPointer(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, out void* value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            value = default;
            fixed (void** output = &value)
            fixed (byte* key = terminated)
            {
                return GetVoidPointer(parameters, (sbyte*)key, output);
            }
        }

        /// <summary>
        /// Returns a typed parameter value and throws on NGX failure.
        /// </summary>
        public static void* GetVoidPointer(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name)
        {
            ThrowIfFailed(GetVoidPointer(parameters, name, out void* value), "NVSDK_NGX_Parameter_GetVoidPointer");

            return value;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetD. Source: nvsdk_ngx_params.h:84.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetD")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial void SetD(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, double @InValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_SetD.
        /// </summary>
        public static void SetD(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, double value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            fixed (byte* key = terminated)
            {
                SetD(parameters, (sbyte*)key, value);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetD3d11Resource. Source: nvsdk_ngx_params.h:90.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetD3d11Resource")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial void SetD3d11Resource(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, nint @InValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_SetD3d11Resource.
        /// </summary>
        public static void SetD3d11Resource(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, nint value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            fixed (byte* key = terminated)
            {
                SetD3d11Resource(parameters, (sbyte*)key, value);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetD3d12Resource. Source: nvsdk_ngx_params.h:92.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetD3d12Resource")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial void SetD3d12Resource(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, nint @InValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_SetD3d12Resource.
        /// </summary>
        public static void SetD3d12Resource(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, nint value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            fixed (byte* key = terminated)
            {
                SetD3d12Resource(parameters, (sbyte*)key, value);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetF. Source: nvsdk_ngx_params.h:82.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetF")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial void SetF(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, float @InValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_SetF.
        /// </summary>
        public static void SetF(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, float value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            fixed (byte* key = terminated)
            {
                SetF(parameters, (sbyte*)key, value);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetI. Source: nvsdk_ngx_params.h:88.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetI")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial void SetI(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, int @InValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_SetI.
        /// </summary>
        public static void SetI(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, int value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            fixed (byte* key = terminated)
            {
                SetI(parameters, (sbyte*)key, value);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetUI. Source: nvsdk_ngx_params.h:86.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetUI")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial void SetUI(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, uint @InValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_SetUI.
        /// </summary>
        public static void SetUI(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, uint value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            fixed (byte* key = terminated)
            {
                SetUI(parameters, (sbyte*)key, value);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetULL. Source: nvsdk_ngx_params.h:80.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetULL")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial void SetULL(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, ulong @InValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_SetULL.
        /// </summary>
        public static void SetULL(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, ulong value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            fixed (byte* key = terminated)
            {
                SetULL(parameters, (sbyte*)key, value);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetVoidPointer. Source: nvsdk_ngx_params.h:94.
        /// </summary>
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetVoidPointer")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        public static partial void SetVoidPointer(global::NGX.NET.Parameter* @InParameter, sbyte* @InName, void* @InValue);

        /// <summary>
        /// Uses a UTF-8 parameter name with NVSDK_NGX_Parameter_SetVoidPointer.
        /// </summary>
        public static void SetVoidPointer(global::NGX.NET.Parameter* parameters, ReadOnlySpan<byte> name, void* value)
        {
            byte[] terminated = new byte[name.Length + 1];
            name.CopyTo(terminated);
            fixed (byte* key = terminated)
            {
                SetVoidPointer(parameters, (sbyte*)key, value);
            }
        }

    }
}
