// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

public static unsafe partial class Ngx
{
    /// <summary>
    /// Parameter application API and native helpers.
    /// </summary>
    public static partial class Parameter
    {
        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetD")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetDNative(nint inParameter, sbyte* inName, double* outValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetD3d11Resource")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetD3d11ResourceNative(nint inParameter, sbyte* inName, nint* outValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetD3d12Resource")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetD3d12ResourceNative(nint inParameter, sbyte* inName, nint* outValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetF")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetFNative(nint inParameter, sbyte* inName, float* outValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetI")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetINative(nint inParameter, sbyte* inName, int* outValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetUI")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetUINative(nint inParameter, sbyte* inName, uint* outValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetULL")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetULLNative(nint inParameter, sbyte* inName, ulong* outValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_GetVoidPointer")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial NGXResult GetVoidPointerNative(nint inParameter, sbyte* inName, void** outValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetD")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial void SetDNative(nint inParameter, sbyte* inName, double inValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetD3d11Resource")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial void SetD3d11ResourceNative(nint inParameter, sbyte* inName, nint inValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetD3d12Resource")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial void SetD3d12ResourceNative(nint inParameter, sbyte* inName, nint inValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetF")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial void SetFNative(nint inParameter, sbyte* inName, float inValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetI")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial void SetINative(nint inParameter, sbyte* inName, int inValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetUI")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial void SetUINative(nint inParameter, sbyte* inName, uint inValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetULL")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial void SetULLNative(nint inParameter, sbyte* inName, ulong inValue);

        [LibraryImport(LibraryName, EntryPoint = "NVSDK_NGX_Parameter_SetVoidPointer")]
        [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
        private static partial void SetVoidPointerNative(nint inParameter, sbyte* inName, void* inValue);

        static Parameter()
        {
            RuntimeHelpers.RunClassConstructor(typeof(Ngx).TypeHandle);
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetD
        /// </summary>
        public static NGXResult GetD(NGXParameter inParameter, string inName, out double outValue)
        {
            sbyte* inNameNative = null;
            outValue = default;
            double outValueNative = default;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                NGXResult result = GetDNative(inParameter.Value, inNameNative, &outValueNative);
                if (result is NGXResult.Success)
                {
                    outValue = outValueNative;
                }

                return result;
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.Parameter.GetD after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static double GetD(NGXParameter inParameter, string inName)
        {
            NGXResult result = GetD(inParameter, inName, out double outValue);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.Parameter.GetD");
            }

            return outValue;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetD3d11Resource
        /// </summary>
        public static NGXResult GetD3d11Resource(NGXParameter inParameter, string inName, out nint outValue)
        {
            sbyte* inNameNative = null;
            outValue = default;
            nint outValueNative = default;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                NGXResult result = GetD3d11ResourceNative(inParameter.Value, inNameNative, &outValueNative);
                if (result is NGXResult.Success)
                {
                    outValue = (nint)outValueNative;
                }

                return result;
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.Parameter.GetD3d11Resource after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static nint GetD3d11Resource(NGXParameter inParameter, string inName)
        {
            NGXResult result = GetD3d11Resource(inParameter, inName, out nint outValue);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.Parameter.GetD3d11Resource");
            }

            return outValue;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetD3d12Resource
        /// </summary>
        public static NGXResult GetD3d12Resource(NGXParameter inParameter, string inName, out nint outValue)
        {
            sbyte* inNameNative = null;
            outValue = default;
            nint outValueNative = default;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                NGXResult result = GetD3d12ResourceNative(inParameter.Value, inNameNative, &outValueNative);
                if (result is NGXResult.Success)
                {
                    outValue = (nint)outValueNative;
                }

                return result;
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.Parameter.GetD3d12Resource after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static nint GetD3d12Resource(NGXParameter inParameter, string inName)
        {
            NGXResult result = GetD3d12Resource(inParameter, inName, out nint outValue);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.Parameter.GetD3d12Resource");
            }

            return outValue;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetF
        /// </summary>
        public static NGXResult GetF(NGXParameter inParameter, string inName, out float outValue)
        {
            sbyte* inNameNative = null;
            outValue = default;
            float outValueNative = default;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                NGXResult result = GetFNative(inParameter.Value, inNameNative, &outValueNative);
                if (result is NGXResult.Success)
                {
                    outValue = outValueNative;
                }

                return result;
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.Parameter.GetF after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static float GetF(NGXParameter inParameter, string inName)
        {
            NGXResult result = GetF(inParameter, inName, out float outValue);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.Parameter.GetF");
            }

            return outValue;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetI
        /// </summary>
        public static NGXResult GetI(NGXParameter inParameter, string inName, out int outValue)
        {
            sbyte* inNameNative = null;
            outValue = default;
            int outValueNative = default;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                NGXResult result = GetINative(inParameter.Value, inNameNative, &outValueNative);
                if (result is NGXResult.Success)
                {
                    outValue = outValueNative;
                }

                return result;
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.Parameter.GetI after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static int GetI(NGXParameter inParameter, string inName)
        {
            NGXResult result = GetI(inParameter, inName, out int outValue);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.Parameter.GetI");
            }

            return outValue;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetUI
        /// </summary>
        public static NGXResult GetUI(NGXParameter inParameter, string inName, out uint outValue)
        {
            sbyte* inNameNative = null;
            outValue = default;
            uint outValueNative = default;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                NGXResult result = GetUINative(inParameter.Value, inNameNative, &outValueNative);
                if (result is NGXResult.Success)
                {
                    outValue = outValueNative;
                }

                return result;
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.Parameter.GetUI after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static uint GetUI(NGXParameter inParameter, string inName)
        {
            NGXResult result = GetUI(inParameter, inName, out uint outValue);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.Parameter.GetUI");
            }

            return outValue;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetULL
        /// </summary>
        public static NGXResult GetULL(NGXParameter inParameter, string inName, out ulong outValue)
        {
            sbyte* inNameNative = null;
            outValue = default;
            ulong outValueNative = default;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                NGXResult result = GetULLNative(inParameter.Value, inNameNative, &outValueNative);
                if (result is NGXResult.Success)
                {
                    outValue = outValueNative;
                }

                return result;
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.Parameter.GetULL after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static ulong GetULL(NGXParameter inParameter, string inName)
        {
            NGXResult result = GetULL(inParameter, inName, out ulong outValue);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.Parameter.GetULL");
            }

            return outValue;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_GetVoidPointer
        /// </summary>
        public static NGXResult GetVoidPointer(NGXParameter inParameter, string inName, out nint outValue)
        {
            sbyte* inNameNative = null;
            outValue = default;
            void* outValueNative = default;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                NGXResult result = GetVoidPointerNative(inParameter.Value, inNameNative, &outValueNative);
                if (result is NGXResult.Success)
                {
                    outValue = (nint)outValueNative;
                }

                return result;
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// Returns the outputs of Ngx.Parameter.GetVoidPointer after checking the NGX result.
        /// </summary>
        /// <exception cref="NGXException">The NGX operation failed.</exception>
        public static nint GetVoidPointer(NGXParameter inParameter, string inName)
        {
            NGXResult result = GetVoidPointer(inParameter, inName, out nint outValue);
            if (result is not NGXResult.Success)
            {
                throw new NGXException(result, "Ngx.Parameter.GetVoidPointer");
            }

            return outValue;
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetD
        /// </summary>
        public static void SetD(NGXParameter inParameter, string inName, double inValue)
        {
            sbyte* inNameNative = null;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                SetDNative(inParameter.Value, inNameNative, inValue);
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetD3d11Resource
        /// </summary>
        public static void SetD3d11Resource(NGXParameter inParameter, string inName, nint inValue)
        {
            sbyte* inNameNative = null;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                SetD3d11ResourceNative(inParameter.Value, inNameNative, inValue);
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetD3d12Resource
        /// </summary>
        public static void SetD3d12Resource(NGXParameter inParameter, string inName, nint inValue)
        {
            sbyte* inNameNative = null;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                SetD3d12ResourceNative(inParameter.Value, inNameNative, inValue);
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetF
        /// </summary>
        public static void SetF(NGXParameter inParameter, string inName, float inValue)
        {
            sbyte* inNameNative = null;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                SetFNative(inParameter.Value, inNameNative, inValue);
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetI
        /// </summary>
        public static void SetI(NGXParameter inParameter, string inName, int inValue)
        {
            sbyte* inNameNative = null;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                SetINative(inParameter.Value, inNameNative, inValue);
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetUI
        /// </summary>
        public static void SetUI(NGXParameter inParameter, string inName, uint inValue)
        {
            sbyte* inNameNative = null;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                SetUINative(inParameter.Value, inNameNative, inValue);
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetULL
        /// </summary>
        public static void SetULL(NGXParameter inParameter, string inName, ulong inValue)
        {
            sbyte* inNameNative = null;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                SetULLNative(inParameter.Value, inNameNative, inValue);
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }

        /// <summary>
        /// NVSDK_NGX_Parameter_SetVoidPointer
        /// </summary>
        public static void SetVoidPointer(NGXParameter inParameter, string inName, nint inValue)
        {
            sbyte* inNameNative = null;

            try
            {
                if (inParameter.IsNull)
                {
                    throw new ArgumentException("A non-null NGX handle is required.", nameof(inParameter));
                }

                ArgumentNullException.ThrowIfNull(inName);
                inNameNative = (sbyte*)NGXMarshal.StringToPtr(inName, NGXEncoding.Utf8);
                SetVoidPointerNative(inParameter.Value, inNameNative, (void*)inValue);
            }
            finally
            {
                NGXMarshal.Free(inNameNative);
            }
        }
    }
}
