namespace NGX.NET.Generator;

internal class CodeWriter
{
    private readonly StringBuilder text = new();

    private int indent;
    private bool blankLine;
    private bool blockStart;

    public override string ToString()
    {
        return text.ToString();
    }

    internal void Line(string value)
    {
        if (blankLine && text.Length is not 0)
        {
            text.Append('\n');
        }

        blankLine = false;
        blockStart = false;
        text.Append(' ', indent * 4);
        text.Append(value);
        text.Append('\n');
    }

    internal void BlankLine()
    {
        blankLine = !blockStart;
    }

    internal void BeginBlock(string declaration, bool continuation = false)
    {
        if (continuation)
        {
            blankLine = false;
        }

        Line(declaration);
        Line("{");
        indent++;
        blockStart = true;
    }

    internal void EndBlock(string suffix = "")
    {
        blankLine = false;
        indent--;
        Line("}" + suffix);
        BlankLine();
    }

    internal static void WriteGuard(CodeWriter text, string condition, string statement)
    {
        text.BlankLine();
        text.BeginBlock($"if ({condition})");
        text.Line(statement);
        text.EndBlock();
    }

    internal static string Escape(string value)
    {
        return SecurityElement.Escape(value)!;
    }

    internal static CodeWriter CreateFile(params ReadOnlySpan<string> imports)
    {
        CodeWriter text = new();
        text.Line("// <auto-generated/>");
        text.Line("// Generated by NGX.NET.Generator. Changes belong in the generator.");
        text.BlankLine();
        text.Line("#nullable enable");
        text.BlankLine();

        foreach (string import in imports)
        {
            text.Line($"using {import};");
        }

        text.BlankLine();
        text.Line("namespace NGX.NET;");
        text.BlankLine();

        return text;
    }

    internal static void WriteSummary(CodeWriter text, string summary)
    {
        text.Line("/// <summary>");
        text.Line($"/// {Escape(summary)}");
        text.Line("/// </summary>");
    }
}
