using System.Globalization;
using System.Security;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace NGX.NET.Generator;

internal sealed partial class Emitter
{
    private readonly JsonElement[] platforms;
    private readonly Dictionary<string, JsonElement> records;
    private readonly Dictionary<string, JsonElement> enums;
    private readonly Dictionary<string, JsonElement> functions;
    private readonly Dictionary<string, string> files = [];
    private readonly Dictionary<string, string> unionNames = [];
    private const string Header = "// <auto-generated/>\n// Generated by NGX.NET.Generator. Changes belong in the generator.\n\n";
    private const string Namespace = "namespace NGX.NET;\n\n";

    // Reviewed SDK ownership/output contracts. New declarations retain their
    // raw binding until their convenience result has been explicitly reviewed.
    private static readonly HashSet<string> OutputContracts =
    [
        "NGX_CUDA_CREATE_DLISP_EXT",
        "NGX_CUDA_CREATE_DLSSD_EXT",
        "NGX_CUDA_CREATE_DLSSD_EXT1",
        "NGX_D3D11_CREATE_DLISP_EXT",
        "NGX_D3D11_CREATE_DLSSD_EXT",
        "NGX_D3D11_CREATE_DLSS_EXT",
        "NGX_D3D12_CREATE_DLISP_EXT",
        "NGX_D3D12_CREATE_DLSSD_EXT",
        "NGX_D3D12_CREATE_DLSSG",
        "NGX_D3D12_CREATE_DLSS_EXT",
        "NGX_VK_CREATE_DLSSG",
        "NGX_VULKAN_CREATE_DLISP_EXT",
        "NGX_VULKAN_CREATE_DLSSD_EXT1",
        "NGX_VULKAN_CREATE_DLSS_EXT",
        "NGX_VULKAN_CREATE_DLSS_EXT1",
        "NVSDK_NGX_CUDA_AllocateParameters",
        "NVSDK_NGX_CUDA_CreateFeature",
        "NVSDK_NGX_CUDA_CreateFeature1",
        "NVSDK_NGX_CUDA_GetCapabilityParameters",
        "NVSDK_NGX_CUDA_GetScratchBufferSize",
        "NVSDK_NGX_D3D11_AllocateParameters",
        "NVSDK_NGX_D3D11_CreateFeature",
        "NVSDK_NGX_D3D11_GetCapabilityParameters",
        "NVSDK_NGX_D3D11_GetScratchBufferSize",
        "NVSDK_NGX_D3D12_AllocateParameters",
        "NVSDK_NGX_D3D12_CreateFeature",
        "NVSDK_NGX_D3D12_GetCapabilityParameters",
        "NVSDK_NGX_D3D12_GetScratchBufferSize",
        "NVSDK_NGX_VULKAN_AllocateParameters",
        "NVSDK_NGX_VULKAN_CreateFeature",
        "NVSDK_NGX_VULKAN_CreateFeature1",
        "NVSDK_NGX_VULKAN_GetCapabilityParameters",
        "NVSDK_NGX_VULKAN_GetScratchBufferSize"
    ];

    public Emitter(JsonElement ast)
    {
        platforms = [.. ast.GetProperty("platforms").EnumerateObject().Select(p => p.Value)];
        records = Merge("records");
        enums = Merge("enums");
        functions = Merge("functions");

        foreach (JsonElement parent in records.Values)
        {
            foreach (JsonElement field in parent.Items("fields"))
            {
                JsonElement type = field.GetProperty("type");

                if (type.Text("kind") == "RECORD" && records[type.Text("name")].Text("kind") == "UNION_DECL")
                {
                    unionNames[type.Text("name")] = TypeName(parent.Text("name")) + "Union";
                }
            }
        }
    }

    private Dictionary<string, JsonElement> Merge(string key) => platforms.SelectMany(p => p.Items(key)).GroupBy(e => e.Text("name")).ToDictionary(g => g.Key, g => g.First());

    public Dictionary<string, string> Generate()
    {
        ValidateLayouts();

        foreach ((string name, JsonElement value) in enums)
        {
            WriteEnum(name, value);
        }

        foreach ((string name, JsonElement value) in records)
        {
            WriteRecord(name, value);
        }

        foreach (IGrouping<string, JsonElement> group in functions.Values.GroupBy(f => FunctionName(f.Text("name")).Group))
        {
            WriteFunctions(group.Key, group);
        }

        WriteCallbacks();
        WriteConstants();

        return files;
    }

    private void ValidateLayouts()
    {
        foreach (JsonElement platform in platforms)
        {
            foreach (JsonElement record in platform.Items("records"))
            {
                JsonElement shared = records[record.Text("name")];

                if (record.Number("size") != shared.Number("size") || record.Number("align") != shared.Number("align") || !record.Items("fields").Select(f => (f.Text("name"), f.Number("offset"))).SequenceEqual(shared.Items("fields").Select(f => (f.Text("name"), f.Number("offset")))))
                {
                    throw new InvalidOperationException("A platform-specific layout requires review: " + record.Text("name"));
                }
            }

            foreach (JsonElement function in platform.Items("functions"))
            {
                JsonElement shared = functions[function.Text("name")];

                if (Type(function.GetProperty("result")) != Type(shared.GetProperty("result")) || !function.Items("parameters").Select(p => Type(p.GetProperty("type"))).SequenceEqual(shared.Items("parameters").Select(p => Type(p.GetProperty("type")))))
                {
                    throw new InvalidOperationException("A platform-specific function signature requires review: " + function.Text("name"));
                }
            }
        }
    }

    private void WriteCallbacks()
    {
        Dictionary<string, JsonElement> aliases = platforms.SelectMany(p => p.GetProperty("aliases").EnumerateObject()).GroupBy(p => p.Name).ToDictionary(g => g.Key, g => g.First().Value);

        foreach ((string native, JsonElement type) in aliases)
        {
            if (type.Text("kind") != "POINTER" || type.GetProperty("element").Text("kind") != "FUNCTIONPROTO")
            {
                continue;
            }

            string name = TypeName(native);
            string pointer = Type(type);
            files[$"Callbacks/{name}.g.cs"] = Header + "using System.Runtime.InteropServices;\n\n" + Namespace + Summary(native + ". Keep callback code alive while NGX retains it; never let managed exceptions cross this ABI.") +
                $"[NGXNativeName(\"{native}\")]\n[StructLayout(LayoutKind.Sequential)]\npublic readonly unsafe struct {name}({pointer} pointer)\n{{\n" +
                Summary("Native C callback pointer. C++ reference parameters use their pointer ABI.", 4) +
                $"    public readonly {pointer} Pointer = pointer;\n}}\n";
        }
    }

    private static string Escape(string value) => SecurityElement.Escape(value)!;

    private static string Summary(string text, int indent = 0)
    {
        string spaces = new(' ', indent);

        return $"{spaces}/// <summary>\n{spaces}/// {Escape(text)}\n{spaces}/// </summary>\n";
    }

    internal static string Name(string name)
    {
        name = name.Replace("NVSDK_NGX_", "", StringComparison.Ordinal);
        HashSet<string> acronyms = ["NGX", "DLSS", "DLSSD", "DLSSG", "DLAA", "DLISP", "CUDA", "D3D11", "D3D12", "VK", "UI", "ULL", "F", "D", "I", "API", "HDR", "SR", "RR", "RW", "VRAM"];

        return string.Concat(name.Split('_', StringSplitOptions.RemoveEmptyEntries).Select(p => acronyms.Contains(p) || p.Any(char.IsLower) ? char.ToUpperInvariant(p[0]) + p[1..] : CultureInfo.InvariantCulture.TextInfo.ToTitleCase(p.ToLowerInvariant())));
    }

    private static string TypeName(string native)
    {
        string name = Name(native);

        return name.StartsWith("NGX", StringComparison.Ordinal) ? name : "NGX" + name;
    }

    // PascalCase names cannot collide with C#'s lowercase keywords.
    private static string FieldName(string name) => name == "v" ? "V" : Name(name);

    private static (string Group, string Method) FunctionName(string native)
    {
        if (native == "GetNGXResultAsString")
        {
            return ("", "GetResultAsString");
        }

        string name = native.StartsWith("NVSDK_NGX_", StringComparison.Ordinal) ? native[10..] : native[4..];

        foreach (string prefix in new[] { "D3D11", "D3D12", "CUDA", "VULKAN", "VK", "Parameter", "DLSSD", "DLSS" })
        {
            if (name.StartsWith(prefix + "_", StringComparison.Ordinal))
            {
                return (prefix is "VULKAN" or "VK" ? "Vulkan" : prefix, Name(name[(prefix.Length + 1)..]));
            }
        }

        return ("", Name(name));
    }

    private string Type(JsonElement type)
    {
        string kind = type.Text("kind");
        string cpp = type.Text("cpp").Replace("const ", "", StringComparison.Ordinal).Trim();

        if (cpp == "size_t")
        {
            return "nuint";
        }

        if (cpp == "size_t *")
        {
            return "nuint*";
        }

        if (kind is "POINTER" or "LVALUEREFERENCE" or "RVALUEREFERENCE")
        {
            JsonElement element = type.GetProperty("element");
            string elementKind = element.Text("kind");

            if (elementKind is "FUNCTIONPROTO" or "FUNCTIONNOPROTO")
            {
                return "delegate* unmanaged[Cdecl]<" + string.Join(", ", element.Items("arguments").Select(Type).Append(Type(element.GetProperty("result")))) + ">";
            }

            if (elementKind == "RECORD" && !element.Text("name").StartsWith("NVSDK_NGX_", StringComparison.Ordinal) && records[element.Text("name")].GetProperty("opaque").GetBoolean())
            {
                return "nint";
            }

            return (elementKind == "WCHAR" ? "void" : Type(element)) + "*";
        }

        if (kind is "ENUM" or "RECORD")
        {
            return "global::NGX.NET." + unionNames.GetValueOrDefault(type.Text("name"), TypeName(type.Text("name")));
        }

        return kind switch
        {
            "VOID" => "void",
            "BOOL" => "global::NGX.NET.NGXBool8",
            "CHAR_S" or "CHAR_U" or "SCHAR" => "sbyte",
            "UCHAR" => "byte",
            "SHORT" => "short",
            "USHORT" => "ushort",
            "INT" => "int",
            "UINT" => "uint",
            "LONG" => type.Number("size") == 8 ? "long" : "int",
            "ULONG" => type.Number("size") == 8 ? "ulong" : "uint",
            "LONGLONG" => "long",
            "ULONGLONG" => "ulong",
            "FLOAT" => "float",
            "DOUBLE" => "double",
            "WCHAR" => throw new InvalidOperationException("A wchar_t value requires a reviewed platform adaptation."),
            _ => throw new InvalidOperationException($"Unsupported native type: {type}")
        };
    }

    private void WriteEnum(string name, JsonElement value)
    {
        string managed = TypeName(name);
        JsonElement[] values = [.. value.Items("values")];
        bool unsigned = name == "NVSDK_NGX_Result" || values.Any(v => v.GetProperty("value").GetInt64() > int.MaxValue);
        string prefix = name + "_";
        StringBuilder text = new(Header + Namespace + Summary(name));
        text.AppendLine($"[NGXNativeName(\"{name}\")]");
        text.AppendLine($"public enum {managed} : {(unsigned ? "uint" : "int")}\n{{");

        foreach (JsonElement item in values)
        {
            string native = item.Text("name");
            string member = native.StartsWith(prefix, StringComparison.Ordinal) ? native[prefix.Length..] : native.Replace("NVSDK_NGX_", "", StringComparison.Ordinal);
            if (!native.StartsWith(prefix, StringComparison.Ordinal))
            {
                string[] parts = native.Split('_');
                string normalized = name.Replace("_", "", StringComparison.Ordinal);

                for (int count = 1; count < parts.Length; count++)
                {
                    if (string.Concat(parts.Take(count)).Equals(normalized, StringComparison.OrdinalIgnoreCase))
                    {
                        member = string.Join("_", parts.Skip(count));
                        break;
                    }
                }
            }

            text.Append(Summary(native, 4));
            text.AppendLine($"    [NGXNativeName(\"{native}\")]");
            text.AppendLine($"    {FieldName(member)} = {(unsigned ? unchecked((uint)item.GetProperty("value").GetInt64()).ToString(CultureInfo.InvariantCulture) : item.GetProperty("value").GetInt64().ToString(CultureInfo.InvariantCulture))},\n");
        }

        text.AppendLine("}");
        files[$"Types/{managed}.g.cs"] = text.ToString();
    }

    private void WriteRecord(string name, JsonElement value)
    {
        bool opaque = value.GetProperty("opaque").GetBoolean();

        if (opaque && !name.StartsWith("NVSDK_NGX_", StringComparison.Ordinal))
        {
            return;
        }

        string managed = unionNames.GetValueOrDefault(name, TypeName(name));
        StringBuilder text = new(Header + "using System.Runtime.CompilerServices;\nusing System.Runtime.InteropServices;\n\n" + Namespace + Summary(opaque ? name + ". Opaque native object; pass only pointers returned by NGX." : name));
        text.AppendLine($"[NGXNativeName(\"{name}\")]");
        text.AppendLine(opaque ? "[StructLayout(LayoutKind.Sequential)]" : $"[StructLayout(LayoutKind.Explicit, Size = {value.Number("size")})]");
        text.AppendLine($"public unsafe partial struct {managed}\n{{");

        foreach (JsonElement field in value.Items("fields"))
        {
            JsonElement type = field.GetProperty("type");
            string fieldName = field.Text("name");
            text.Append(Summary($"{name}::{fieldName}", 4));
            text.AppendLine($"    [NGXNativeName(\"{fieldName}\")]");
            text.AppendLine($"    [FieldOffset({field.Number("offset") / 8})]");

            if (type.Text("kind") == "CONSTANTARRAY")
            {
                int count = 1;

                while (type.Text("kind") == "CONSTANTARRAY")
                {
                    count *= type.Number("count");
                    type = type.GetProperty("element");
                }

                string element = Type(type);

                if (element is "float" or "double" or "int" or "uint" or "sbyte" or "byte" or "long" or "ulong" or "short" or "ushort")
                {
                    text.AppendLine($"    public fixed {element} {FieldName(fieldName)}[{count}];\n");
                }
                else
                {
                    if (element.EndsWith('*'))
                    {
                        element = "global::NGX.NET.NGXPointer<" + element[..^1] + ">";
                    }

                    string arrayName = TypeName(fieldName) + "Buffer";
                    text.AppendLine($"    public {arrayName} {FieldName(fieldName)};\n");
                    text.Append(Summary($"Inline storage for {count} native elements.", 4));
                    text.AppendLine($"    [InlineArray({count})]\n    public struct {arrayName}\n    {{\n        private {element} element;\n    }}\n");
                }
            }
            else
            {
                text.AppendLine($"    public {Type(type)} {FieldName(fieldName)};\n");
            }
        }

        List<(string Field, string Value)> initializers = [];

        foreach (JsonElement field in value.Items("fields"))
        {
            if (!field.TryGetProperty("declaration", out JsonElement declaration) || !declaration.GetString()!.Contains('='))
            {
                continue;
            }

            string expression = declaration.GetString()!.Split('=', 2)[1].Trim();

            if (Regex.IsMatch(expression, @"^-?\d+(?:\.\d+f)?$"))
            {
                initializers.Add((FieldName(field.Text("name")), expression));
            }
            else if (!Regex.IsMatch(expression, @"^\{[0 ,.f]+\}$"))
            {
                throw new InvalidOperationException("Unreviewed native initializer: " + expression);
            }
        }

        if (initializers.Count > 0)
        {
            text.Append(Summary("Initializes the defaults declared by the native SDK.", 4));
            text.AppendLine($"    public {managed}()\n    {{\n        this = default;\n");

            foreach ((string field, string expression) in initializers)
            {
                text.AppendLine($"        {field} = {expression};");
            }

            text.AppendLine("    }\n");
        }

        text.AppendLine("}");
        files[$"Types/{managed}.g.cs"] = text.ToString();
    }

    private void WriteFunctions(string group, IEnumerable<JsonElement> functionsInGroup)
    {
        StringBuilder text = new(Header + "using System.Runtime.CompilerServices;\nusing System.Runtime.InteropServices;\n\n" + Namespace + "public static unsafe partial class NGX\n{\n");
        int indent = group.Length == 0 ? 4 : 8;
        string spaces = new(' ', indent);

        if (group.Length != 0)
        {
            text.Append(Summary($"{group} application API and native inline helpers.", 4));
            text.AppendLine($"    public static partial class {group}\n    {{");
        }

        foreach (JsonElement function in functionsInGroup.OrderBy(f => f.Text("name"), StringComparer.Ordinal))
        {
            string native = function.Text("name");
            string method = FunctionName(native).Method;
            string result = Type(function.GetProperty("result"));
            JsonElement[] parameters = [.. function.Items("parameters")];
            string args = string.Join(", ", parameters.Select(p => Type(p.GetProperty("type")) + " " + FieldName(p.Text("name"))));
            text.Append(Summary($"{native}. Source: {function.Text("header")}:{function.Number("line")}.", indent));
            text.AppendLine($"{spaces}[LibraryImport(LibraryName, EntryPoint = \"{function.Text("export")}\")]");
            text.AppendLine($"{spaces}[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]");
            text.AppendLine($"{spaces}public static partial {result} {method}({args});\n");
            WriteOverloads(text, function, method, result, parameters, indent);
        }

        if (group.Length != 0)
        {
            text.AppendLine("    }");
        }

        text.AppendLine("}");
        files[$"API/{(group.Length == 0 ? "Core" : group)}.g.cs"] = text.ToString();
    }

    private void WriteOverloads(StringBuilder text, JsonElement function, string method, string result, JsonElement[] parameters, int indent)
    {
        string spaces = new(' ', indent);
        string native = function.Text("name");
        List<string> declarations = [];
        List<string> arguments = [];
        List<string> pins = [];

        foreach (JsonElement parameter in parameters)
        {
            JsonElement type = parameter.GetProperty("type");
            string name = FieldName(parameter.Text("name"));
            string mapped = Type(type);

            if (type.Text("kind") == "POINTER" && type.GetProperty("element").Text("kind") == "RECORD" && !records[type.GetProperty("element").Text("name")].GetProperty("opaque").GetBoolean())
            {
                declarations.Add("ref " + mapped[..^1] + " " + name);
                string pin = "pointer" + pins.Count;
                pins.Add($"fixed ({mapped} {pin} = &{name})");
                arguments.Add(pin);
            }
            else
            {
                declarations.Add(mapped + " " + name);
                arguments.Add(name);
            }
        }

        if (pins.Count > 0)
        {
            text.Append(Summary("Pins native structures for " + native + ".", indent));
            text.AppendLine($"{spaces}public static {result} {method}({string.Join(", ", declarations)})\n{spaces}{{");

            foreach (string pin in pins)
            {
                text.AppendLine($"{spaces}    {pin}");
            }

            text.AppendLine($"{spaces}    {{\n{spaces}        {(result == "void" ? "" : "return ")}{method}({string.Join(", ", arguments)});\n{spaces}    }}\n{spaces}}}\n");
        }

        if (native.StartsWith("NVSDK_NGX_Parameter_", StringComparison.Ordinal))
        {
            bool getter = native.StartsWith("NVSDK_NGX_Parameter_Get", StringComparison.Ordinal);
            string valueType = Type(parameters[2].GetProperty("type"));
            string valueName = getter ? "out " + valueType[..^1] + " value" : valueType + " value";
            text.Append(Summary("Uses a UTF-8 parameter name with " + native + ".", indent));
            text.AppendLine($"{spaces}public static {result} {method}(global::NGX.NET.NGXParameter* parameters, ReadOnlySpan<byte> name, {valueName})\n{spaces}{{");
            text.AppendLine($"{spaces}    byte[] terminated = new byte[name.Length + 1];\n{spaces}    name.CopyTo(terminated);\n{spaces}    terminated[^1] = 0;");

            if (getter)
            {
                text.AppendLine($"{spaces}    value = default;");
                text.AppendLine($"{spaces}    fixed ({valueType} output = &value)");
            }

            text.AppendLine($"{spaces}    fixed (byte* key = terminated)\n{spaces}    {{\n{spaces}        {(getter ? "return " : "")}{method}(parameters, (sbyte*)key, {(getter ? "output" : "value")});\n{spaces}    }}\n{spaces}}}\n");

            if (getter)
            {
                text.Append(Summary("Returns a typed parameter value and throws on NGX failure.", indent));
                text.AppendLine($"{spaces}public static {valueType[..^1]} {method}(global::NGX.NET.NGXParameter* parameters, ReadOnlySpan<byte> name)\n{spaces}{{\n{spaces}    ThrowIfFailed({method}(parameters, name, out {valueType[..^1]} value), \"{native}\");\n\n{spaces}    return value;\n{spaces}}}\n");
            }
        }

        // Reviewed one-output contracts. Never infer an owned result merely
        // because an arbitrary future API contains a pointer parameter.
        int output = Array.FindIndex(parameters, p => p.Text("name") is "OutParameters" or "OutHandle" or "ppOutHandle" or "OutSizeInBytes");
        bool reviewed = OutputContracts.Contains(native);

        if (reviewed && output >= 0 && result == "global::NGX.NET.NGXResult")
        {
            string outputType = Type(parameters[output].GetProperty("type"))[..^1];
            string args = string.Join(", ", parameters.Where((_, i) => i != output).Select(p => Type(p.GetProperty("type")) + " " + FieldName(p.Text("name"))));
            string call = string.Join(", ", parameters.Select((p, i) => i == output ? "&value" : FieldName(p.Text("name"))));
            text.Append(Summary("Returns the reviewed output of " + native + "; throws on NGX failure. The caller owns any returned handle or parameter map.", indent));
            text.AppendLine($"{spaces}public static {outputType} {method}({args})\n{spaces}{{\n{spaces}    {outputType} value = default;\n{spaces}    ThrowIfFailed({method}({call}), \"{native}\");\n\n{spaces}    return value;\n{spaces}}}\n");
            string outArgs = string.Join(", ", parameters.Select((p, i) => i == output ? "out " + outputType + " value" : Type(p.GetProperty("type")) + " " + FieldName(p.Text("name"))));
            text.Append(Summary("Preserves the native result and writes the output of " + native + ".", indent));
            text.AppendLine($"{spaces}public static {result} {method}({outArgs})\n{spaces}{{\n{spaces}    value = default;\n\n{spaces}    fixed ({outputType}* pointer = &value)\n{spaces}    {{\n{spaces}        return {method}({call.Replace("&value", "pointer", StringComparison.Ordinal)});\n{spaces}    }}\n{spaces}}}\n");
        }
    }

    private void WriteConstants()
    {
        StringBuilder text = new(Header + Namespace + "public static unsafe partial class NGX\n{\n");
        Dictionary<string, JsonElement> macros = Merge("macros");

        foreach (JsonElement macro in macros.Values.OrderBy(m => m.Text("name"), StringComparer.Ordinal))
        {
            string native = macro.Text("name");
            string[] tokens = [.. macro.Items("tokens").Select(t => t.GetString()!)];

            if (macro.GetProperty("functionLike").GetBoolean() || tokens.Length == 0)
            {
                continue;
            }

            if (tokens.All(t => t.StartsWith('"')))
            {
                text.Append(Summary(native, 4));
                text.AppendLine($"    [NGXNativeName(\"{native}\")]");
                text.AppendLine($"    public static ReadOnlySpan<byte> {Name(native)} => {string.Join(" + ", tokens.Select(t => t + "u8"))};\n");
            }
            else if (native == "NVSDK_NGX_VERSION_API_MACRO")
            {
                text.Append(Summary(native, 4));
                text.AppendLine($"    [NGXNativeName(\"{native}\")]");
                text.AppendLine($"    public const uint VersionAPI = {tokens[0]};\n");
            }
            else if (native == "NVSDK_NGX_DLSS_DEBUG_OVERLAY_VALUE_UNSET")
            {
                text.Append(Summary(native, 4));
                text.AppendLine($"    [NGXNativeName(\"{native}\")]");
                text.AppendLine($"    public const int DLSSDebugOverlayValueUnset = {string.Concat(tokens)};\n");
            }
            else if (native is not ("NVSDK_NGX_API" or "NVSDK_CONV" or "SR_DEPRECATED_SHARPENING"))
            {
                throw new InvalidOperationException("Unclassified public macro: " + native);
            }
        }

        text.AppendLine("}");
        files["API/Constants.g.cs"] = text.ToString();
    }
}
