using System.Globalization;
using System.Security;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace NGX.NET.Generator;

internal sealed partial class Emitter
{
    private readonly JsonElement[] platforms;
    private readonly Dictionary<string, JsonElement> records;
    private readonly Dictionary<string, JsonElement> enums;
    private readonly Dictionary<string, JsonElement> functions;
    private readonly Dictionary<string, string> files = [];
    private readonly Dictionary<string, string> unionNames = [];
    private const string Header = "// <auto-generated/>\n// Generated by NGX.NET.Generator. Changes belong in the generator.\n\n";
    private const string Namespace = "namespace NGX.NET;\n\n";

    public Emitter(JsonElement ast)
    {
        platforms = [.. ast.GetProperty("platforms").EnumerateObject().Select(p => p.Value)];
        records = Merge("records");
        enums = Merge("enums");
        functions = Merge("functions");

        foreach (JsonElement parent in records.Values)
        {
            foreach (JsonElement field in parent.Items("fields"))
            {
                JsonElement type = field.GetProperty("type");

                if (type.Text("kind") == "RECORD" && records[type.Text("name")].Text("kind") == "UNION_DECL")
                {
                    unionNames[type.Text("name")] = TypeName(parent.Text("name")) + "Union";
                }
            }
        }
    }

    private Dictionary<string, JsonElement> Merge(string key) => platforms.SelectMany(p => p.Items(key)).GroupBy(e => e.Text("name")).ToDictionary(g => g.Key, g => g.First());

    public Dictionary<string, string> Generate()
    {
        ValidateLayouts();

        foreach ((string name, JsonElement value) in enums)
        {
            WriteEnum(name, value);
        }

        foreach ((string name, JsonElement value) in records)
        {
            WriteRecord(name, value);
        }

        foreach (IGrouping<string, JsonElement> group in functions.Values.GroupBy(f => FunctionName(f.Text("name")).Group))
        {
            WriteFunctions(group.Key, group);
        }

        WriteCallbacks();
        WriteConstants();

        return files;
    }

    private void ValidateLayouts()
    {
        foreach (JsonElement platform in platforms)
        {
            foreach (JsonElement record in platform.Items("records"))
            {
                JsonElement shared = records[record.Text("name")];

                if (record.Number("size") != shared.Number("size") || record.Number("align") != shared.Number("align") || !record.Items("fields").Select(f => (f.Text("name"), f.Number("offset"))).SequenceEqual(shared.Items("fields").Select(f => (f.Text("name"), f.Number("offset")))))
                {
                    throw new InvalidOperationException("A platform-specific layout requires review: " + record.Text("name"));
                }

                foreach (JsonElement field in record.Items("fields"))
                {
                    MathFieldType(record.Text("name"), field);
                }
            }

            foreach (JsonElement function in platform.Items("functions"))
            {
                JsonElement shared = functions[function.Text("name")];

                if (Type(function.GetProperty("result")) != Type(shared.GetProperty("result")) || !function.Items("parameters").Select(p => Type(p.GetProperty("type"))).SequenceEqual(shared.Items("parameters").Select(p => Type(p.GetProperty("type")))))
                {
                    throw new InvalidOperationException("A platform-specific function signature requires review: " + function.Text("name"));
                }
            }
        }
    }

    private void WriteCallbacks()
    {
        Dictionary<string, JsonElement> aliases = platforms.SelectMany(p => p.GetProperty("aliases").EnumerateObject()).GroupBy(p => p.Name).ToDictionary(g => g.Key, g => g.First().Value);

        foreach ((string native, JsonElement type) in aliases)
        {
            if (type.Text("kind") != "POINTER" || type.GetProperty("element").Text("kind") != "FUNCTIONPROTO")
            {
                continue;
            }

            string name = TypeName(native);
            string pointer = Type(type);
            files[$"Callbacks/{name}.g.cs"] = Header + "using System.Runtime.InteropServices;\n\n" + Namespace + Summary(native + ". Keep callback code alive while NGX retains it; never let managed exceptions cross this ABI.") +
                $"[NGXNativeName(\"{native}\")]\n[StructLayout(LayoutKind.Sequential)]\npublic readonly unsafe struct {name}({pointer} pointer)\n{{\n" +
                Summary("Native C callback pointer. C++ reference parameters use their pointer ABI.", 4) +
                $"    public readonly {pointer} Pointer = pointer;\n}}\n";
        }
    }

    private static string Escape(string value) => SecurityElement.Escape(value)!;

    private static string Summary(string text, int indent = 0)
    {
        string spaces = new(' ', indent);

        return $"{spaces}/// <summary>\n{spaces}/// {Escape(text)}\n{spaces}/// </summary>\n";
    }

    internal static string Name(string name)
    {
        name = name.Replace("NVSDK_NGX_", "", StringComparison.Ordinal);
        HashSet<string> acronyms = ["NGX", "DLSS", "DLSSD", "DLSSG", "DLAA", "DLISP", "CUDA", "D3D11", "D3D12", "VK", "UI", "ULL", "F", "D", "I", "API", "HDR", "SR", "RR", "RW", "VRAM"];

        return string.Concat(name.Split('_', StringSplitOptions.RemoveEmptyEntries).Select(p => acronyms.Contains(p) || p.Any(char.IsLower) ? char.ToUpperInvariant(p[0]) + p[1..] : CultureInfo.InvariantCulture.TextInfo.ToTitleCase(p.ToLowerInvariant())));
    }

    private static string TypeName(string native)
    {
        string name = Name(native);

        return name.StartsWith("NGX", StringComparison.Ordinal) ? name : "NGX" + name;
    }

    // PascalCase names cannot collide with C#'s lowercase keywords.
    private static string FieldName(string name) => name == "v" ? "V" : Name(name);

    private static string ParameterName(string native)
    {
        string name = Name(native);
        // Preserve existing camelCase prefixes, such as pVRAMAllocatedBytes.
        name = char.IsLower(native[0]) ? char.ToLowerInvariant(name[0]) + name[1..] : JsonNamingPolicy.CamelCase.ConvertName(name);

        return name switch
        {
            "abstract" or "as" or "base" or "bool" or "break" or "byte" or "case" or "catch" or "char" or "checked" or
            "class" or "const" or "continue" or "decimal" or "default" or "delegate" or "do" or "double" or "else" or "enum" or
            "event" or "explicit" or "extern" or "false" or "finally" or "fixed" or "float" or "for" or "foreach" or "goto" or
            "if" or "implicit" or "in" or "int" or "interface" or "internal" or "is" or "lock" or "long" or "namespace" or
            "new" or "null" or "object" or "operator" or "out" or "override" or "params" or "private" or "protected" or "public" or
            "readonly" or "ref" or "return" or "sbyte" or "sealed" or "short" or "sizeof" or "stackalloc" or "static" or "string" or
            "struct" or "switch" or "this" or "throw" or "true" or "try" or "typeof" or "uint" or "ulong" or "unchecked" or
            "unsafe" or "ushort" or "using" or "virtual" or "void" or "volatile" or "while" => "@" + name,
            _ => name
        };
    }

    private static (string Group, string Method) FunctionName(string native)
    {
        if (native == "GetNGXResultAsString")
        {
            return ("", "GetResultAsString");
        }

        string name = native.StartsWith("NVSDK_NGX_", StringComparison.Ordinal) ? native[10..] : native[4..];

        foreach (string prefix in new[] { "D3D11", "D3D12", "CUDA", "VULKAN", "VK", "Parameter", "DLSSD", "DLSS" })
        {
            if (name.StartsWith(prefix + "_", StringComparison.Ordinal))
            {
                return (prefix is "VULKAN" or "VK" ? "Vulkan" : prefix, Name(name[(prefix.Length + 1)..]));
            }
        }

        return ("", Name(name));
    }

    private string Type(JsonElement type)
    {
        string kind = type.Text("kind");
        string cpp = type.Text("cpp").Replace("const ", "", StringComparison.Ordinal).Trim();

        if (cpp == "size_t")
        {
            return "nuint";
        }

        if (cpp == "size_t *")
        {
            return "nuint*";
        }

        if (kind is "POINTER" or "LVALUEREFERENCE" or "RVALUEREFERENCE")
        {
            JsonElement element = type.GetProperty("element");
            string elementKind = element.Text("kind");

            if (elementKind is "FUNCTIONPROTO" or "FUNCTIONNOPROTO")
            {
                return "delegate* unmanaged[Cdecl]<" + string.Join(", ", element.Items("arguments").Select(Type).Append(Type(element.GetProperty("result")))) + ">";
            }

            if (elementKind == "RECORD" && !element.Text("name").StartsWith("NVSDK_NGX_", StringComparison.Ordinal) && records[element.Text("name")].GetProperty("opaque").GetBoolean())
            {
                return "nint";
            }

            return (elementKind == "WCHAR" ? "void" : Type(element)) + "*";
        }

        if (kind is "ENUM" or "RECORD")
        {
            return unionNames.GetValueOrDefault(type.Text("name"), TypeName(type.Text("name")));
        }

        return kind switch
        {
            "VOID" => "void",
            "BOOL" => "NGXBool8",
            "CHAR_S" or "CHAR_U" or "SCHAR" => "sbyte",
            "UCHAR" => "byte",
            "SHORT" => "short",
            "USHORT" => "ushort",
            "INT" => "int",
            "UINT" => "uint",
            "LONG" => type.Number("size") == 8 ? "long" : "int",
            "ULONG" => type.Number("size") == 8 ? "ulong" : "uint",
            "LONGLONG" => "long",
            "ULONGLONG" => "ulong",
            "FLOAT" => "float",
            "DOUBLE" => "double",
            "WCHAR" => throw new InvalidOperationException("A wchar_t value requires a reviewed platform adaptation."),
            _ => throw new InvalidOperationException($"Unsupported native type: {type}")
        };
    }

    private void WriteEnum(string name, JsonElement value)
    {
        string managed = TypeName(name);
        JsonElement[] values = [.. value.Items("values")];
        bool unsigned = name == "NVSDK_NGX_Result" || values.Any(v => v.GetProperty("value").GetInt64() > int.MaxValue);
        string prefix = name + "_";
        StringBuilder text = new(Header + Namespace + Summary(name));
        text.AppendLine($"[NGXNativeName(\"{name}\")]");
        text.AppendLine($"public enum {managed} : {(unsigned ? "uint" : "int")}\n{{");

        foreach (JsonElement item in values)
        {
            string native = item.Text("name");
            string member = native.StartsWith(prefix, StringComparison.Ordinal) ? native[prefix.Length..] : native.Replace("NVSDK_NGX_", "", StringComparison.Ordinal);
            if (!native.StartsWith(prefix, StringComparison.Ordinal))
            {
                string[] parts = native.Split('_');
                string normalized = name.Replace("_", "", StringComparison.Ordinal);

                for (int count = 1; count < parts.Length; count++)
                {
                    if (string.Concat(parts.Take(count)).Equals(normalized, StringComparison.OrdinalIgnoreCase))
                    {
                        member = string.Join("_", parts.Skip(count));
                        break;
                    }
                }
            }

            text.Append(Summary(native, 4));
            text.AppendLine($"    [NGXNativeName(\"{native}\")]");
            text.AppendLine($"    {member.Replace("_", "", StringComparison.Ordinal)} = {(unsigned ? unchecked((uint)item.GetProperty("value").GetInt64()).ToString(CultureInfo.InvariantCulture) : item.GetProperty("value").GetInt64().ToString(CultureInfo.InvariantCulture))},\n");
        }

        text.AppendLine("}");
        files[$"Types/{managed}.g.cs"] = text.ToString();
    }

    private void WriteRecord(string name, JsonElement value)
    {
        bool opaque = value.GetProperty("opaque").GetBoolean();

        if (opaque && !name.StartsWith("NVSDK_NGX_", StringComparison.Ordinal))
        {
            return;
        }

        string managed = unionNames.GetValueOrDefault(name, TypeName(name));
        string numerics = value.Items("fields").Any(field => MathFieldType(name, field) is not null) ? "using System.Numerics;\n" : "";
        StringBuilder text = new(Header + numerics + "using System.Runtime.CompilerServices;\nusing System.Runtime.InteropServices;\n\n" + Namespace + Summary(opaque ? name + ". Opaque native object; pass only pointers returned by NGX." : name));
        text.AppendLine($"[NGXNativeName(\"{name}\")]");
        text.AppendLine(opaque ? "[StructLayout(LayoutKind.Sequential)]" : $"[StructLayout(LayoutKind.Explicit, Size = {value.Number("size")})]");
        text.AppendLine($"public unsafe partial struct {managed}\n{{");

        foreach (JsonElement field in value.Items("fields"))
        {
            JsonElement type = field.GetProperty("type");
            string fieldName = field.Text("name");
            text.Append(Summary($"{name}::{fieldName}", 4));
            text.AppendLine($"    [NGXNativeName(\"{fieldName}\")]");
            text.AppendLine($"    [FieldOffset({field.Number("offset") / 8})]");

            if (MathFieldType(name, field) is string mathType)
            {
                text.AppendLine($"    public {mathType} {FieldName(fieldName)};\n");
            }
            else if (type.Text("kind") == "CONSTANTARRAY")
            {
                int count = 1;

                while (type.Text("kind") == "CONSTANTARRAY")
                {
                    count *= type.Number("count");
                    type = type.GetProperty("element");
                }

                string element = Type(type);

                if (element is "float" or "double" or "int" or "uint" or "sbyte" or "byte" or "long" or "ulong" or "short" or "ushort")
                {
                    text.AppendLine($"    public fixed {element} {FieldName(fieldName)}[{count}];\n");
                }
                else
                {
                    if (element.EndsWith('*'))
                    {
                        element = "NGXPointer<" + element[..^1] + ">";
                    }

                    string arrayName = TypeName(fieldName) + "Buffer";
                    text.AppendLine($"    public {arrayName} {FieldName(fieldName)};\n");
                    text.Append(Summary($"Inline storage for {count} native elements.", 4));
                    text.AppendLine($"    [InlineArray({count})]\n    public struct {arrayName}\n    {{\n        private {element} element;\n    }}\n");
                }
            }
            else
            {
                text.AppendLine($"    public {Type(type)} {FieldName(fieldName)};\n");
            }
        }

        List<(string Field, string Value)> initializers = [];

        foreach (JsonElement field in value.Items("fields"))
        {
            if (!field.TryGetProperty("declaration", out JsonElement declaration) || !declaration.GetString()!.Contains('='))
            {
                continue;
            }

            string expression = declaration.GetString()!.Split('=', 2)[1].Trim();

            if (Regex.IsMatch(expression, @"^-?\d+(?:\.\d+f)?$"))
            {
                initializers.Add((FieldName(field.Text("name")), expression));
            }
            else if (!Regex.IsMatch(expression, @"^\{[0 ,.f]+\}$"))
            {
                throw new InvalidOperationException("Unreviewed native initializer: " + expression);
            }
        }

        if (initializers.Count > 0)
        {
            text.Append(Summary("Initializes the defaults declared by the native SDK.", 4));
            text.AppendLine($"    public {managed}()\n    {{\n        this = default;\n");

            foreach ((string field, string expression) in initializers)
            {
                text.AppendLine($"        {field} = {expression};");
            }

            text.AppendLine("    }\n");
        }

        text.AppendLine("}");
        files[$"Types/{managed}.g.cs"] = text.ToString();
    }

    // These fields have explicit vector/matrix semantics in the SDK. Array
    // length alone is not sufficient to map arbitrary native data to math types.
    private static string? MathFieldType(string record, JsonElement field)
    {
        string? managed = record switch
        {
            "NVSDK_NGX_DLSSG_Opt_Eval_Params" => field.Text("name") switch
            {
                "cameraViewToClip" or "clipToCameraView" or "clipToLensClip" or "clipToPrevClip" or "prevClipToClip" => "Matrix4x4",
                "jitterOffset" or "mvecScale" or "cameraPinholeOffset" => "Vector2",
                "cameraPos" or "cameraUp" or "cameraRight" or "cameraFwd" => "Vector3",
                _ => null
            },
            "NVSDK_NGX_CUDA_DLSSD_Eval_Params" or "NVSDK_NGX_D3D11_DLSSD_Eval_Params" or
            "NVSDK_NGX_D3D12_DLSSD_Eval_Params" or "NVSDK_NGX_VK_DLSSD_Eval_Params"
                when field.Text("name") is "pInWorldToViewMatrix" or "pInViewToClipMatrix" => "Matrix4x4*",
            _ => null
        };

        if (managed is null)
        {
            return null;
        }

        JsonElement type = field.GetProperty("type");
        bool compatible = managed switch
        {
            "Vector2" => IsFloatArray(type, 2),
            "Vector3" => IsFloatArray(type, 3),
            "Matrix4x4" => IsFloatArray(type, 4, 4),
            "Matrix4x4*" => type.Text("kind") == "POINTER" && type.GetProperty("element").Text("kind") == "FLOAT" && type.GetProperty("element").Number("size") == sizeof(float),
            _ => false
        };

        if (!compatible)
        {
            throw new InvalidOperationException($"A mathematical field mapping requires review: {record}::{field.Text("name")} -> {managed}");
        }

        return managed;
    }

    private static bool IsFloatArray(JsonElement type, params int[] dimensions)
    {
        foreach (int count in dimensions)
        {
            if (type.Text("kind") != "CONSTANTARRAY" || type.Number("count") != count)
            {
                return false;
            }

            type = type.GetProperty("element");
        }

        return type.Text("kind") == "FLOAT" && type.Number("size") == sizeof(float);
    }

    private void WriteFunctions(string group, IEnumerable<JsonElement> functionsInGroup)
    {
        StringBuilder text = new(Header + "using System.Runtime.CompilerServices;\nusing System.Runtime.InteropServices;\n\n" + Namespace + "public static unsafe partial class NGX\n{\n");
        int indent = group.Length == 0 ? 4 : 8;
        string spaces = new(' ', indent);

        if (group.Length != 0)
        {
            text.Append(Summary($"{group} application API and native inline helpers.", 4));
            text.AppendLine($"    public static partial class {group}\n    {{");
        }

        foreach (JsonElement function in functionsInGroup.OrderBy(f => f.Text("name"), StringComparer.Ordinal))
        {
            string native = function.Text("name");
            string method = FunctionName(native).Method;
            string result = Type(function.GetProperty("result"));
            JsonElement[] parameters = [.. function.Items("parameters")];
            string args = string.Join(", ", parameters.Select(p => Type(p.GetProperty("type")) + " " + ParameterName(p.Text("name"))));
            text.Append(Summary($"{native}. Source: {function.Text("header")}:{function.Number("line")}.", indent));
            text.AppendLine($"{spaces}[LibraryImport(LibraryName, EntryPoint = \"{function.Text("export")}\")]");
            text.AppendLine($"{spaces}[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]");
            text.AppendLine($"{spaces}public static partial {result} {method}({args});\n");
        }

        if (group.Length != 0)
        {
            text.AppendLine("    }");
        }

        text.AppendLine("}");
        files[$"API/{(group.Length == 0 ? "Core" : group)}.g.cs"] = text.ToString();
    }

    private void WriteConstants()
    {
        StringBuilder text = new(Header + Namespace + "public static unsafe partial class NGX\n{\n");
        Dictionary<string, JsonElement> macros = Merge("macros");

        foreach (JsonElement macro in macros.Values.OrderBy(m => m.Text("name"), StringComparer.Ordinal))
        {
            string native = macro.Text("name");
            string[] tokens = [.. macro.Items("tokens").Select(t => t.GetString()!)];

            if (macro.GetProperty("functionLike").GetBoolean() || tokens.Length == 0)
            {
                continue;
            }

            if (tokens.All(t => t.StartsWith('"')))
            {
                text.Append(Summary(native, 4));
                text.AppendLine($"    [NGXNativeName(\"{native}\")]");
                text.AppendLine($"    public const string {Name(native)} = {string.Join(" + ", tokens)};\n");
            }
            else if (native == "NVSDK_NGX_VERSION_API_MACRO")
            {
                text.Append(Summary(native, 4));
                text.AppendLine($"    [NGXNativeName(\"{native}\")]");
                text.AppendLine($"    public const uint VersionAPI = {tokens[0]};\n");
            }
            else if (native == "NVSDK_NGX_DLSS_DEBUG_OVERLAY_VALUE_UNSET")
            {
                text.Append(Summary(native, 4));
                text.AppendLine($"    [NGXNativeName(\"{native}\")]");
                text.AppendLine($"    public const int DLSSDebugOverlayValueUnset = {string.Concat(tokens)};\n");
            }
            else if (native is not ("NVSDK_NGX_API" or "NVSDK_CONV" or "SR_DEPRECATED_SHARPENING"))
            {
                throw new InvalidOperationException("Unclassified public macro: " + native);
            }
        }

        text.AppendLine("}");
        files["API/Constants.g.cs"] = text.ToString();
    }
}
