using System.Text;
using System.Text.Json;

namespace NGX.NET.Generator;

internal static class Program
{
    private static readonly UTF8Encoding UTF8 = new(true);

    private static int Main(string[] args)
    {
        try
        {
            string root = args.Length > 0 ? Path.GetFullPath(args[0]) : Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../"));
            string input = Path.Combine(root, "NGX.NET.Generator", "ast.json");
            using JsonDocument document = JsonDocument.Parse(File.ReadAllText(input));
            Emitter emitter = new(document.RootElement);
            Dictionary<string, string> files = emitter.Generate();
            string output = Path.Combine(root, "NGX.NET");
            int changed = 0;
            foreach ((string name, string source) in files)
            {
                string path = Path.Combine(output, name);
                byte[] content = [.. UTF8.GetPreamble(), .. UTF8.GetBytes(source)];
                Directory.CreateDirectory(Path.GetDirectoryName(path)!);

                if (!File.Exists(path) || !File.ReadAllBytes(path).AsSpan().SequenceEqual(content))
                {
                    File.WriteAllBytes(path, content);
                    changed++;
                }
            }

            foreach (string directory in new[] { "API", "Types", "Callbacks" })
            {
                foreach (string path in Directory.EnumerateFiles(Path.Combine(output, directory), "*.g.cs", SearchOption.AllDirectories))
                {
                    string name = Path.GetRelativePath(output, path).Replace(Path.DirectorySeparatorChar, '/');
                    if (!files.ContainsKey(name) && File.ReadAllText(path).ReplaceLineEndings("\n").StartsWith("// <auto-generated/>\n// Generated by NGX.NET.Generator.", StringComparison.Ordinal))
                    {
                        File.Delete(path);
                        changed++;
                    }
                }
            }

            Console.WriteLine($"Generated {files.Count} files; {changed} changed.");

            return 0;
        }
        catch (Exception exception)
        {
            Console.Error.WriteLine(exception.Message);

            return 1;
        }
    }
}
