// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_Application_Identifier. Owns only storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 32)]
internal unsafe partial struct NGXApplicationIdentifierNative : IDisposable
{
    /// <summary>
    /// NVSDK_NGX_Application_Identifier::IdentifierType
    /// </summary>
    [FieldOffset(0)]
    public NGXApplicationIdentifierType IdentifierType;

    /// <summary>
    /// NVSDK_NGX_Application_Identifier::v
    /// </summary>
    [FieldOffset(8)]
    public NGXApplicationIdentifierUnionNative V;

    public NGXApplicationIdentifierNative(in NGXApplicationIdentifier value)
    {
        this = default;

        try
        {
            if (value.IdentifierType == NGXApplicationIdentifierType.ProjectId != value.V.ProjectDesc.HasValue) throw new ArgumentException("Application identifier and active union member disagree.", nameof(value));
            if (value.IdentifierType is not (NGXApplicationIdentifierType.ProjectId or NGXApplicationIdentifierType.ApplicationId)) throw new ArgumentOutOfRangeException(nameof(value));
            IdentifierType = value.IdentifierType;
            V = new(in value.V);
        }
        catch
        {
            Dispose();
            throw;
        }
    }

    public void Dispose()
    {
        if (IdentifierType == NGXApplicationIdentifierType.ProjectId) V.ProjectDesc.Dispose();
        this = default;
    }
}
