// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_BufferInfo_VK. Owns storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 16)]
internal unsafe struct NGXBufferInfoVKNative : IDisposable
{
    /// <summary>
    /// NVSDK_NGX_BufferInfo_VK::Buffer
    /// </summary>
    [FieldOffset(0)]
    public nint Buffer;

    /// <summary>
    /// NVSDK_NGX_BufferInfo_VK::SizeInBytes
    /// </summary>
    [FieldOffset(8)]
    public uint SizeInBytes;

    public NGXBufferInfoVKNative(in NGXBufferInfoVK value)
    {
        this = default;

        try
        {
            Buffer = value.Buffer;
            SizeInBytes = value.SizeInBytes;
        }
        catch
        {
            Dispose();

            throw;
        }
    }

    public void Dispose()
    {
        this = default;
    }
}
