// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_CUDA_DLSSD_Eval_Params. Owns storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 632)]
internal unsafe struct NGXCUDADLSSDEvalParamsNative : IDisposable
{
    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDiffuseAlbedo
    /// </summary>
    [FieldOffset(0)]
    public void* PInDiffuseAlbedo;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInSpecularAlbedo
    /// </summary>
    [FieldOffset(8)]
    public void* PInSpecularAlbedo;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInNormals
    /// </summary>
    [FieldOffset(16)]
    public void* PInNormals;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInRoughness
    /// </summary>
    [FieldOffset(24)]
    public void* PInRoughness;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInColor
    /// </summary>
    [FieldOffset(32)]
    public void* PInColor;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInOutput
    /// </summary>
    [FieldOffset(40)]
    public void* PInOutput;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDepth
    /// </summary>
    [FieldOffset(48)]
    public void* PInDepth;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInMotionVectors
    /// </summary>
    [FieldOffset(56)]
    public void* PInMotionVectors;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InJitterOffsetX
    /// </summary>
    [FieldOffset(64)]
    public float InJitterOffsetX;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InJitterOffsetY
    /// </summary>
    [FieldOffset(68)]
    public float InJitterOffsetY;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InRenderSubrectDimensions
    /// </summary>
    [FieldOffset(72)]
    public NGXDimensionsNative InRenderSubrectDimensions;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InReset
    /// </summary>
    [FieldOffset(80)]
    public int InReset;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InMVScaleX
    /// </summary>
    [FieldOffset(84)]
    public float InMVScaleX;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InMVScaleY
    /// </summary>
    [FieldOffset(88)]
    public float InMVScaleY;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInTransparencyMask
    /// </summary>
    [FieldOffset(96)]
    public void* PInTransparencyMask;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInExposureTexture
    /// </summary>
    [FieldOffset(104)]
    public void* PInExposureTexture;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInBiasCurrentColorMask
    /// </summary>
    [FieldOffset(112)]
    public void* PInBiasCurrentColorMask;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDiffuseAlbedoSubrectBase
    /// </summary>
    [FieldOffset(120)]
    public NGXCoordinatesNative InDiffuseAlbedoSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InSpecularAlbedoSubrectBase
    /// </summary>
    [FieldOffset(128)]
    public NGXCoordinatesNative InSpecularAlbedoSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InNormalsSubrectBase
    /// </summary>
    [FieldOffset(136)]
    public NGXCoordinatesNative InNormalsSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InRoughnessSubrectBase
    /// </summary>
    [FieldOffset(144)]
    public NGXCoordinatesNative InRoughnessSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InColorSubrectBase
    /// </summary>
    [FieldOffset(152)]
    public NGXCoordinatesNative InColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDepthSubrectBase
    /// </summary>
    [FieldOffset(160)]
    public NGXCoordinatesNative InDepthSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InMVSubrectBase
    /// </summary>
    [FieldOffset(168)]
    public NGXCoordinatesNative InMVSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InTranslucencySubrectBase
    /// </summary>
    [FieldOffset(176)]
    public NGXCoordinatesNative InTranslucencySubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InBiasCurrentColorSubrectBase
    /// </summary>
    [FieldOffset(184)]
    public NGXCoordinatesNative InBiasCurrentColorSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InOutputSubrectBase
    /// </summary>
    [FieldOffset(192)]
    public NGXCoordinatesNative InOutputSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInReflectedAlbedo
    /// </summary>
    [FieldOffset(200)]
    public void* PInReflectedAlbedo;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInColorBeforeParticles
    /// </summary>
    [FieldOffset(208)]
    public void* PInColorBeforeParticles;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInColorBeforeTransparency
    /// </summary>
    [FieldOffset(216)]
    public void* PInColorBeforeTransparency;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInColorBeforeFog
    /// </summary>
    [FieldOffset(224)]
    public void* PInColorBeforeFog;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDiffuseHitDistance
    /// </summary>
    [FieldOffset(232)]
    public void* PInDiffuseHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInSpecularHitDistance
    /// </summary>
    [FieldOffset(240)]
    public void* PInSpecularHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDiffuseRayDirection
    /// </summary>
    [FieldOffset(248)]
    public void* PInDiffuseRayDirection;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInSpecularRayDirection
    /// </summary>
    [FieldOffset(256)]
    public void* PInSpecularRayDirection;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDiffuseRayDirectionHitDistance
    /// </summary>
    [FieldOffset(264)]
    public void* PInDiffuseRayDirectionHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInSpecularRayDirectionHitDistance
    /// </summary>
    [FieldOffset(272)]
    public void* PInSpecularRayDirectionHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InReflectedAlbedoSubrectBase
    /// </summary>
    [FieldOffset(280)]
    public NGXCoordinatesNative InReflectedAlbedoSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InColorBeforeParticlesSubrectBase
    /// </summary>
    [FieldOffset(288)]
    public NGXCoordinatesNative InColorBeforeParticlesSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InColorBeforeTransparencySubrectBase
    /// </summary>
    [FieldOffset(296)]
    public NGXCoordinatesNative InColorBeforeTransparencySubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InColorBeforeFogSubrectBase
    /// </summary>
    [FieldOffset(304)]
    public NGXCoordinatesNative InColorBeforeFogSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDiffuseHitDistanceSubrectBase
    /// </summary>
    [FieldOffset(312)]
    public NGXCoordinatesNative InDiffuseHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InSpecularHitDistanceSubrectBase
    /// </summary>
    [FieldOffset(320)]
    public NGXCoordinatesNative InSpecularHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDiffuseRayDirectionSubrectBase
    /// </summary>
    [FieldOffset(328)]
    public NGXCoordinatesNative InDiffuseRayDirectionSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InSpecularRayDirectionSubrectBase
    /// </summary>
    [FieldOffset(336)]
    public NGXCoordinatesNative InSpecularRayDirectionSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InDiffuseRayDirectionHitDistanceSubrectBase
    /// </summary>
    [FieldOffset(344)]
    public NGXCoordinatesNative InDiffuseRayDirectionHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InSpecularRayDirectionHitDistanceSubrectBase
    /// </summary>
    [FieldOffset(352)]
    public NGXCoordinatesNative InSpecularRayDirectionHitDistanceSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInWorldToViewMatrix
    /// </summary>
    [FieldOffset(360)]
    public Matrix4x4* PInWorldToViewMatrix;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInViewToClipMatrix
    /// </summary>
    [FieldOffset(368)]
    public Matrix4x4* PInViewToClipMatrix;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InPreExposure
    /// </summary>
    [FieldOffset(376)]
    public float InPreExposure;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InExposureScale
    /// </summary>
    [FieldOffset(380)]
    public float InExposureScale;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InIndicatorInvertXAxis
    /// </summary>
    [FieldOffset(384)]
    public int InIndicatorInvertXAxis;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InIndicatorInvertYAxis
    /// </summary>
    [FieldOffset(388)]
    public int InIndicatorInvertYAxis;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::GBufferSurface
    /// </summary>
    [FieldOffset(392)]
    public NGXCUDAGBufferNative GBufferSurface;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InToneMapperType
    /// </summary>
    [FieldOffset(528)]
    public NGXToneMapperType InToneMapperType;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInMotionVectors3D
    /// </summary>
    [FieldOffset(536)]
    public void* PInMotionVectors3D;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInIsParticleMask
    /// </summary>
    [FieldOffset(544)]
    public void* PInIsParticleMask;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInAnimatedTextureMask
    /// </summary>
    [FieldOffset(552)]
    public void* PInAnimatedTextureMask;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInDepthHighRes
    /// </summary>
    [FieldOffset(560)]
    public void* PInDepthHighRes;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInPositionViewSpace
    /// </summary>
    [FieldOffset(568)]
    public void* PInPositionViewSpace;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InFrameTimeDeltaInMsec
    /// </summary>
    [FieldOffset(576)]
    public float InFrameTimeDeltaInMsec;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInRayTracingHitDistance
    /// </summary>
    [FieldOffset(584)]
    public void* PInRayTracingHitDistance;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInMotionVectorsReflections
    /// </summary>
    [FieldOffset(592)]
    public void* PInMotionVectorsReflections;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInTransparencyLayer
    /// </summary>
    [FieldOffset(600)]
    public void* PInTransparencyLayer;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InTransparencyLayerSubrectBase
    /// </summary>
    [FieldOffset(608)]
    public NGXCoordinatesNative InTransparencyLayerSubrectBase;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::pInTransparencyLayerOpacity
    /// </summary>
    [FieldOffset(616)]
    public void* PInTransparencyLayerOpacity;

    /// <summary>
    /// NVSDK_NGX_CUDA_DLSSD_Eval_Params::InTransparencyLayerOpacitySubrectBase
    /// </summary>
    [FieldOffset(624)]
    public NGXCoordinatesNative InTransparencyLayerOpacitySubrectBase;

    public NGXCUDADLSSDEvalParamsNative(in NGXCUDADLSSDEvalParams value)
    {
        this = default;

        try
        {
            PInDiffuseAlbedo = (void*)value.PInDiffuseAlbedo;
            PInSpecularAlbedo = (void*)value.PInSpecularAlbedo;
            PInNormals = (void*)value.PInNormals;
            PInRoughness = (void*)value.PInRoughness;
            PInColor = (void*)value.PInColor;
            PInOutput = (void*)value.PInOutput;
            PInDepth = (void*)value.PInDepth;
            PInMotionVectors = (void*)value.PInMotionVectors;
            InJitterOffsetX = value.InJitterOffsetX;
            InJitterOffsetY = value.InJitterOffsetY;
            InRenderSubrectDimensions = new(in value.InRenderSubrectDimensions);
            InReset = value.InReset;
            InMVScaleX = value.InMVScaleX;
            InMVScaleY = value.InMVScaleY;
            PInTransparencyMask = (void*)value.PInTransparencyMask;
            PInExposureTexture = (void*)value.PInExposureTexture;
            PInBiasCurrentColorMask = (void*)value.PInBiasCurrentColorMask;
            InDiffuseAlbedoSubrectBase = new(in value.InDiffuseAlbedoSubrectBase);
            InSpecularAlbedoSubrectBase = new(in value.InSpecularAlbedoSubrectBase);
            InNormalsSubrectBase = new(in value.InNormalsSubrectBase);
            InRoughnessSubrectBase = new(in value.InRoughnessSubrectBase);
            InColorSubrectBase = new(in value.InColorSubrectBase);
            InDepthSubrectBase = new(in value.InDepthSubrectBase);
            InMVSubrectBase = new(in value.InMVSubrectBase);
            InTranslucencySubrectBase = new(in value.InTranslucencySubrectBase);
            InBiasCurrentColorSubrectBase = new(in value.InBiasCurrentColorSubrectBase);
            InOutputSubrectBase = new(in value.InOutputSubrectBase);
            PInReflectedAlbedo = (void*)value.PInReflectedAlbedo;
            PInColorBeforeParticles = (void*)value.PInColorBeforeParticles;
            PInColorBeforeTransparency = (void*)value.PInColorBeforeTransparency;
            PInColorBeforeFog = (void*)value.PInColorBeforeFog;
            PInDiffuseHitDistance = (void*)value.PInDiffuseHitDistance;
            PInSpecularHitDistance = (void*)value.PInSpecularHitDistance;
            PInDiffuseRayDirection = (void*)value.PInDiffuseRayDirection;
            PInSpecularRayDirection = (void*)value.PInSpecularRayDirection;
            PInDiffuseRayDirectionHitDistance = (void*)value.PInDiffuseRayDirectionHitDistance;
            PInSpecularRayDirectionHitDistance = (void*)value.PInSpecularRayDirectionHitDistance;
            InReflectedAlbedoSubrectBase = new(in value.InReflectedAlbedoSubrectBase);
            InColorBeforeParticlesSubrectBase = new(in value.InColorBeforeParticlesSubrectBase);
            InColorBeforeTransparencySubrectBase = new(in value.InColorBeforeTransparencySubrectBase);
            InColorBeforeFogSubrectBase = new(in value.InColorBeforeFogSubrectBase);
            InDiffuseHitDistanceSubrectBase = new(in value.InDiffuseHitDistanceSubrectBase);
            InSpecularHitDistanceSubrectBase = new(in value.InSpecularHitDistanceSubrectBase);
            InDiffuseRayDirectionSubrectBase = new(in value.InDiffuseRayDirectionSubrectBase);
            InSpecularRayDirectionSubrectBase = new(in value.InSpecularRayDirectionSubrectBase);
            InDiffuseRayDirectionHitDistanceSubrectBase = new(in value.InDiffuseRayDirectionHitDistanceSubrectBase);
            InSpecularRayDirectionHitDistanceSubrectBase = new(in value.InSpecularRayDirectionHitDistanceSubrectBase);
            PInWorldToViewMatrix = value.PInWorldToViewMatrix.HasValue ? NGXMarshal.AllocValue(value.PInWorldToViewMatrix.Value) : null;
            PInViewToClipMatrix = value.PInViewToClipMatrix.HasValue ? NGXMarshal.AllocValue(value.PInViewToClipMatrix.Value) : null;
            InPreExposure = value.InPreExposure;
            InExposureScale = value.InExposureScale;
            InIndicatorInvertXAxis = value.InIndicatorInvertXAxis;
            InIndicatorInvertYAxis = value.InIndicatorInvertYAxis;
            GBufferSurface = new(in value.GBufferSurface);
            InToneMapperType = value.InToneMapperType;
            PInMotionVectors3D = (void*)value.PInMotionVectors3D;
            PInIsParticleMask = (void*)value.PInIsParticleMask;
            PInAnimatedTextureMask = (void*)value.PInAnimatedTextureMask;
            PInDepthHighRes = (void*)value.PInDepthHighRes;
            PInPositionViewSpace = (void*)value.PInPositionViewSpace;
            InFrameTimeDeltaInMsec = value.InFrameTimeDeltaInMsec;
            PInRayTracingHitDistance = (void*)value.PInRayTracingHitDistance;
            PInMotionVectorsReflections = (void*)value.PInMotionVectorsReflections;
            PInTransparencyLayer = (void*)value.PInTransparencyLayer;
            InTransparencyLayerSubrectBase = new(in value.InTransparencyLayerSubrectBase);
            PInTransparencyLayerOpacity = (void*)value.PInTransparencyLayerOpacity;
            InTransparencyLayerOpacitySubrectBase = new(in value.InTransparencyLayerOpacitySubrectBase);
        }
        catch
        {
            Dispose();

            throw;
        }
    }

    public void Dispose()
    {
        InTransparencyLayerOpacitySubrectBase.Dispose();
        InTransparencyLayerSubrectBase.Dispose();
        GBufferSurface.Dispose();
        NGXMarshal.Free(PInViewToClipMatrix);
        NGXMarshal.Free(PInWorldToViewMatrix);
        InSpecularRayDirectionHitDistanceSubrectBase.Dispose();
        InDiffuseRayDirectionHitDistanceSubrectBase.Dispose();
        InSpecularRayDirectionSubrectBase.Dispose();
        InDiffuseRayDirectionSubrectBase.Dispose();
        InSpecularHitDistanceSubrectBase.Dispose();
        InDiffuseHitDistanceSubrectBase.Dispose();
        InColorBeforeFogSubrectBase.Dispose();
        InColorBeforeTransparencySubrectBase.Dispose();
        InColorBeforeParticlesSubrectBase.Dispose();
        InReflectedAlbedoSubrectBase.Dispose();
        InOutputSubrectBase.Dispose();
        InBiasCurrentColorSubrectBase.Dispose();
        InTranslucencySubrectBase.Dispose();
        InMVSubrectBase.Dispose();
        InDepthSubrectBase.Dispose();
        InColorSubrectBase.Dispose();
        InRoughnessSubrectBase.Dispose();
        InNormalsSubrectBase.Dispose();
        InSpecularAlbedoSubrectBase.Dispose();
        InDiffuseAlbedoSubrectBase.Dispose();
        InRenderSubrectDimensions.Dispose();
        this = default;
    }
}
