// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_CUDA_Feature_Eval_Params. Owns only storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 24)]
internal unsafe partial struct NGXCUDAFeatureEvalParamsNative : IDisposable
{
    /// <summary>
    /// NVSDK_NGX_CUDA_Feature_Eval_Params::pInColor
    /// </summary>
    [FieldOffset(0)]
    public ulong* PInColor;

    /// <summary>
    /// NVSDK_NGX_CUDA_Feature_Eval_Params::pInOutput
    /// </summary>
    [FieldOffset(8)]
    public ulong* PInOutput;

    /// <summary>
    /// NVSDK_NGX_CUDA_Feature_Eval_Params::InSharpness
    /// </summary>
    [FieldOffset(16)]
    public float InSharpness;

    public NGXCUDAFeatureEvalParamsNative(in NGXCUDAFeatureEvalParams value)
    {
        this = default;

        try
        {
            PInColor = value.PInColor.HasValue ? NGXMarshal.AllocValue(value.PInColor.GetValueOrDefault()) : null;
            PInOutput = value.PInOutput.HasValue ? NGXMarshal.AllocValue(value.PInOutput.GetValueOrDefault()) : null;
            InSharpness = value.InSharpness;
        }
        catch
        {
            Dispose();
            throw;
        }
    }

    public void Dispose()
    {
        NGXMarshal.Free(PInColor);
        NGXMarshal.Free(PInOutput);
        this = default;
    }
}
