// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_Dimensions. Owns storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 8)]
internal unsafe struct NGXDimensionsNative : IDisposable
{
    /// <summary>
    /// NVSDK_NGX_Dimensions::Width
    /// </summary>
    [FieldOffset(0)]
    public uint Width;

    /// <summary>
    /// NVSDK_NGX_Dimensions::Height
    /// </summary>
    [FieldOffset(4)]
    public uint Height;

    public NGXDimensionsNative(in NGXDimensions value)
    {
        this = default;

        try
        {
            Width = value.Width;
            Height = value.Height;
        }
        catch
        {
            Dispose();

            throw;
        }
    }

    public void Dispose()
    {
        this = default;
    }
}
