// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_DLSSG_Opt_Eval_Params. Owns only storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 592)]
internal unsafe partial struct NGXDLSSGOptEvalParamsNative : IDisposable
{
    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::multiFrameCount
    /// </summary>
    [FieldOffset(0)]
    public uint MultiFrameCount;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::multiFrameIndex
    /// </summary>
    [FieldOffset(4)]
    public uint MultiFrameIndex;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraViewToClip
    /// </summary>
    [FieldOffset(8)]
    public Matrix4x4 CameraViewToClip;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::clipToCameraView
    /// </summary>
    [FieldOffset(72)]
    public Matrix4x4 ClipToCameraView;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::clipToLensClip
    /// </summary>
    [FieldOffset(136)]
    public Matrix4x4 ClipToLensClip;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::clipToPrevClip
    /// </summary>
    [FieldOffset(200)]
    public Matrix4x4 ClipToPrevClip;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::prevClipToClip
    /// </summary>
    [FieldOffset(264)]
    public Matrix4x4 PrevClipToClip;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::jitterOffset
    /// </summary>
    [FieldOffset(328)]
    public Vector2 JitterOffset;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::mvecScale
    /// </summary>
    [FieldOffset(336)]
    public Vector2 MvecScale;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraPinholeOffset
    /// </summary>
    [FieldOffset(344)]
    public Vector2 CameraPinholeOffset;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraPos
    /// </summary>
    [FieldOffset(352)]
    public Vector3 CameraPos;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraUp
    /// </summary>
    [FieldOffset(364)]
    public Vector3 CameraUp;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraRight
    /// </summary>
    [FieldOffset(376)]
    public Vector3 CameraRight;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraFwd
    /// </summary>
    [FieldOffset(388)]
    public Vector3 CameraFwd;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraNear
    /// </summary>
    [FieldOffset(400)]
    public float CameraNear;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraFar
    /// </summary>
    [FieldOffset(404)]
    public float CameraFar;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraFOV
    /// </summary>
    [FieldOffset(408)]
    public float CameraFOV;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraAspectRatio
    /// </summary>
    [FieldOffset(412)]
    public float CameraAspectRatio;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::colorBuffersHDR
    /// </summary>
    [FieldOffset(416)]
    public NGXBool8 ColorBuffersHDR;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::depthInverted
    /// </summary>
    [FieldOffset(417)]
    public NGXBool8 DepthInverted;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::cameraMotionIncluded
    /// </summary>
    [FieldOffset(418)]
    public NGXBool8 CameraMotionIncluded;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::reset
    /// </summary>
    [FieldOffset(419)]
    public NGXBool8 Reset;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::automodeOverrideReset
    /// </summary>
    [FieldOffset(420)]
    public NGXBool8 AutomodeOverrideReset;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::notRenderingGameFrames
    /// </summary>
    [FieldOffset(421)]
    public NGXBool8 NotRenderingGameFrames;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::orthoProjection
    /// </summary>
    [FieldOffset(422)]
    public NGXBool8 OrthoProjection;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::motionVectorsInvalidValue
    /// </summary>
    [FieldOffset(424)]
    public float MotionVectorsInvalidValue;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::motionVectorsDilated
    /// </summary>
    [FieldOffset(428)]
    public NGXBool8 MotionVectorsDilated;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::menuDetectionEnabled
    /// </summary>
    [FieldOffset(429)]
    public NGXBool8 MenuDetectionEnabled;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::mvecsSubrectBase
    /// </summary>
    [FieldOffset(432)]
    public NGXCoordinatesNative MvecsSubrectBase;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::mvecsSubrectSize
    /// </summary>
    [FieldOffset(440)]
    public NGXDimensionsNative MvecsSubrectSize;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::depthSubrectBase
    /// </summary>
    [FieldOffset(448)]
    public NGXCoordinatesNative DepthSubrectBase;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::depthSubrectSize
    /// </summary>
    [FieldOffset(456)]
    public NGXDimensionsNative DepthSubrectSize;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::hudLessSubrectBase
    /// </summary>
    [FieldOffset(464)]
    public NGXCoordinatesNative HudLessSubrectBase;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::hudLessSubrectSize
    /// </summary>
    [FieldOffset(472)]
    public NGXDimensionsNative HudLessSubrectSize;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::uiSubrectBase
    /// </summary>
    [FieldOffset(480)]
    public NGXCoordinatesNative UiSubrectBase;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::uiSubrectSize
    /// </summary>
    [FieldOffset(488)]
    public NGXDimensionsNative UiSubrectSize;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::uiAlphaSubrectBase
    /// </summary>
    [FieldOffset(496)]
    public NGXCoordinatesNative UiAlphaSubrectBase;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::uiAlphaSubrectSize
    /// </summary>
    [FieldOffset(504)]
    public NGXDimensionsNative UiAlphaSubrectSize;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::bidirectionalDistFieldSubrectBase
    /// </summary>
    [FieldOffset(512)]
    public NGXCoordinatesNative BidirectionalDistFieldSubrectBase;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::bidirectionalDistFieldSubrectSize
    /// </summary>
    [FieldOffset(520)]
    public NGXDimensionsNative BidirectionalDistFieldSubrectSize;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::bidirectionalDistFieldPrecisionInfo
    /// </summary>
    [FieldOffset(528)]
    public NGXPrecisionInfoNative BidirectionalDistFieldPrecisionInfo;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::minRelativeLinearDepthObjectSeparation
    /// </summary>
    [FieldOffset(540)]
    public float MinRelativeLinearDepthObjectSeparation;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::backbufferSubrectBase
    /// </summary>
    [FieldOffset(544)]
    public NGXCoordinatesNative BackbufferSubrectBase;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::backbufferSubrectSize
    /// </summary>
    [FieldOffset(552)]
    public NGXDimensionsNative BackbufferSubrectSize;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::outputInterpSubrectBase
    /// </summary>
    [FieldOffset(560)]
    public NGXCoordinatesNative OutputInterpSubrectBase;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::outputInterpSubrectSize
    /// </summary>
    [FieldOffset(568)]
    public NGXDimensionsNative OutputInterpSubrectSize;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::outputRealSubrectBase
    /// </summary>
    [FieldOffset(576)]
    public NGXCoordinatesNative OutputRealSubrectBase;

    /// <summary>
    /// NVSDK_NGX_DLSSG_Opt_Eval_Params::outputRealSubrectSize
    /// </summary>
    [FieldOffset(584)]
    public NGXDimensionsNative OutputRealSubrectSize;

    public NGXDLSSGOptEvalParamsNative(in NGXDLSSGOptEvalParams value)
    {
        this = default;

        try
        {
            MultiFrameCount = value.MultiFrameCount;
            MultiFrameIndex = value.MultiFrameIndex;
            CameraViewToClip = value.CameraViewToClip;
            ClipToCameraView = value.ClipToCameraView;
            ClipToLensClip = value.ClipToLensClip;
            ClipToPrevClip = value.ClipToPrevClip;
            PrevClipToClip = value.PrevClipToClip;
            JitterOffset = value.JitterOffset;
            MvecScale = value.MvecScale;
            CameraPinholeOffset = value.CameraPinholeOffset;
            CameraPos = value.CameraPos;
            CameraUp = value.CameraUp;
            CameraRight = value.CameraRight;
            CameraFwd = value.CameraFwd;
            CameraNear = value.CameraNear;
            CameraFar = value.CameraFar;
            CameraFOV = value.CameraFOV;
            CameraAspectRatio = value.CameraAspectRatio;
            ColorBuffersHDR = value.ColorBuffersHDR;
            DepthInverted = value.DepthInverted;
            CameraMotionIncluded = value.CameraMotionIncluded;
            Reset = value.Reset;
            AutomodeOverrideReset = value.AutomodeOverrideReset;
            NotRenderingGameFrames = value.NotRenderingGameFrames;
            OrthoProjection = value.OrthoProjection;
            MotionVectorsInvalidValue = value.MotionVectorsInvalidValue;
            MotionVectorsDilated = value.MotionVectorsDilated;
            MenuDetectionEnabled = value.MenuDetectionEnabled;
            MvecsSubrectBase = new(in value.MvecsSubrectBase);
            MvecsSubrectSize = new(in value.MvecsSubrectSize);
            DepthSubrectBase = new(in value.DepthSubrectBase);
            DepthSubrectSize = new(in value.DepthSubrectSize);
            HudLessSubrectBase = new(in value.HudLessSubrectBase);
            HudLessSubrectSize = new(in value.HudLessSubrectSize);
            UiSubrectBase = new(in value.UiSubrectBase);
            UiSubrectSize = new(in value.UiSubrectSize);
            UiAlphaSubrectBase = new(in value.UiAlphaSubrectBase);
            UiAlphaSubrectSize = new(in value.UiAlphaSubrectSize);
            BidirectionalDistFieldSubrectBase = new(in value.BidirectionalDistFieldSubrectBase);
            BidirectionalDistFieldSubrectSize = new(in value.BidirectionalDistFieldSubrectSize);
            BidirectionalDistFieldPrecisionInfo = new(in value.BidirectionalDistFieldPrecisionInfo);
            MinRelativeLinearDepthObjectSeparation = value.MinRelativeLinearDepthObjectSeparation;
            BackbufferSubrectBase = new(in value.BackbufferSubrectBase);
            BackbufferSubrectSize = new(in value.BackbufferSubrectSize);
            OutputInterpSubrectBase = new(in value.OutputInterpSubrectBase);
            OutputInterpSubrectSize = new(in value.OutputInterpSubrectSize);
            OutputRealSubrectBase = new(in value.OutputRealSubrectBase);
            OutputRealSubrectSize = new(in value.OutputRealSubrectSize);
        }
        catch
        {
            Dispose();
            throw;
        }
    }

    public void Dispose()
    {
        MvecsSubrectBase.Dispose();
        MvecsSubrectSize.Dispose();
        DepthSubrectBase.Dispose();
        DepthSubrectSize.Dispose();
        HudLessSubrectBase.Dispose();
        HudLessSubrectSize.Dispose();
        UiSubrectBase.Dispose();
        UiSubrectSize.Dispose();
        UiAlphaSubrectBase.Dispose();
        UiAlphaSubrectSize.Dispose();
        BidirectionalDistFieldSubrectBase.Dispose();
        BidirectionalDistFieldSubrectSize.Dispose();
        BidirectionalDistFieldPrecisionInfo.Dispose();
        BackbufferSubrectBase.Dispose();
        BackbufferSubrectSize.Dispose();
        OutputInterpSubrectBase.Dispose();
        OutputInterpSubrectSize.Dispose();
        OutputRealSubrectBase.Dispose();
        OutputRealSubrectSize.Dispose();
        this = default;
    }
}
