// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_D3D12_GBuffer. Owns only storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 136)]
internal unsafe partial struct NGXD3D12GBufferNative : IDisposable
{
    /// <summary>
    /// NVSDK_NGX_D3D12_GBuffer::pInAttrib
    /// </summary>
    [FieldOffset(0)]
    public PInAttribBuffer PInAttrib;

    [InlineArray(17)]
    internal struct PInAttribBuffer
    {
        private nint element;
    }

    public NGXD3D12GBufferNative(in NGXD3D12GBuffer value)
    {
        this = default;

        try
        {
            if (value.PInAttrib is { } itemsPInAttrib)
            {
                if (itemsPInAttrib.Length > 17) throw new ArgumentException("PInAttrib accepts at most 17 elements.", nameof(value));
                for (int i = 0; i < itemsPInAttrib.Length; i++)
                {
                    PInAttrib[i] = itemsPInAttrib[i];
                }
            }
        }
        catch
        {
            Dispose();
            throw;
        }
    }

    public void Dispose()
    {
        this = default;
    }
}
