// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_PrecisionInfo. Owns only storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 12)]
internal unsafe partial struct NGXPrecisionInfoNative : IDisposable
{
    /// <summary>
    /// NVSDK_NGX_PrecisionInfo::IsLowPrecision
    /// </summary>
    [FieldOffset(0)]
    public uint IsLowPrecision;

    /// <summary>
    /// NVSDK_NGX_PrecisionInfo::Bias
    /// </summary>
    [FieldOffset(4)]
    public float Bias;

    /// <summary>
    /// NVSDK_NGX_PrecisionInfo::Scale
    /// </summary>
    [FieldOffset(8)]
    public float Scale;

    public NGXPrecisionInfoNative(in NGXPrecisionInfo value)
    {
        this = default;

        try
        {
            IsLowPrecision = value.IsLowPrecision;
            Bias = value.Bias;
            Scale = value.Scale;
        }
        catch
        {
            Dispose();
            throw;
        }
    }

    public void Dispose()
    {
        this = default;
    }
}
