// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// NVSDK_NGX_ProjectIdDescription. Owns storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 24)]
internal unsafe struct NGXProjectIdDescriptionNative : IDisposable
{
    /// <summary>
    /// NVSDK_NGX_ProjectIdDescription::ProjectId
    /// </summary>
    [FieldOffset(0)]
    public sbyte* ProjectId;

    /// <summary>
    /// NVSDK_NGX_ProjectIdDescription::EngineType
    /// </summary>
    [FieldOffset(8)]
    public NGXEngineType EngineType;

    /// <summary>
    /// NVSDK_NGX_ProjectIdDescription::EngineVersion
    /// </summary>
    [FieldOffset(16)]
    public sbyte* EngineVersion;

    public NGXProjectIdDescriptionNative(in NGXProjectIdDescription value)
    {
        this = default;

        try
        {
            ProjectId = (sbyte*)NGXMarshal.TextToPtr(value.ProjectId, NGXEncoding.Utf8);
            EngineType = value.EngineType;
            EngineVersion = (sbyte*)NGXMarshal.TextToPtr(value.EngineVersion, NGXEncoding.Utf8);
        }
        catch
        {
            Dispose();

            throw;
        }
    }

    public void Dispose()
    {
        NGXMarshal.Free(EngineVersion);
        NGXMarshal.Free(ProjectId);
        this = default;
    }
}
