// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// Anonymous_94_5. Owns storage allocated by managed conversion.
/// </summary>
[StructLayout(LayoutKind.Explicit, Size = 48)]
internal unsafe struct NGXResourceVKUnionNative : IDisposable
{
    /// <summary>
    /// Anonymous_94_5::ImageViewInfo
    /// </summary>
    [FieldOffset(0)]
    public NGXImageViewInfoVKNative ImageViewInfo;

    /// <summary>
    /// Anonymous_94_5::BufferInfo
    /// </summary>
    [FieldOffset(0)]
    public NGXBufferInfoVKNative BufferInfo;

    public NGXResourceVKUnionNative(in NGXResourceVKUnion value)
    {
        this = default;

        try
        {
            if (value.ImageViewInfo.HasValue && value.BufferInfo.HasValue)
            {
                throw new ArgumentException("Only one union member may be specified.", nameof(value));
            }

            if (value.ImageViewInfo is NGXImageViewInfoVK member0)
            {
                ImageViewInfo = new(in member0);
            }
            else if (value.BufferInfo is NGXBufferInfoVK member1)
            {
                BufferInfo = new(in member1);
            }
        }
        catch
        {
            Dispose();

            throw;
        }
    }

    public void Dispose()
    {
        this = default;
    }
}
