// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.InteropServices;

namespace NGX.NET;

internal static partial class NgxCallbacks
{
    internal static nint Acquire(NGXAppLogCallback? callback)
    {
        if (callback is null) return 0;

        NGXAppLogCallback guarded = (string? message, NGXLoggingLevel loggingLevel, NGXFeature sourceComponent) =>
        {
            try
            {
                callback(message, loggingLevel, sourceComponent);
            }
            catch (Exception exception)
            {
                Report(exception);
            }
        };

        return Register(guarded);
    }

    internal static nint Acquire(NGXPfnProgressCallback? callback)
    {
        if (callback is null) return 0;

        NGXPfnProgressCallback guarded = (float progress, ref bool shouldCancel) =>
        {
            try
            {
                callback(progress, ref shouldCancel);
            }
            catch (Exception exception)
            {
                Report(exception);
                shouldCancel = true;
            }
        };

        return Register(guarded);
    }

    internal static nint Acquire(NGXPfnProgressCallbackC? callback)
    {
        if (callback is null) return 0;

        NGXPfnProgressCallbackC guarded = (float progress, ref bool shouldCancel) =>
        {
            try
            {
                callback(progress, ref shouldCancel);
            }
            catch (Exception exception)
            {
                Report(exception);
                shouldCancel = true;
            }
        };

        return Register(guarded);
    }

}
