// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// PFN_NVSDK_NGX_DLSSG_GetCurrentSettingsCallback. Keep callback code alive while NGX retains it; never let managed exceptions cross this ABI.
/// </summary>
[NGXNativeName("PFN_NVSDK_NGX_DLSSG_GetCurrentSettingsCallback")]
[StructLayout(LayoutKind.Sequential)]
public readonly unsafe struct NGXPfnDLSSGGetCurrentSettingsCallback(delegate* unmanaged[Cdecl]<global::NGX.NET.NGXHandle*, global::NGX.NET.NGXParameter*, global::NGX.NET.NGXResult> pointer)
{
    /// <summary>
    /// Native C callback pointer. C++ reference parameters use their pointer ABI.
    /// </summary>
    public readonly delegate* unmanaged[Cdecl]<global::NGX.NET.NGXHandle*, global::NGX.NET.NGXParameter*, global::NGX.NET.NGXResult> Pointer = pointer;
}
