// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// PFN_NVSDK_NGX_D3D12_ResourceAllocCallback
/// </summary>
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate void NGXPfnD3D12ResourceAllocCallback(nint description, int state, nint heap, out nint resource);
