// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// PFN_NVSDK_NGX_Parameter_SetI. Keep callback code alive while NGX retains it; never let managed exceptions cross this ABI.
/// </summary>
[NGXNativeName("PFN_NVSDK_NGX_Parameter_SetI")]
[StructLayout(LayoutKind.Sequential)]
public readonly unsafe struct NGXPfnParameterSetI(delegate* unmanaged[Cdecl]<NGXParameter*, sbyte*, int, void> pointer)
{
    /// <summary>
    /// Native C callback pointer. C++ reference parameters use their pointer ABI.
    /// </summary>
    public readonly delegate* unmanaged[Cdecl]<NGXParameter*, sbyte*, int, void> Pointer = pointer;
}
