// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// PFN_NVSDK_NGX_Parameter_GetUI. Borrowed SDK callbacks require a live source; raw managed registrations require caller-owned roots and exception containment.
/// </summary>
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate NGXResult NGXPfnParameterGetUI(NGXParameter parameters, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name, out uint value);
