// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// PFN_NVSDK_NGX_ProgressCallback. Keep callback code alive while NGX retains it; never let managed exceptions cross this ABI.
/// </summary>
[NGXNativeName("PFN_NVSDK_NGX_ProgressCallback")]
[StructLayout(LayoutKind.Sequential)]
public readonly unsafe struct NGXPfnProgressCallback(delegate* unmanaged[Cdecl]<float, global::NGX.NET.NGXBool8*, void> pointer)
{
    /// <summary>
    /// Native C callback pointer. C++ reference parameters use their pointer ABI.
    /// </summary>
    public readonly delegate* unmanaged[Cdecl]<float, global::NGX.NET.NGXBool8*, void> Pointer = pointer;
}
