// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

#nullable enable

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// PFN_NVSDK_NGX_Parameter_SetULL
/// </summary>
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate void NGXPfnParameterSetULL(NGXParameter parameters, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name, ulong value);
