// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// PFN_NVSDK_NGX_Parameter_GetD3d12Resource. Keep callback code alive while NGX retains it; never let managed exceptions cross this ABI.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public readonly unsafe struct NGXPfnParameterGetD3d12Resource(delegate* unmanaged[Cdecl]<NGXParameter*, sbyte*, nint*, NGXResult> pointer)
{
    /// <summary>
    /// Native C callback pointer. C++ reference parameters use their pointer ABI.
    /// </summary>
    public readonly delegate* unmanaged[Cdecl]<NGXParameter*, sbyte*, nint*, NGXResult> Pointer = pointer;
}
