// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// PFN_NVSDK_NGX_D3D12_ResourceAllocCallback. Keep callback code alive while NGX retains it; never let managed exceptions cross this ABI.
/// </summary>
[NativeName("PFN_NVSDK_NGX_D3D12_ResourceAllocCallback")]
[StructLayout(LayoutKind.Sequential)]
public readonly unsafe struct PfnD3D12ResourceAllocCallback(delegate* unmanaged[Cdecl]<nint, int, nint, nint*, void> pointer)
{
    /// <summary>
    /// Native C callback pointer. C++ reference parameters use their pointer ABI.
    /// </summary>
    public readonly delegate* unmanaged[Cdecl]<nint, int, nint, nint*, void> Pointer = pointer;
}
