// <auto-generated/>
// Generated by NGX.NET.Generator. Changes belong in the generator.

using System.Runtime.InteropServices;

namespace NGX.NET;

/// <summary>
/// PFN_NVSDK_NGX_Parameter_SetVoidPointer. Keep callback code alive while NGX retains it; never let managed exceptions cross this ABI.
/// </summary>
[NativeName("PFN_NVSDK_NGX_Parameter_SetVoidPointer")]
[StructLayout(LayoutKind.Sequential)]
public readonly unsafe struct PfnParameterSetVoidPointer(delegate* unmanaged[Cdecl]<global::NGX.NET.Parameter*, sbyte*, void*, void> pointer)
{
    /// <summary>
    /// Native C callback pointer. C++ reference parameters use their pointer ABI.
    /// </summary>
    public readonly delegate* unmanaged[Cdecl]<global::NGX.NET.Parameter*, sbyte*, void*, void> Pointer = pointer;
}
